### ISSUE TITLE
[NPC] Fleet Master Firallon

### ISSUE THREAD

**Issue by phonkala** [SallyWhitemane/Maelstrom#112]
**Description:**
Now that issue/quest https://github.com/SallyWhitemane/Maelstrom/issues/53 got fixed, went to complete it. Fleet Master Firallon fell straight throught the boat on attack. He was outside / under the boat standing in water, combat reseted, but attacking him again worked normally and was able to complete the quest.

![WoWScrnShot_061422_110610](https://user-images.githubusercontent.com/43609330/173526953-191020aa-1387-4b18-8d18-d0b72c2eaeb8.jpg)

**Comment by ghost** [comment]
Works okay to me.
