### ISSUE TITLE
[NPC] Foe Reaper 5000 now unattackable after fix

### ISSUE THREAD

**Issue by phonkala** [SallyWhitemane/Maelstrom#113]
**Description:**
Went into Deadmines to finish the dungeon now after fixes, but now the Foe Reaper 5000 event is more bugged than before fix.

2) The adds in boss room (Defias Watchers / Defias Reapers) should attack you. Currently they just stand still and wait you to kill them.
3) The adds should turn friendly around 20-30% hp so you can mount them and attack other adds/boss. While mounted, their hp should slowly go down (no matter if not attacked - they get debuff called "On Fire!") and when they hit 0% hp, they kinda "zap" the boss (like before fix).
4) When 4th add dies, boss should lose it's "Off-line" buff, which makes it unattackable. Currently as the adds no longer do
the "zap" part to boss when they die, the buff is never taken away from boss and you can never attack Foe Reaper 5000. Boss is not skippable so can't proceed further in dungeon.

Not sure if this all is just because now the adds are wrong ones in the boss room, can't remember how it was before fix. How it should work: https://youtu.be/sWTAGVRJ0oY?t=150

For some reason, in the video it does not do the "zap" part when adds die, but before fix on ptr that did work well.

**Comment by Afgann** [comment]
fixed
