### ISSUE TITLE
NPC Zuni is Pasive

### ISSUE THREAD

**Issue by ElFuegoBaby** [SallyWhitemane/Maelstrom#115]
Description : NPZ Zuni ( https://wowpedia.fandom.com/wiki/Zuni - https://www.wowhead.com/npc=38423/zuni ) Should assist you while fighting nagas in the cave for the quest https://www.wowhead.com/quest=24812/no-more-mercy

**How to reproduce:** Get the quest https://www.wowhead.com/quest=24812/no-more-mercy , start attacking naga and watch Zuni doing nothing

**How it should work:** Zuni should help you battle the nagas

**Comment by Afgann** [comment]
fixed
