### ISSUE TITLE
[Generic] Attacking still sometimes makes the target bugged

### ISSUE THREAD

**Issue by phonkala** [SallyWhitemane/Maelstrom#118]
**Description:**
This was fixed already, but seems it still happens sometimes. The target just keeps resetting hp to full, won't move or attack you and keeps you in combat.

In most cases regarding stealth this was fixed, but seems to still happen, though very rarely. Now it happened again when I attacked Lord Darkscythe from stealth. I am using a macro that only starts autoattack when not in stealth, so maybe this isn't anymore a stealth/autoattack issue and is something completely different.

I will add more info if/when this occurs, but it seems to be very rare now.

**Comment by ghost** [comment]
@phonkala More info about NPCs/mobs, maybe some screenshots/clips?

**Comment by phonkala** [comment]
I wish I had more, this has not happened since the fixes, but now it did. Exactly same behaviour than earlier with the stealth into autoattack bug.

If this happens again, I will take screenshot but like said, exactly same behaviour than before the fix. Could not reproduce it on other mobs and so far I think this has been only time after the fixes that this happens.

**Comment by phonkala** [comment]
This happened again with Volchan, and I was not even in stealth.
![173771548-64259eeb-2ef7-44d3-89fa-4dbbd8d3ac24](https://user-images.githubusercontent.com/43609330/173771834-a29688a5-ddfe-4561-a281-2be272343b19.jpg)

Right now it seems to me that whenever the target isn't able to instantly attack me (maybe because of pathing, but could also be that it misses, or I dodge etc), it gets bugged. Will be posting more info whenever possible.

**Comment by phonkala** [comment]
Same happened with Silt Crawler, I was not stealthed. It felt like it had no path to me and got bugged (stayed still, healed to full nonstop, kept me in combat), basicly just evaded as mobs do when they can't get to you. Used shadowmeld and it reseted like always.

**Comment by phonkala** [comment]
Happened again with Razorsaw in Outlands, I just used feral charge (not stealthed) to attack him, this time he just kept walking and did not attack me, health kept resetting to full as usual. Shadowmeld > it reseted and attacked me > all good again.

**Comment by phonkala** [comment]
Possibly related too, at least sounds like it: https://github.com/SallyWhitemane/Maelstrom/issues/148

**Comment by phonkala** [comment]
Also from our Discord: NPC Gluggl was also reported for similar behaviour. Obviously this is still (kinda random) issue as there are still multiple occurrences. Won't be posting more reports of this unless it's later wished/required.
