### ISSUE TITLE
[NPC] Gahz'rilla keeps getting summoned unlimited(?) times

### ISSUE THREAD

**Issue by phonkala** [SallyWhitemane/Maelstrom#120]
**Description:**
Was testing the Zul'Farrak bosses and all but Gahz'rilla were doable. I clicked the gong and Gahz'rilla was summoned and I pulled it, but then realized there was 2 or 3 of those and more kept coming. Died to see if it resets, ran back in and then there was like 100 of them :)

![WoWScrnShot_061422_151757](https://user-images.githubusercontent.com/43609330/173576526-d7b5fced-aa6a-4158-aa28-7c22bd745e08.jpg)
![WoWScrnShot_061422_152152](https://user-images.githubusercontent.com/43609330/173576527-5e95d90a-9ab6-48e2-8dc3-975405613305.jpg)

**Comment by Afgann** [comment]
fixed
