### ISSUE TITLE
[Quest] The Twilight Skymaster id=28098

### ISSUE THREAD

**Issue by bartekdcm** [SallyWhitemane/Maelstrom#126]
**Description:**
We're suposed to get a flight (path).  We control mount and can't get off it.
[https://www.wowhead.com/quest=28098/the-twilight-skymaster](url)

**How it should work:**
Flight to destination, uncontrollable by player.

**Comment by MrTide** [comment]
Also players can still mount him after finish the quest atm
i don't think fix is live atm so i can't do further testing atm
