### ISSUE TITLE
Taking fall damage from finishing flying trip from Ironforge Airfield back to gol'bolar quarry.

### ISSUE THREAD

**Issue by Craxzycubu** [SallyWhitemane/Maelstrom#133]
**Description:**
You can take a charter flying machine from gol'bolar quarry to Ironforge airfield, when you take the flight back to gol'bolar, u die from falldamge as the journey ends.

**How to reproduce:**
take charter flight from ironforge airfield back to gol'bolar.

**How it should work:**
no die pls

**Comment by ghost** [comment]
Cannot reproduce it.
