### ISSUE TITLE
Quest : An Ancient Enemy

### ISSUE THREAD

**Issue by ElFuegoBaby** [SallyWhitemane/Maelstrom#136]
At the quest https://www.wowhead.com/quest=24814/an-ancient-enemy you need to fight  Zar'jira the sea witch ( https://www.wowhead.com/npc=38306/zarjira ) 
During the fight you are assisted by few NPC that deal dmg, give buffs etc
In last phase she froze the NPC how it should but they stay in the ice tomb and make it imposible to kill her 

**How to reproduce:**

Get the quest An ancient enemy, move on  the top of the cave and start the encounter 
**How it should work:**
https://www.youtube.com/watch?v=BtpK9zTNAzA

**Comment by ghost** [comment]
Everything works okay. Just wait a little.
