### ISSUE TITLE
NPC Muyoh

### ISSUE THREAD

**Issue by ElFuegoBaby** [SallyWhitemane/Maelstrom#140]
**Description:**
After killing all the bosses in WC dungeon, you need to speak with Muyoh ( https://www.wowhead.com/npc=3678/muyoh ) and he should proceed to summon last boss
All good here, however, he literally RUN and he should walk. Also he dosent stop to assist killing mobs 

**How to reproduce:**
Kill all the bosses on WC then speak with Muyoh

**How it should work:**
After you speak with him at the entrance of dungeon, he should walk to last boss and  assist you to kill mobs on his way.

**Comment by Afgann** [comment]
fixed
