### ISSUE TITLE
Orgrimmar Grunts ( guards ) 

### ISSUE THREAD

**Issue by ElFuegoBaby** [SallyWhitemane/Maelstrom#143]
**Description:**

Orgrimmar grunts donse't stop when you talk with them

**How to reproduce:**
Get a horde char, go to Orgrimmar and talk with a guard that patrol 

**How it should work:**

When you interact with them and the window with directions open, they should stop and wait til you finish

**Comment by ElFuegoBaby** [comment]
![image](https://user-images.githubusercontent.com/94279719/173996444-196b7a3f-cadf-451e-80d8-0af893257349.png)

Same issue with Razorhill Grunts 

To test more town NPC later

**Comment by ElFuegoBaby** [comment]
I have confirmation that is the same for the alliance guard NPCs

**Comment by Afgann** [comment]
fixed
