### ISSUE TITLE
Blax Bottlerocket slightly bugged

### ISSUE THREAD

**Issue by ElFuegoBaby** [SallyWhitemane/Maelstrom#144]
**Description:**
blax bottlerocket slightly bugged. He is a patroling NPC in Orgrimmar that sell toys, after you interact with him he stops. 
However, after you close the buy window he should start patroling again but he dosent

**How to reproduce:**
Get a horde char, talk with the NPC, close the window

**How it should work:**

After you close the trade window and stop interacting with him, he should start patroling

**Comment by ElFuegoBaby** [comment]
https://www.wowhead.com/npc=52809/blax-bottlerocket

**Comment by ghost** [comment]
Works okay - stops for 3 minutes.
