### ISSUE TITLE
[Dungeon] Stratholme - Maelstorm

### ISSUE THREAD

**Issue by Arkasus11** [SallyWhitemane/Maelstrom#146]
Quests only come after completing the dungeon
no quests from start.

affects both parts of the dungeon, both part Balnazzar and Baron Aurius

**Comment by ghost** [comment]
It's Blizz.

**Comment by MrTide** [comment]
Wrong they should be available more info here
https://github.com/SallyWhitemane/Maelstrom/issues/561
https://github.com/SallyWhitemane/Maelstrom/issues/560
