### ISSUE TITLE
Rare spawn pathing

### ISSUE THREAD

**Issue by Craxzycubu** [SallyWhitemane/Maelstrom#148]
**Description:**
When you encounter rare spawns in the open world, that has a routed path (IE walking back and forth) you cannot get agro from the rare spawn by attacking it, nor from being close to it. it just regains health every 2 sec, and keeps walking.

**How to reproduce:**
find a rare spawn with a pathing, and try to attack it. 

**How it should work:**
it should agro to you.

**Comment by Craxzycubu** [comment]
i found that, as a shaman, i can put down a totem near it, and it will get agro from that, and then me, to be able to actually kill them.

**Comment by Afgann** [comment]
fixed
