### ISSUE TITLE
[Quest] Just Hatched does not pop up during Bad Medicine.

### ISSUE THREAD

**Issue by Craxzycubu** [SallyWhitemane/Maelstrom#149]
**Description:**
During Bad Medicine, the quest Just hatched doesnt pop up, however, on completion, you gain the hatchling as a pet(not really a pet, because you cannot summon or desummon it) 

**How to reproduce:**
Complete the Bad Medicine Quest, as alliance. 

**How it should work:**
 [https://wowpedia.fandom.com/wiki/Just_Hatched](url)

**Comment by Craxzycubu** [comment]
Also, the current lashtail hatchling you get from the bad medicine quest, has wrong dialog..
![image](https://user-images.githubusercontent.com/107545199/174064976-27508f99-dc9e-4895-81ee-577731eedcc4.png)

**Comment by ghost** [comment]
Quest does show up correctly.
