### ISSUE TITLE
Rain of destruction - Quest - slightly bugged

### ISSUE THREAD

**Issue by ElFuegoBaby** [SallyWhitemane/Maelstrom#151]
**Description:**
After you accept the quest Rain of destruction ( https://www.wowhead.com/quest=13798/rain-of-destruction#comments ) you get morphed into a imp and start proceding with the quest. However, if you lose the imp morph, you can return to Durak ( https://www.wowhead.com/npc=33977/durak ) and he will give you the imp form back
**How to reproduce:**
Accept the quest and proceed into tower and kill the quest mobs, when you return, you will lose the Imp form and can`t get it back from Durak

**How it should work:**

Durak should give you option to get imp form back

![image](https://user-images.githubusercontent.com/94279719/174074337-ddaac2f8-7fd0-4058-b5fc-b66daf46a0ec.png)

**Comment by ghost** [comment]
This is #71 for extra context; I will add that after multiple attempts of abandoning and re-completing the quest, I was eventually able to make it back to Durak and turn the quest in while in imp form. However, it appears to be very inconsistent as to whether or not imp form breaks while walking through the tunnel.
