### ISSUE TITLE
[Dungeon][BRD] Small list of bugs from my first solo run in Blackrock Depths

### ISSUE THREAD

**Issue by phonkala** [SallyWhitemane/Maelstrom#152]
Blackrock Depths, did a solo run as a druid. Saw few bugs which are listed here:
- Grim Guzzler area - breaking the kegs never summoned the boss Hurley Blackbreath, as it should.
- Grim Guzzler area - Patrons don't turn hostile after killing Plugger Spazzring, they should.
- Died and ran in again, Panzor (rare) was back up (had killed it already). I don't think it should respawn that fast.
- Thaurissan kept casting Hand of Thaurissan (stun) way too often, pretty much every time the stun ended. So was almost permanently stunned.

**Comment by ghost** [comment]
`haurissan kept casting Hand of Thaurissan (stun) way too often, pretty much every time the stun ended. So was almost permanently stunned.`
This ability shoud have no cooldown.
Other problems fixed.

**Comment by phonkala** [comment]
Awesome! Just for a note, at least on ChromieCraft (WotLK/AzerothCore) they made it to have random schedule (urand(4000, 7000)) for the ability, not a static one (5000) like in TrinityCore Cata. Not sure how it's done on Maelstrom though.

- https://github.com/azerothcore/azerothcore-wotlk/blob/master/src/server/scripts/EasternKingdoms/BlackrockMountain/BlackrockDepths/boss_emperor_dagran_thaurissan.cpp#L121
- https://github.com/The-Cataclysm-Preservation-Project/TrinityCore/blob/master/src/server/scripts/EasternKingdoms/BlackrockMountain/BlackrockDepths/boss_emperor_dagran_thaurissan.cpp#L102
