### ISSUE TITLE
[Racial Ability] Cannibalize doesn't find corpse

### ISSUE THREAD

**Issue by OrthoTemplar** [SallyWhitemane/Maelstrom#155]
**Description:**
When trying to cast Cannibalize it gives a error "There are no nearby corpses to eat"

**How to reproduce:** 
1. Defeat undead or humanoid mob
2. Try to use [Cannibalize](https://wowwiki-archive.fandom.com/wiki/Cannibalize) (tried on un-looted and looted corpse)
3. Receive red error text message in the upper-middle of the screen "There are no nearby corpses to eat"

**How it should work:**
Ability should start to channel and apply healing until done or interrupted

![WoWScrnShot_061622_202036](https://user-images.githubusercontent.com/102799057/174129914-965e0b09-80c3-4363-89d7-bc339acbd10f.jpg)

**Comment by Afgann** [comment]
fixed
