### ISSUE TITLE
[Environment] Floating bear rug - Deathknell

### ISSUE THREAD

**Issue by OrthoTemplar** [SallyWhitemane/Maelstrom#157]
**Description:**
In Deathknell in the hut with the Armorer and Weaponsmith Vendors the bear rug is floating a bit over an undead male char's ankle in height.

**How it should work:**
Bear rugs should respect gravity and stay put on the floor.

![WoWScrnShot_061622_204358](https://user-images.githubusercontent.com/102799057/174134022-51b58e2e-76d4-4f30-906c-72e8077655e0.jpg)

**Comment by UltraNix** [comment]
Looks okay.

**Comment by ghost** [comment]
Clientside texture.
