### ISSUE TITLE
[NPC] Rare spawn Spiteflayer won't aggro

### ISSUE THREAD

**Issue by ghost** [SallyWhitemane/Maelstrom#158]
**Description:**
Wowhead: https://www.wowhead.com/npc=8299/spiteflayer

When attacked, Spiteflayer ignores the player, continues patrolling, and regenerates health, keeping the player stuck in combat until force closing the game.

I'll add that this is one of many "rare spawn" NPCs that have this behavior, as many other rare NPCs seem to have this exact same behavior issue. #15 #73 are a couple of examples. Generally referenced in #148 

**How to reproduce:**
- Attack Spiteflayer
- Note that it doesn't aggro

**How it should work:**
Spiteflayer should aggro like any other mob,

**Comment by Afgann** [comment]
fixed
