### ISSUE TITLE
[Dungeon][SM] Scarlet Monastery Graveyard - Fallen Champion can't get to you.

### ISSUE THREAD

**Issue by phonkala** [SallyWhitemane/Maelstrom#159]
**Description:**
Went into Scarlet Monastery and entered Graveyard. Found the rare Fallen Champion and used Faerie Fire on it, but it could not come attack me, it was stuck on the "platform". It reseted about 5 sec later, I did the same thing and it couldn't run to me then either. Went to the platform myself and killed it, that worked fine.

![WoWScrnShot_061622_214750](https://user-images.githubusercontent.com/43609330/174145750-da5cc4b2-e377-44a0-a3b8-cdb89285ed2b.jpg)

**Comment by Afgann** [comment]
fixed
