### ISSUE TITLE
Arcane Patroller does not take damage and aggro

### ISSUE THREAD

**Issue by bovanova1** [SallyWhitemane/Maelstrom#16]
**Description:**
There is a Arcane Patroller that constantly goes in circles in Ruins of Silvermoon. He cannot be aggroed and he does not take damage.
But the mob initiates the combat bug. Meaning once you attack him you stay in Combat (until alt + f4 or get killed)

**How to reproduce:**
Attack Arcane Patroller that is going in circles

**How it should work:**
He supposed to take damage and aggro and try  n kill you .. but he ignores you

https://user-images.githubusercontent.com/106834485/171983848-e9e433f8-9675-4cd8-a654-bb37e7776ee3.mp4

**Comment by ghost** [comment]
@bovanova1 Cannot reproduce it.

**Comment by ghost** [comment]
Please, retest it.

**Comment by bovanova1** [comment]
I could not reproduce this again.
