### ISSUE TITLE
[System message] Unable to zone in while an encounter is in progress

### ISSUE THREAD

**Issue by phonkala** [SallyWhitemane/Maelstrom#160]
**Description:**
Was planning to do all Scarlet Monastery dungeons to test them, but after clearing Graveyeard I ran out and tried to enter Library. Upon entering, I got instantly teleported to my hearthstone location and got the system message "Unable to zone in while an encounter is in progress".

I flew back and this time went into Cathedral, same message "Unable to zone in while an encounter is in progress" and was teleported to my hearthstone location. Made sure I was not combat etc.

Dunno if this really an issue or just requires server restart or something, but reported it here anyways as it prevented me from entering the dungeons.

**Comment by phonkala** [comment]
Went to Stormwind after and was able to enter Stockade. So flew back to Scarlet Monastery and entered Armory, and once again got teleported to my hearthstone location with same message.

**Comment by phonkala** [comment]
I believe the quest Val'kyr Incursion (https://github.com/SallyWhitemane/Maelstrom/issues/117) is causing this. The quest it currently bugged and can't be completed (no valkyrs in the area). However, I had the quest in my quest book.

When flying to Scarlet Monastery, I saw a friendly Enthralled Val'kyr appear midflight (yeah weird place, not even close to the quest area) and fall to the ground. So I assumed game somehow thinks I'm doing that encounter. Deleted the quest, relogged and was able to enter Scarlet Monastery dungeons again.

![WoWScrnShot_061622_223343](https://user-images.githubusercontent.com/43609330/174151145-bb280b76-84c8-4e09-b735-9edccbf8efbd.jpg)

**Comment by ghost** [comment]
Cannot reproduce it.

**Comment by phonkala** [comment]
I don't believe issues should be closed just if one person can't reproduce it, this isn't the first one. Well, I mean your call of course but obviously something is bugged if stuff like this happens and there's even screenshot of it. It feels kinda like saying "well if I can't get this to happen, it doesn't matter" :)

**Comment by ghost** [comment]
I tried for 1 hour to reproduce it. If something bugs out from time to time - it's hard to fix it.
