### ISSUE TITLE
[Dungeon][SM] Whitemane should not die before resummoning Mograine

### ISSUE THREAD

**Issue by phonkala** [SallyWhitemane/Maelstrom#165]
**Description:**
In Scarlet Monastery Cathedral, I attacked the final boss Mograine. After killing him, High Inquisitor Whitemane comes in and you have to fight her. I set up bleeds on her, and she cast her stun at 50% hp like she should.

However, my bleeds killed her during the stun and she did not have time to cast the resurrect, which resurrects Mograine. The boss event ended on her death.

**How it should work:**
Whitemane should never die before casting the resurrect, she should stay at 1 hp at least. After the resurrect, both bosses should go back to 100% hp and killing them both ends up completing the dungeon quests.

**Additional notes**
After first run, I did reset the dungeon and try again, this time not killing Whitemane too fast. Then everything worked well.

**Comment by Afgann** [comment]
fixed
