### ISSUE TITLE
[NPC] Yetimus the Yeti Lord doesn't aggro, continues patrolling

### ISSUE THREAD

**Issue by ghost** [SallyWhitemane/Maelstrom#166]
**Description:**
Wowhead: https://www.wowhead.com/npc=47484/yetimus-the-yeti-lord

Upon attacking Yetimus, he does not aggro, regenerates health, and keeps attackers stuck in combat. Same patrolling behavior as multiple other bugged mobs.

**How to reproduce:**
- Attack Yetimus
- Note that he continues patrolling

**How it should work:**
Yetimus should aggro and fight upon being attacked.

**Comment by ghost** [comment]
Upon logging out and back in, I was able to attack him and he aggroed as expected. I used the same spell to pull (Frostbolt), so I'm not sure why the behavior was inconsistent.

**Comment by Afgann** [comment]
fixed
