### ISSUE TITLE
[Dungeon][Gnomeregan] Crazed Leper Gnomes got way too high drop % of bags

### ISSUE THREAD

**Issue by phonkala** [SallyWhitemane/Maelstrom#167]
**Description:**
Crazed Leper Gnomes outside the dungeon have way too high drop % of bags (Small Brown/GreenBlue/Red Pouch). Killed around 30 gnomes, got 13 bags. Drop chance should be easily below 1% as links below show.

https://cata-twinhead.twinstar.cz/EQ?npc=46391#drop:100-13+1
https://www.wowhead.com/npc=46363/crazed-leper-gnome

**Comment by Afgann** [comment]
fixed
