### ISSUE TITLE
[Dungeon][Sunken Temple] Morphas and Hazzas evade during knockback

### ISSUE THREAD

**Issue by phonkala** [SallyWhitemane/Maelstrom#169]
**Description:**
Morphaz and Hazzas knockback sometimes makes them evade while I'm in air. They are still attackable again after landing, but sometimes reset health to full (when evading). This happened to me on 3 knockbacks, but not on every one. Killable, but makes the fight quite long if they reset a lot.

**Comment by ghost** [comment]
@phonkala Cannot reproduce it. Can you record it?

**Comment by phonkala** [comment]
Could not reproduce either, possibly fixed with some other update? It used to happen kinda "a lot", like every second or third knockback at least. Now I didn't get it to happen at all.

**Comment by ghost** [comment]
Perhaps already fixed.
