### ISSUE TITLE
Worgen starting area completely scuffed

### ISSUE THREAD

**Issue by GreenTactician** [SallyWhitemane/Maelstrom#17]
**Description:**
Spawn in at beginning of Worgen starting experience, Merchant Square. Floors are missing, Buildings are missing, floor can be seen from some angles occasionally.

**How to reproduce:**
Create a Worgen.

**How it should work:**
There should be floors and buildings.

**Comment by phonkala** [comment]
Everything looks perfectly fine to me. I would suggest to clear client cache.

**Comment by ghost** [comment]
@GreenTactician Provide some screenshots.

**Comment by GreenTactician** [comment]
This was fixed like 5 minutes after i posted it two nights ago, so i assume there was some switch that needed to be flipped lol. regardless it was scuffed when i posted and got fixed, how do i close this
