### ISSUE TITLE
[Quest] Brother against Brother

### ISSUE THREAD

**Issue by Craxzycubu** [SallyWhitemane/Maelstrom#171]
**Description:**
The forsaken troopers in andorhal is spawning much ealier in the quest chain than what they are supposed to. They spawn at initial start of quest chain, which is at lvl 35, but forsaken troops doesnt spawn until the Brother against brother quest, and they are level 40. can give issues when navigating the questing area at lvl 34-35. 

**How to reproduce:**
stand in andorhal without completion of the quest chain in the area.

**How it should work:**
troopers spawn correctly when the Brother against brother is reached, but that they also spawn much ealier, which they are not supposed to.

**Comment by ghost** [comment]
They spawn after https://www.wowhead.com/quest=27205/the-depravity-of-the-forsaken completed, so it's only one quest before.
