### ISSUE TITLE
[Quest] Val'kyr incursion

### ISSUE THREAD

**Issue by Craxzycubu** [SallyWhitemane/Maelstrom#172]
**Description:**
Val'kyr's doesnt spawn in the area.

**How to reproduce:**
accept the Val'kyr incursion quest in andorhal. 

**How it should work:**
They should be in the area.

**Comment by phonkala** [comment]
Duplicate of https://github.com/SallyWhitemane/Maelstrom/issues/117 . That one was closed so I believe it's fixed whenever next update becomes live on PTR.

**Comment by ghost** [comment]
Yep.
