### ISSUE TITLE
[Dungeon][RFK] Agethelos the Raging evading randomly

### ISSUE THREAD

**Issue by phonkala** [SallyWhitemane/Maelstrom#174]
**Description:**
Attacked Agethelos the Raging in Razorfen Kraul before he finished his path coming from the cave. He did not attack, and evaded when he reached the end of the path. He stayed evaded while I stayed in his range, when I ran bit away he reseted the evade bug.

Then mid combat, he suddenly evaded again for no reason so something might be bit bugged with him. This repeated 4 times, until I just used all cooldowns and managed to kill him before he had chance to evade again.

![WoWScrnShot_061722_110312](https://user-images.githubusercontent.com/43609330/174262467-a4ee6763-186b-4ea2-9793-9c3d5d240def.jpg)

**Comment by Afgann** [comment]
fixed
