### ISSUE TITLE
[Dungeon][WC] Final boss rp event issues

### ISSUE THREAD

**Issue by phonkala** [SallyWhitemane/Maelstrom#177]
**Description:**
After killing all but last boss in Wailing Caverns, you go back to the entrance of the dungeon talk to Muyoh which then starts the final rp event where you escort and protect him on the way to last boss room.

1) Myuoh should stop to fight any mobs. Currently he just runs past them all, which kinda forces the party to pull huge amount of mobs while running to the last boss room. This might work with well geared players and if the path was cleared of mobs beforehand, but might also result into a wipe if lower geared players.

2) Also in the last boss room, while Myuoh is doing the rp / casting, there are 3 Deviate Moccasins summoned that should attack you. Summoning works, but 2 of the moccasins seem to always evade and reset in the water. Had same evade issue with the last boss Mutanus the Devourer too. All killable after they reset, but this just makes the boss event lots easier than it should be.
 
![WoWScrnShot_061722_113510](https://user-images.githubusercontent.com/43609330/174262131-f5225b2b-ab18-455d-838b-fb1a0f9d9f3e.jpg)

**Comment by Afgann** [comment]
fixed
