### ISSUE TITLE
[Dungeon][BFD] Summoned mobs after Lord Kelris won't attack, hp resets to full

### ISSUE THREAD

**Issue by phonkala** [SallyWhitemane/Maelstrom#178]
**Description:**
In Blackfathom Deeps, after killing Twilight Lord Kelris you use the braciers around the statue, clicking each of them summons a different packs of mobs that should attack you.

However, the mobs don't attack, they evade at their summon locations. They dont attack even if you go stand on top of them and keep resetting health to full when attacked, so low level party probably can't kill them and can never proceed forward in the dungeon as the doors won't open until the mobs are killed.

![WoWScrnShot_061722_115513](https://user-images.githubusercontent.com/43609330/174264718-296a26f3-a2d0-4d5f-a8b3-f2794f0cfb1c.jpg)

**Comment by Afgann** [comment]
fixed
