### ISSUE TITLE
Quest "Evacuate Merchant Square" in Worgen starting zone has issues

### ISSUE THREAD

**Issue by GreenTactician** [SallyWhitemane/Maelstrom#18]
**Description:**
Doors that you knock on are supposed to rest so they can be used again, it would seem none of the doors are resetting so if enough people make Worgen there won't be any doors for them to advance quest. Some of them will also have an aggressive Rampaging Worgen run out that attacks you, it wont actually attack you, and you can't attack it, so it just follows you around seemingly forever.

**How to reproduce:**
Pick up the quest Evacuate the Merchant Square from Prince Liam

**How it should work:**
Doors should reset eventually, Rampaging Worgen should be attackable.

**Comment by ghost** [comment]
Doors are reset after 30 sec.
