### ISSUE TITLE
[Dungeon][DM] Dire Maul North - list of bugs

### ISSUE THREAD

**Issue by phonkala** [SallyWhitemane/Maelstrom#184]
- Guard Mol'dar pathing bit off, goes through the slope next to him and shows falling animation.
- Looting Ogre Tannin Basket had nothing in it. There should tannin to complete the ogre suit quest. https://www.youtube.com/watch?v=yFAEbbo3VlA&t=1025s 
- Captain Kromcrush should not have his adds summoned at start. (check from same video)
- Attacking Cho'Rush should make King Gordok attack you too, and other way around too.
- After killing King Gordok there should be that NPC running in ("tribute run NPC") and doing the rp. After the rp all ogres should turn friendly too, which now did not happen.
- Also, tried to run back to the start of the dungeon but the last door before last boss was closed. It should be open.

**Comment by ghost** [comment]
`Looting Ogre Tannin Basket had nothing in it. There should tannin to complete the ogre suit quest.` works okay with quest.

**Comment by ghost** [comment]
Tribute Chest event works okay. Cho'Rush aggroes with King Gordok.
