### ISSUE TITLE
[NPC] Shadowpine Catlord pets Ghostclaw Lynx

### ISSUE THREAD

**Issue by MrTide** [SallyWhitemane/Maelstrom#189]
**Description:** This issue is related to Ghostclaw Lynx which are summoned by Shadowpine catlords

**How to reproduce:** Ghostclaw Lynx Chase you forever and don't follow their master agrro reset 
![image](https://user-images.githubusercontent.com/36106057/174338698-613350b2-909d-40f2-92a1-cd11500c1828.png)
and after killing their pets their master dont aggro at all and keep healing also keep you in combat. ( remember to reproduce the bug that master dont hit you.. you need to separate the pet and master from each other by pulling the pet away)
![image](https://user-images.githubusercontent.com/36106057/174339188-d103f7ee-34bb-4328-875a-4ca558573531.png)

**How it should work:** they should reset and go back to their summoner/master
and also their master should be killable afterwards and should not lock you in combat for no reason

**Comment by ghost** [comment]
Already fixed.
