### ISSUE TITLE
First Worgen Pet "Young Mastiff" has uncontrollable bloodlust

### ISSUE THREAD

**Issue by GreenTactician** [SallyWhitemane/Maelstrom#19]
**Description:**
First pet hunters can summon, for Worgen is Young Mastiff. I believe hunters can't see the pets control bar until level 10, which would be ok, but it would seem this pet started on "universal aggression" setting because from the moment i entered combat, after we killed the enemy, he just started chasing down and murdering every enemy it can reach, even ones back in the previous area i came from. He is now out of bounds killing something i can't even see.

**How to reproduce:**
Summon first Hunter pet in Worgen starting zone, attack and kill a creature with it out, it just starts running everywhere.

**How it should work:**
Either pets normally start on Aggressive and its not supposed to be this aggressive, or pets normally start on defensive/assist mode, which is what i think its supposed to be since you can't normally change it until level 10.

**Comment by ghost** [comment]
Pet is on assist mode.
I can't reproduce it.
