### ISSUE TITLE
[Quest] Crisis at Splintertree

### ISSUE THREAD

**Issue by Freemind0** [SallyWhitemane/Maelstrom#194]
**Description:**
There are no elves spawning on the road, Gorka also sits inside of you, instead of infront & shes not shooting any arrows on supposed elf targets. Theres also missing voicelines.
Screenshot below shows the entire chat during the quest. 
![image](https://user-images.githubusercontent.com/56369938/174389622-d26c6f6d-5b76-4e61-a823-99a8dd2d807c.png)

**How to reproduce:**
Pick up the quest from Gorka at the Warsong Labor Camp.
Idk how it works with GMs giving themselves the quests, but there were a few quests prior to this one. 
Not sure on the entire chain, i just started questing from the Ashenvale/Barrens border that took me to her eventually.

**How it should work:**
Should be elves on the road, Gorka should be talking & so should the elves & Gorka should then shoot fire arrows at them, killing them. But non of that happens.

https://www.youtube.com/watch?v=f5wCl8ruIBA

**Comment by MrTide** [comment]
This event/quest still have issues 
https://github.com/SallyWhitemane/Maelstrom/issues/517
