### ISSUE TITLE
[Quest] Playing with Felfire

### ISSUE THREAD

**Issue by Freemind0** [SallyWhitemane/Maelstrom#197]
**Description:**
You can endlessly siphon felfire from 1 fire. 
Was able to siphon this one endlessly
![image](https://user-images.githubusercontent.com/56369938/174392706-6eb5eb54-2de7-448e-ac5d-586de0fcf8f4.png)

**How to reproduce:**
Pick up quest from Splintertree outpost & start siphoning a fire, it will be repeatable on the same fire.

**How it should work:**

Each fire should vanish after a siphon.

https://youtu.be/AzBzJVg-A6s?t=49

**Comment by MrTide** [comment]
Confirmed, same thing happened to me
