### ISSUE TITLE
[NPC] Ashenvale skirmisher

### ISSUE THREAD

**Issue by MrTide** [SallyWhitemane/Maelstrom#199]
**Description:**
ashenvale entrance from northern barren side have issues (horde) 

**How to reproduce:** there are a lot of npcs  at 1hp specially alliance side
![image](https://user-images.githubusercontent.com/36106057/174393344-25c36d29-a9fa-4640-a086-cbd499831969.png)
which also sometimes yield  exp and loot when players kills them (might also cause issues with dynamic respawn) they should not take damage from eachother (other npcs) like horde counter part
Some even hitting the corpses the whole event there requires developers attention
![image](https://user-images.githubusercontent.com/36106057/174393399-b4967170-4b26-46e5-ba2b-cd6078f427d2.png)
![image](https://user-images.githubusercontent.com/36106057/174393439-956ccc4f-14ad-4f8d-bde9-d7d1490cd3cf.png)
![image](https://user-images.githubusercontent.com/36106057/174393578-fad1b90a-d23e-483c-b48d-4ec904fc37de.png)
![image](https://user-images.githubusercontent.com/36106057/174394299-dbee99ea-9537-44c9-9d19-ec9497f69fa5.png)

**How it should work:**
this video briefly shows how event should work npcs that are fighting outside should not damage eachother and those that attack to the gate.. horde guards should be able to kill them and also they should not spawn all at once at the gate.
https://www.youtube.com/watch?v=fzD0DXTb8g0
https://www.youtube.com/watch?v=y6P4p5exy2o

----------------------------------------

I recommend the same method of Corrupted Cliff giants which their health goes to max once players hits them
![image](https://user-images.githubusercontent.com/36106057/174480625-27cec6d8-6738-4ccc-b010-8489499e1f93.png) you can find them in ferelas 
![image](https://user-images.githubusercontent.com/36106057/174480660-6641fab1-084b-4b6f-988e-caedff87e04e.png)

![image](https://user-images.githubusercontent.com/36106057/174480675-691be055-2726-4354-ae00-177f0958a56b.png)

**Comment by Freemind0** [comment]
Already reported in issue #190 which also includes the Bowmen.

**Comment by MrTide** [comment]
This issue still not fixed
