### ISSUE TITLE
[Quest] Rain of Destruction Ashenvale Splintertree post.

### ISSUE THREAD

**Issue by Freemind0** [SallyWhitemane/Maelstrom#202]
**Description:**
Randomly lost my Imp suit while running (had some issues at start of quest, had to re apply the imp suit a few times).
And i lost it at the end of the quest, leaving me unable to turn in the quest cuz it told me i had to be in imp form but i couldn't put it on because the npc did not give me an option to.

After i completed the quest, the entire area phased back to normal, but should still be "under attack." So in the cave rocks should fall down & the miners should still cover in fear, but they stop it. I think it also goes hand in hand with losing the imp suit. I think it phases you out of it & removes your imp suit. 

![image](https://user-images.githubusercontent.com/56369938/174397598-d966f0e4-d695-4ff4-9a6c-7c7b2eb1e6b5.png)

**How to reproduce:**
Pick up quest, try using auto run & running around, it's a bit hard to trigger this.
But i got it while autorunning away from the npc to the quest area & running bk to npc with autorun on.

**How it should work:**
Should not lose the imp suit. You should also be given the option to re apply the imp form when talking to the npc.
The area should still be phased even after you're done with the quest prior to turning it in.

https://www.youtube.com/watch?v=elKLWO9DQEI

**Comment by MrTide** [comment]
Same thing happened to me as well.

**Comment by ghost** [comment]
Fixed.
