### ISSUE TITLE
[NPC] Rare Spawn Rorgish jowl 

### ISSUE THREAD

**Issue by MrTide** [SallyWhitemane/Maelstrom#204]
**Description:** Rare Spawn Rorgish is an npc that can be found in ashenvale zone

**How to reproduce:**
NPC simply ignores damage from players like nothing happens and heals up and also keeps players in combat
![image](https://user-images.githubusercontent.com/36106057/174404498-da2db0d3-817f-4682-a1f1-d04b40ca4bc6.png)

**How it should work:** players should be able to kill it.

**Comment by ghost** [comment]
Fixed.
