### ISSUE TITLE
No loot dropping from many neutral mobs (including quest items)

### ISSUE THREAD

**Issue by phonkala** [SallyWhitemane/Maelstrom#21]
**Description:**
Was about to report issue with quest items in nelf starting area not dropping, but seems none of the mobs in the area drop anything. Was doing the quest "Fel Moss Corruption" where you loot Fel Moss from grells/grellkins, but _nothing_ dropped in ~20 kills. Decided to test killing other animals in area, absolutely no loot after 30-40 kills. Also tried making a human character and instantly got loot from first kill.

**How to reproduce:**
Create nelf (mine is a druid, didn't test other class in same area), kill stuff, nothing drops.

**Comment by phonkala** [comment]
Couple more ppl joined the nelf starting area, same issue.

**Comment by phonkala** [comment]
Seems to be only issue with the neutral mobs in the nelf area. Human area neutral mobs do drop loot though.

**Comment by phonkala** [comment]
Seems to be same issue with many originally neutral mobs. Also James Clark for the quest "Wanted: James Clark" does not drop loot, it's a mob that is neutral that you need to kill to loot the item.

**Comment by UltraNix** [comment]
Just testit in Shadowglen and with dfirrent quests - works okay now.
