### ISSUE TITLE
Pathfinding on mobs that can both swim in water and walk on land

### ISSUE THREAD

**Issue by angel-krastev** [SallyWhitemane/Maelstrom#217]
**Description:**
I encountered this first with some crawlers in the troll's starting zone - I was standing on the land and I pulled a mob that was underwater. The mob could not find a way to get to me and evaded. This also happens when fighting a crawler in water and jumping out of water. A similar issue is the reversed situation of pulling a mob from the land into the water and jumping a few times - it starts evading and resets.

**How to reproduce:**
Simply try pulling a mob from underwater whilst standing on the land. Try pulling a mob from underwater while you are in the water and jump over the water a few times. Try pulling a mob from the land to the water and jumping over the water a few times.

**How it should work:**
I think mobs that can both swim and walk should have no problems chasing you from land to water and the other way around.

**Comment by ghost** [comment]
Fixed.
