### ISSUE TITLE
[Quest] Mr. D's Wild Ride

### ISSUE THREAD

**Issue by MrTide** [SallyWhitemane/Maelstrom#219]
**Description:** NPC dont have enough HP 

**How to reproduce:** Large daddy NPC should have around 4000 HP not 210
![image](https://user-images.githubusercontent.com/36106057/174434499-de1adee9-48c2-4f1e-961b-41c87ba8361b.png)
![image](https://user-images.githubusercontent.com/36106057/174434717-f8d0dbb9-aeee-48de-b60a-fa6d971ce5d7.png)
![image](https://user-images.githubusercontent.com/36106057/174434764-14cc65ac-295b-47dd-9293-381c11bd8737.png)

**How it should work:** it should have 4000hp https://cata-twinhead.twinstar.cz/?npc=41954

**Comment by Freemind0** [comment]
To add to this, the helmet should not float that high above the machine you're in.
It should be ontop of the greenglass on the shredder.
