### ISSUE TITLE
 [Quest] All Becoming Clearer

### ISSUE THREAD

**Issue by MrTide** [SallyWhitemane/Maelstrom#225]
**Description:** All Becoming Clearer credit trigger is not working at all
 
**How to reproduce:** Its not working players can't complete it
![image](https://user-images.githubusercontent.com/36106057/174440018-ec8790aa-3aa1-4426-a202-c0c1033b48a6.png)

**How it should work:**  like the video listed below
https://www.youtube.com/watch?v=w7SO0YFVXjw

**Comment by ghost** [comment]
Works okay.
