### ISSUE TITLE
[QUEST] Searing Gorge - Set Them Ablaze!

### ISSUE THREAD

**Issue by Lex449** [SallyWhitemane/Maelstrom#231]
**Description:**
Set the North, South, East, and West Sentry Towers on fire by using the [Torch of Retribution](https://classic.wowhead.com/item=10515/torch-of-retribution) inside each of the buildings.

**How to reproduce:**
North, South and West work fine but in the East tower the Item for interaction is missing like in the screenshot.

**How it should work:**
The East Tower need this item (Sentry Brazier (object=149025))
![WoWScrnShot_061822_220714](https://user-images.githubusercontent.com/107636988/174455720-11ac78ba-f377-4b48-8da7-cdee4c72860f.jpg)
![WoWScrnShot_061822_220943](https://user-images.githubusercontent.com/107636988/174455724-192ac661-7b4d-4846-bf4f-031b0f918bc3.jpg)

**Comment by MrTide** [comment]
Not fixed opened a new report 
https://github.com/SallyWhitemane/Maelstrom/issues/447
![image](https://user-images.githubusercontent.com/36106057/177416454-e6dffd85-6c2c-402e-8eda-ea78731b5fe2.png)
Should go back and test every closed report ? :\
