### ISSUE TITLE
[Quest] Changing of the Gar'dul

### ISSUE THREAD

**Issue by ElFuegoBaby** [SallyWhitemane/Maelstrom#235]
**Description:** You go on top of the tower and wait for the RP ( is working <3 ) then go down to deliver the q
NPC never shows

**How to reproduce:** accept the q https://www.wowhead.com/quest=24591/changing-of-the-gardul , run at the top of the tower, wait for the RP event to complete then go down and....wait 

**How it should work:**

after the RP ends you should be able to deliver the q 

https://www.wowhead.com/quest=24591/changing-of-the-gardul#videos:id=194905

**Comment by ghost** [comment]
Quest is autorewared.
