### ISSUE TITLE
[Quest][Tanaris] Rocket Rescue uncompletable

### ISSUE THREAD

**Issue by SylahUmehara1** [SallyWhitemane/Maelstrom#236]
**Description:** Quest Rocket Rescue (ID 25050) does not function,  quest can be accepted and balloon can be boarded.  But all Steamwheedle Survivors (NPC id 38571) cannot be rescued and Blockaders remain unkillable.  Quest can  be abandoned but balloon cannot be exited,  requires ALT+F4 to exit the balloon

**How to reproduce:** Participating in quest will show this.

**How it should work:** The quest should function as shown in this video - https://www.youtube.com/watch?v=SFGGsLbyeHA

**Comment by ghost** [comment]
Works okay.
