### ISSUE TITLE
[Unknown NPC] Arelas BrightStar

### ISSUE THREAD

**Issue by MrTide** [SallyWhitemane/Maelstrom#240]
**Description:** this npc is supposed to be on argent but can be found in desolace in the air

**How to reproduce:** there are also multiple spawn points for it
![image](https://user-images.githubusercontent.com/36106057/174479813-0831af51-d1fa-4568-b46d-a6743395dbee.png)
![image](https://user-images.githubusercontent.com/36106057/174479835-0beba3ab-a66a-4407-a2c6-7412cf1e0d27.png)

**How it should work:** i don't believe it should be here specially with this display ID also its ID belongs to a invisible stalker i will post it down below
https://cata-twinhead.twinstar.cz/?npc=35592
![image](https://user-images.githubusercontent.com/36106057/174479880-005afb3a-19ea-4b42-a0a8-e1e455cfd332.png)

**Comment by Afgann** [comment]
fixed
