### ISSUE TITLE
[Quest] Murder Was The Case That They Gave Me - npcs bugged

### ISSUE THREAD

**Issue by phonkala** [SallyWhitemane/Maelstrom#25]
**Description:**
In the quest (Westfall) you have to talk to the West Plains Drifters to find all four clues to complete quest. You always have two options when talking to them, and sometimes clicking other one starts a fight with the drifters. However, seems that sometimes they clearly engage into combat but don't attack you and also stay unattackable and just follow you, keeping you in combat forever. Quest can still be completed while they follow you.

**Comment by Hewlith** [comment]
Can Confirm this is the case. Also some of the Npc's do not have any talk options.

**Comment by UltraNix** [comment]
Cannot reproduce it.
