### ISSUE TITLE
 [Quest] Go Blow that Horn

### ISSUE THREAD

**Issue by MrTide** [SallyWhitemane/Maelstrom#250]
**Description:** This quest is offered on Thousand Needles

**How to reproduce:** Summed NPC won't attack the player
![image](https://user-images.githubusercontent.com/36106057/174489624-a655c698-87af-44c4-8f9a-20f6c257afda.png)
 just stands there

**How it should work:** It should fight the player like the video below
https://www.youtube.com/watch?v=SuGzZcPeudc

**Comment by Afgann** [comment]
fixed
