### ISSUE TITLE
Warlock Pets Not Regenerating Mana

### ISSUE THREAD

**Issue by Enider890** [SallyWhitemane/Maelstrom#251]
**Description:** Warlock pets are not regenerating mana which means once they are empty they cannot use abilities anymore.

**How to reproduce:** Summon a warlock pet and have it use abilities. Watch the mana and how it stays where it is over long periods, never regenerates. Note the time from the top-right on the minimap in each screenshot and how the pet hasn't regenerated any mana at all.

![Warlock Felguard Mana 1](https://user-images.githubusercontent.com/45482752/174502600-07b8e96f-6598-429f-be88-6c0a14de248d.PNG)

![Warlock Felguard Mana 2](https://user-images.githubusercontent.com/45482752/174502624-07535c13-0dc9-4288-a517-d76b87921392.PNG)

I have only attached screenshots of felguard, but the same is happening with every pet.

**How it should work:** Demons should regenerate mana so that they can continue using their abilities.

**Comment by phonkala** [comment]
Can confirm this at least with fresh warlock using Imp as pet.

**Comment by Afgann** [comment]
fixed
