### ISSUE TITLE
[Item] Vanishing Powder missing from all(?) vendors

### ISSUE THREAD

**Issue by phonkala** [SallyWhitemane/Maelstrom#253]
**Description:**
Was about to unlearn some glyphs and at my current level it requires Vanishing Powder. Checked 3 of the reagents vendors in Stormwind and also Engineer Curtis Paddock at the shore and none had Vanishing Powder for sale (they should). Could be issue with all vendors that are supposed to sell it?

https://cata-twinhead.twinstar.cz/?item=64670#sold-by

**Comment by phonkala** [comment]
Finally found this item from Inscription Supplies NPC. I do think this is incorrect, based on the earlier link and this one too: https://wowwiki-archive.fandom.com/wiki/Vanishing_Powder

"It is sold by reagent vendors and can be crafted by Scribes with a skill level of 75."

However, the in-game tooltip says it is sold by inscription vendors, so not sure which is correct.

**Comment by Afgann** [comment]
fixed
