### ISSUE TITLE
[Quest] The Perfect Horns

### ISSUE THREAD

**Issue by MrTide** [SallyWhitemane/Maelstrom#254]
**Description:** This quest is offered to the players in winterspring

**How to reproduce:** after finishing this quest you can't turn it back in 
The Perfect Horns NPC simply don't accept it
![image](https://user-images.githubusercontent.com/36106057/174578470-fbe053f4-0efb-4816-a780-ff1cc792a45d.png)

**How it should work:** you should be able to turn it back in.

**Comment by MrTide** [comment]
Similar issue https://github.com/SallyWhitemane/Maelstrom/issues/255
https://github.com/SallyWhitemane/Maelstrom/issues/256

**Comment by Afgann** [comment]
fixed
