### ISSUE TITLE
[Quest]  Are We There, Yeti?

### ISSUE THREAD

**Issue by MrTide** [SallyWhitemane/Maelstrom#255]
**Description:** This quest is offered to the players in winterspring

**How to reproduce:** after finishing the quest you can't turn it back in
![image](https://user-images.githubusercontent.com/36106057/174578724-0b382b0d-2db7-4cbc-89b3-79d05e38d9de.png)

**How it should work:** you should be able to turn the quest back in

**Comment by Afgann** [comment]
fixed
