### ISSUE TITLE
[Quest] Yetiphobia

### ISSUE THREAD

**Issue by MrTide** [SallyWhitemane/Maelstrom#256]
**Description:**  This quest is offered to the players in winterspring

**How to reproduce:** after using the yeti next to Legacki she won't react and won't run away (missing animations) and after finishing the quest you can't turn the quest back in either
![image](https://user-images.githubusercontent.com/36106057/174580253-72930fc2-faf4-43b9-a1e8-b70af93ed449.png)

**How it should work:** you should be able to turn the quest back in and also yeti start chasing legacki around
https://www.youtube.com/watch?v=pjbdxgu24f8

**Comment by Afgann** [comment]
fixed
