### ISSUE TITLE
[NPC] Doomguard Destroyer

### ISSUE THREAD

**Issue by MrTide** [SallyWhitemane/Maelstrom#263]
**Description:** These creatures can be found in blasted land

**How to reproduce:** they simply fall under ground and still hit the player while you can't hit them back
https://user-images.githubusercontent.com/36106057/174611027-a81c4077-3bf8-4472-affb-1db57cd83c35.mp4
![image](https://user-images.githubusercontent.com/36106057/174611162-edb1daec-0d86-4f25-9c4c-ed258f686441.png)

**How it should work:** They should not fall under ground and players should be able to kill them

**Comment by Afgann** [comment]
fixed
