### ISSUE TITLE
[Core Mechanic][NPC] [Missing mechanic] NPC positioning during combat 

### ISSUE THREAD

**Issue by MrTide** [SallyWhitemane/Maelstrom#264]
**Description:** 
Two prominent combat features from retail are currently missing in This core

**Wrong and correct behaviors:** If a single NPC is too close to the player it should reposition itself by walking backwards. here they just stay on top of you
![image](https://user-images.githubusercontent.com/36106057/174615332-90be60e1-d5d1-47bd-a7b7-3da1a4fc25e3.png)

If multiple NPCs are attacking the same player, they should reposition themselves after a brief period by walking to form a circle/cone shape in front of the player so they do not stack on top of each other. 
![image](https://user-images.githubusercontent.com/36106057/174615470-a326f670-659b-4f15-b333-0d88741d183d.png)

**Comment by MrTide** [comment]
@[UltraNix](https://github.com/UltraNix) Well done with the fix but stacking while moving can use improvements 
This is sunwell
![image](https://user-images.githubusercontent.com/36106057/176322060-b8e2f82a-346e-4d92-9a8a-d516cc882c9a.png)
This is Maelstorm
![image](https://user-images.githubusercontent.com/36106057/176322110-3c20d759-a339-475e-8d6f-67dd13f3ce07.png)
I am just walking backwards

**Comment by ghost** [comment]
@MrTide New report please.
