### ISSUE TITLE
[Quest/Proffesion] Sharing the knowledge

### ISSUE THREAD

**Issue by Craxzycubu** [SallyWhitemane/Maelstrom#265]
**Description:**
The sandy book in twillight base camp should reward you with a quest to learn the Smoked Desert dumpling (cooking) but when you interract with the book, it simply states: Greetings Stonks. 

**How to reproduce:**
interract with the sandy book in twillight base camp at level 54+ (perhaps some cooking requirement, my guess would be 275 ish)

**How it should work:**
[https://cata-twinhead.twinstar.cz/?quest=8313](url)

**Comment by Craxzycubu** [comment]
nevermind, you need 285 cooking to see the quest.

**Comment by MrTide** [comment]
you can close it if you think its working as intended
