### ISSUE TITLE
[Quest] Delicate Negotiations [Core issue] [Vehicles]

### ISSUE THREAD

**Issue by GMHiki** [SallyWhitemane/Maelstrom#266]
**Description:**
questID=14318
Vehicle should be taxi and take you on a waypointed path, but it does not, just give you a vehicle you are stuck in with the previous bugs described in my other tickets (no waypointed path, doesnt let you dismount, when you dismount you get stuck etc)

**How to reproduce:**
take quest, see.

**How it should work:**
Quest should taxi you on a vehicle to the destination (fatherstone in desolace)

**Comment by ghost** [comment]
Fixed.
