### ISSUE TITLE
[Quest] Cleansing our Crevasse [Vehicles]

### ISSUE THREAD

**Issue by GMHiki** [SallyWhitemane/Maelstrom#267]
**Description:**
quest 14381
again, vehicles are fucked up and dont do what they are supposed to, no waypointed path, some dont allow flying, some dont allow you to use their skills, etc.

This one specifically does not fly on waypointed path, and does not allow you to use the vehicle skills to kill the mobs.

**How to reproduce:**
take quest and see

**How it should work:**
this quest should fly you on a waypointed path while you use a vehicle skill to kill the naga in the crevasse and then flies you back.

**Comment by ghost** [comment]
Fixed.
