### ISSUE TITLE
[NPC] Cliff Stormer Stonetalon Mountains

### ISSUE THREAD

**Issue by Freemind0** [SallyWhitemane/Maelstrom#271]
**Description:**
![image](https://user-images.githubusercontent.com/56369938/174884776-7ed59b48-9bd8-4b13-80c6-798b2e546af3.png)
![image](https://user-images.githubusercontent.com/56369938/174884813-687c7c2a-74c5-4133-ad95-6a88e79f2661.png)

This mob seems to be invisible or under the ground?
He is attackable & spawns at the tree where iam, seems to be just invisible or missing a model.

**How to reproduce:**
Go to the location & aggro it.

**How it should work:**
Should be an actual mob, not an invisible ghost.
https://wowpedia.fandom.com/wiki/Cliff_Stormer

**Comment by Afgann** [comment]
fixed
