### ISSUE TITLE
[Quest] Evisceration - Sunstrider Isle

### ISSUE THREAD

**Issue by IHeckingLoveGithub** [SallyWhitemane/Maelstrom#276]
**Description:**
 Rogue class quest you get from trainer. You can't turn in the quest after completing it

**How to reproduce:**
 Get to level 3 as rogue, get the from rogue trainer, hit target dummies 3 times with your eviscerate, try to turn in the quest

**How it should work:**
 You should be able to turn it in to complete it

**Comment by ghost** [comment]
Works okay.
