### ISSUE TITLE
[Quest]  The Princess Unleashed

### ISSUE THREAD

**Issue by MrTide** [SallyWhitemane/Maelstrom#279]
**Description:** This quest is offered at arathi highlands 

**How to reproduce:** She wont move and wont attack you until you get close to her
and her summoned creatures won't attack you either they just do nothing 
![image](https://user-images.githubusercontent.com/36106057/174894327-67b40f06-8280-45ba-b0f1-830b13b69f3d.png)

**How it should work:** like the video below
https://www.youtube.com/watch?v=aI6vUWaR2kg

**Comment by ghost** [comment]
Fixed.
