### ISSUE TITLE
[Quest] Scouring the Desert

### ISSUE THREAD

**Issue by MrTide** [SallyWhitemane/Maelstrom#280]
**Description:**
This quest is offered in silithus

**How to reproduce:** quest is not fully scripted you go grab the silithyst but its not required for you to use the machine it just completes when you reach the camp

**How it should work:** Like the video below you need to go inside of a machine
https://www.youtube.com/watch?v=nI6VATVpN8Y

**Comment by Afgann** [comment]
fixed
