### ISSUE TITLE
[Quest] Adder Subtraction , Southern Barrens

### ISSUE THREAD

**Issue by Freemind0** [SallyWhitemane/Maelstrom#286]
**Description:**
This quest has a reacurring bug i've seen on a few quests, it allows you to spam the button & finnish the quest on 1 snake.
So it's allowing you to press multiple times to go from 1/5 to 5/5 on 1 snake.

**How to reproduce:**
Pick up quest around here 
![image](https://user-images.githubusercontent.com/56369938/175097383-87ee3110-4678-4e06-8543-7762fb54b837.png)

And spam click a snake.

**How it should work:**

Should just give 1/5 2/5 & so on per snake.

**Comment by Afgann** [comment]
fixed
