### ISSUE TITLE
[Quest] A line in the dirt, Southern  Barrens

### ISSUE THREAD

**Issue by Freemind0** [SallyWhitemane/Maelstrom#289]
**Description:**
It whispers "Defend the Hill!", while it should just give a yellow message of it.
It also does not give any message that you succeeded in defending the hill.
Far to few enemies & waves.
![image](https://user-images.githubusercontent.com/56369938/175104850-f8e42e47-f725-4410-93fc-380369904023.png)

There also seems to be alot fewer waves of enemies, i had a total of 6 enemies, 2 waves.

**How to reproduce:**
Pick up quest @vendetta point & click on the flag.

**How it should work:**

It should give a yellow announcement "Defend the hill!"
Then a "Success! the hill is yours!"

There should also be alot more enemies, atleast according to this video.

https://www.youtube.com/watch?v=zaFqVQjb2tk

**Comment by mserkanoz** [comment]
I just tried the quest. The yellow "Defend the Hill!" warning text appears but no mobs spawning.
