### ISSUE TITLE
[Event] New kargath event

### ISSUE THREAD

**Issue by MrTide** [SallyWhitemane/Maelstrom#291]
**Description:** this place can be found at west searing gorge

**How to reproduce:** Orcs and Darkflight flameblade are supposed to fight eachother but they just look at eachother
![image](https://user-images.githubusercontent.com/36106057/175120234-b307faf7-c008-492d-b6db-fa773a296d68.png)
![image](https://user-images.githubusercontent.com/36106057/175120205-13c992eb-a017-46d1-a46d-3c2bc26c4010.png)

**How it should work:** you can see in this video that they are fighting fast forward to 1:57
https://www.youtube.com/watch?v=rVbWdj9tEBw

**Comment by MrTide** [comment]
Hey @UltraNix these creatures are killing eachother way too fast it should be ongoing battle
basically any event in the world that players are not getting involved in killing the creatures that are fighting eachother they should basically be fighting eachother forever. this goes with my other similar reports as well
![image](https://user-images.githubusercontent.com/36106057/177391555-12810e1f-56aa-48df-b814-14a673fba136.png)

**Comment by ghost** [comment]
@MrTide It's not always the case. E.g. https://github.com/SallyWhitemane/Maelstrom/issues/484 The NPCs should kill each other, as you can see in many videos.
Just make a new report about this one particular.

**Comment by MrTide** [comment]
[UltraNix](https://github.com/UltraNix)Good point i was not talking about the spawns that attack the gate on 484 report random spawns like that come from no where should die yes  also those creatures in that report were stuck at 1 HP which players could abuse .. i believe these creatures here should be hurt but not damage eachother
i will upload an example shortly

**Comment by ghost** [comment]
@MrTide Just make a new report about this.

**Comment by MrTide** [comment]
sure thing but its not just this.. take a look at this video
basically any creature that spawn from nothing should die and anything that is fighting and have actual spawn should not die. thats why you can always see in videos related to quests that creatures are always there and you dont have to wait for respawn please keep this in mind for future fixes 

https://user-images.githubusercontent.com/36106057/177403265-272eb53f-5e45-42dd-9786-432a75e2f979.mp4

**Comment by ghost** [comment]
Because creatures related to quests/required for quests have short respawn timers.
Of course, there are plenty mobs that fight each other and don't die. But there are also mobs that fight and kills each other for real.

**Comment by ghost** [comment]
It's not a generic rule. So everytime you see that NPCs/mobs should not die, just report it

**Comment by MrTide** [comment]
> It's not a generic rule. So everytime you see that NPCs/mobs should not die, just report it

it would be almost impossible for anyone to make guides... you can always see creatures fighting each other around on guide videos.. even with less than 1min respawn timer it would not feel like a war happening around you.. its really up to you.. its actually is a rule but doesn't apply to creatures that spawn from no where.

**Comment by ghost** [comment]
No. Believe me - it's not rule. I've worked on many creatures and mobs from different expansions. They mostly implemented that on Cata, but they were not consistent - sometimes it's just a visual emote (e.g. wolves in Northshire), sometimes they should do only limited damage (from 30 to 75-80%) and sometims they just kill other NPCS.

**Comment by MrTide** [comment]
> No. Believe me - it's not rule. I've worked on many creatures and mobs from different expansions. They mostly implemented that on Cata, but they were not consistent - sometimes it's just a visual emote (e.g. wolves in Northshire), sometimes they should do only limited damage (from 30 to 75-80%) and sometimes they just kill other NPCS.

yes true its cata but don't you think those are bugged as well then ? either way it should be easy to figure out what creatures should be fighting forever or not .. its just a convenient way to fix it, letting these creatures kill eachother specially the 1v1 fights just makes no sense and just wastes player time and makes him to not enjoy the content we are trying to provide :). thanks eitherway

**Comment by ghost** [comment]
As I said - it's a not a generic rule so it's not "easy to figure out what creatures should be fighting forever or no".
The only way to fix it is just report every mob that should work like that.

**Comment by MrTide** [comment]
Fair enough i will try to report the similar issues again with more details
Thanks
