### ISSUE TITLE
[Quest] Survival of the Fattest

### ISSUE THREAD

**Issue by MrTide** [SallyWhitemane/Maelstrom#293]
**Description:** This quest is offered to the players at badlands 

**How to reproduce:** You go to the cave and to the place you are supposed to get the meat and try to click on the meat and nothing happens

**How it should work:** players should be able to loot them
like the video below
https://www.youtube.com/watch?v=qGBgx9yTujM

**Comment by ghost** [comment]
Works okay to me.

**Comment by MrTide** [comment]
hmm interesting.. i couldn't even click on them before and now they are working.. most likely something went wrong and server restart fixed most of them
some still got issues tho can't click on these 
![image](https://user-images.githubusercontent.com/36106057/176716991-454d7b3e-7e79-40ad-9b72-85c570453f99.png)

Thanks eitherway
