### ISSUE TITLE
[NPC] Worgen Sentry

### ISSUE THREAD

**Issue by MrTide** [SallyWhitemane/Maelstrom#297]
**Description:** These creatures can be found at silverpine forest at fenris isle

**How to reproduce:** there are multiple spawn of them inside eachother i would assume someone put two in one spot by mistake 
![image](https://user-images.githubusercontent.com/36106057/175141861-57834284-c986-47db-99bf-c6b4bbcb4af5.png)
![image](https://user-images.githubusercontent.com/36106057/175141886-03584d24-12aa-4d6d-b6ca-514baf20f066.png)
![image](https://user-images.githubusercontent.com/36106057/175141981-01282cd5-9d69-4025-bcab-7443690148a4.png)

**How it should work:** Extra spawns should be removed

**Comment by Afgann** [comment]
fixed
