### ISSUE TITLE
Mob's pets aggroing range and unable to die

### ISSUE THREAD

**Issue by lorenzo-ranciaffi** [SallyWhitemane/Maelstrom#30]
**Description:**
All the Razormane Hunter's pet (the wolves) in the Far Watch Post (Northern Barrens) will aggro you from an insane distance (something like 1000y) with no aggro reset. You can run till Orgrimmar and they would still chase you.
Their regen it's as if they were evading, so basically unkillable.
They also always run to your back, making really hard to cast a spell on them.

**How to reproduce:**
Just run around their camps and you will see the wolves running to you from the distance.

**How it should work:**
They should despawn if you kill the owner and sometimes that's possible, only if you can manage to aggro them. Otherwise they also are unkillable because of the regen.

**Comment by vadrigaar** [comment]
Here's a small demonstration:

https://www.youtube.com/watch?v=oopj69XikmQ
