### ISSUE TITLE
[Quest] Makha's plea, Southern Barrens

### ISSUE THREAD

**Issue by Freemind0** [SallyWhitemane/Maelstrom#305]
**Description:**
Quest just autocompletes.

**How to reproduce:**
Pick up quest from Mahka & it will autocomplete.

**How it should work:**
You should be required to talk to Mankrik & then return to Makha.

**Comment by MrTide** [comment]
More info here https://github.com/SallyWhitemane/Maelstrom/issues/499
there are minor events which also require attention there i will close this one for now unless you wanna take a look

**Comment by ghost** [comment]
@MrTide The event is scripted now.
