### ISSUE TITLE
[NPC] Tilly Torpin, Thousand Needles on Fizzle & pozziks boat.

### ISSUE THREAD

**Issue by Freemind0** [SallyWhitemane/Maelstrom#309]
**Description:**
She is friendly to Horde & allows you to use the flightpath from her.
But she should be red as all the other gnomes to Horde, but ofcourse not attackable.

**How to reproduce:**

**How it should work:**
She should be red & non attackable for Horde & not be able to be interacted with to use flightpath.

**Comment by ghost** [comment]
[Nope - seems to be friendly to Horde players.](https://www.wowhead.com/npc=40768)
