### ISSUE TITLE
Cast knockback pierces through Power Word: Shield

### ISSUE THREAD

**Issue by lorenzo-ranciaffi** [SallyWhitemane/Maelstrom#31]
**Description:**
If you cast a Power Word: Shield on yourself and start casting while a mob is hitting you, it will produce the knockback effect, increasing your cast time.

**How to reproduce:**
As said in the description.

**How it should work:**
As long as your bubble is up, you should experience no knockback

**Comment by ghost** [comment]
Fixed.
