### ISSUE TITLE
[Quest] Bar fight! 

### ISSUE THREAD

**Issue by Freemind0** [SallyWhitemane/Maelstrom#310]
**Description:**
As Horde, if you smash a Gnome with the grog (tried abandoning & picking it up, choosing another Gnome, same thing), the bar do not go into a fight. They all just stand around.

Previous closed ticket 
[Quest] Bar Fight! id=25518 (animations) #110
Don't know if this guy was an alliance maybe?
And still bugged on horde side. 

**How to reproduce:**
Pick up quest, buy Grog & smash a Gnome.
I picked these 2 male gnomes 
![image](https://user-images.githubusercontent.com/56369938/175372536-cb263e87-c4e4-4192-832c-fb70fea6eab4.png)

**How it should work:**
After you smash Gnome as Horde or Goblin as Alliance, the bar fight should begin as on this video.
https://www.youtube.com/watch?v=pzF-vFNKPAA

**Comment by MrTide** [comment]
Already reported twice i believe i think its fixed as well not live yet
you can close this 
https://github.com/SallyWhitemane/Maelstrom/issues?q=Bar+fight%21+
