### ISSUE TITLE
[NPC] Brienna Starglow, Thousand Needles 

### ISSUE THREAD

**Issue by Freemind0** [SallyWhitemane/Maelstrom#319]
**Description:**
She is fighting 3 other npcs, Bor'Zehn, Nag'Zhen & Rau Cliffrunner, right where you do the "Grimtotem in the post" quest.
They should not be fighting, but fighting with eachother against the Grimtotem, they should be allied. 
![image](https://user-images.githubusercontent.com/56369938/175395267-512e4159-1aa4-4569-b672-65ad45ca5e47.png)

**How to reproduce:**

**How it should work:**
Should not be fighting. 
Brienna is a quest npc for the alliance.

https://www.youtube.com/watch?v=LNfEHXfRhmI

**Comment by Afgann** [comment]
fixed
