### ISSUE TITLE
"You Can't Take 'Em Alone" Quest Bugged

### ISSUE THREAD

**Issue by SpicyMarinara** [SallyWhitemane/Maelstrom#32]
**Description:**
This is a quest in the Worgens' starting zone - Duskhaven. The player is supposed to gather 4 Black Gunpowder Kegs (items) to blow up 4 Horrid Abominations (enemies) which are wandering around. The issue is - those Horrid Abominations are untargetable and there is no way to use any items on them or to even attack them at all.

**How to reproduce:**
Accepting the quest when doing the Worgens' starting zone.

**How it should work:**
The player should be able to cast gathered Black Gunpowder Kegs from their inventory on the Horrid Abominations, which should cause them to die.

This quest is required to progress through the entire Worgen starting scenario.

**Comment by F1r3m4st3r** [comment]
please make them targetable
