### ISSUE TITLE
[NPC] Rundok Orgrimmar

### ISSUE THREAD

**Issue by Freemind0** [SallyWhitemane/Maelstrom#323]
**Description:**
He should not be wandering around & walking through the portal to Outland.
He even walks into the wall.

![image](https://user-images.githubusercontent.com/56369938/175400658-c075cb9d-9d60-424b-bc83-e66874b9b0dc.png)

**How to reproduce:**

**How it should work:**
He should just stand next to it.

**Comment by Afgann** [comment]
fixed
