### ISSUE TITLE
[NPC] Skitterweb Matriarch

### ISSUE THREAD

**Issue by MrTide** [SallyWhitemane/Maelstrom#324]
**Description:**

**How to reproduce:** She is not on the ceiling 
![image](https://user-images.githubusercontent.com/36106057/175405640-c2c917e5-ab4d-4593-9a51-26b4e91570f5.png)

**How it should work:**
Correct animation is shown in this video https://www.youtube.com/watch?v=neOikNxWwk8
https://www.wowhead.com/npc=44906/skitterweb-matriarch#comments
![image](https://user-images.githubusercontent.com/36106057/175405864-23d721f2-08c7-4bf6-98e7-2fecfb039fa7.png)

**Comment by ghost** [comment]
Works okay.
