### ISSUE TITLE
[Quest] A blight upon

### ISSUE THREAD

**Issue by MrTide** [SallyWhitemane/Maelstrom#329]
**Description:**
this quest is offered to the players at hillsbrad zone

**How to reproduce:** Quest is working there are some minor animation issues which can be improved but the problems is that npcs still follow you after finishing the quest
![image](https://user-images.githubusercontent.com/36106057/175424901-4ff52c58-5204-408b-8599-582d0f6795c2.png)
![image](https://user-images.githubusercontent.com/36106057/175424991-26948a96-cc11-407a-996f-c99c656c14a3.png)

**How it should work:** they should despawn after finishing the quest
https://www.youtube.com/watch?v=s5nVLPh9ovk

**Comment by ghost** [comment]
But in this video I don't see any despawn. That NPC offers next quest, so there there is no way of despawning him @MrTide

**Comment by MrTide** [comment]
> But in this video I don't see any despawn. That NPC offers next quest, so there there is no way of despawning him @MrTide

Here you can see them despawn/phase out after taking the head https://youtu.be/s5nVLPh9ovk?t=143 they become perm npcs afterwards

**Comment by ghost** [comment]
You are right.

**Comment by ghost** [comment]
Works okay to me - after killing the monster NPCs despawned.

**Comment by MrTide** [comment]
> Works okay to me - after killing the monster NPCs despawned.

I don't know if you applied any updates to this but they dont even move anymore
![image](https://user-images.githubusercontent.com/36106057/178497749-a07bd824-13fc-4fcb-99ed-e2ba859428e8.png)
![image](https://user-images.githubusercontent.com/36106057/178497808-a9581e59-913a-4b5b-aa38-786452baf919.png)
also after you turn in the quest they show up again @UltraNix 
so its not fixed at all just tested it a few min ago
![image](https://user-images.githubusercontent.com/36106057/178498432-6d6ed2c2-7d48-49d7-a4b4-0ee7789f4c36.png)

**Comment by ghost** [comment]
I did not say it's fixed, I said it works fine on my local. Just tested that too on my server.

**Comment by MrTide** [comment]
> I did not say it's fixed, I said it works fine on my local. Just tested that too on my server.

I am confused, so are we doing anything about this issue because you closed it :\ and said "works okay" while its not

**Comment by ghost** [comment]
Tested again and confirmed - NPCs appeared again on quest rewarded.

**Comment by MrTide** [comment]
npcs that are supposed to get killed dont move as well for some reason anymore .. test it with a caster ... (the two main ones tho)
thanks

**Comment by ghost** [comment]
Tested and they move normally. Just not follwing players because fighting with Warden.

**Comment by MrTide** [comment]
i mean i had the agrro but they didnt come to me which is weird. at start they didnt even fight with eachother
https://user-images.githubusercontent.com/36106057/178497749-a07bd824-13fc-4fcb-99ed-e2ba859428e8.png

**Comment by ghost** [comment]
Just try again. For me it works okay every time.

**Comment by ghost** [comment]
Also, they should be "blue" not "green". Have you summoned them vis command?

**Comment by MrTide** [comment]
no they just respawn themselves everytime i come back here this time he was alone and low and was just looking at me
![image](https://user-images.githubusercontent.com/36106057/178511553-cc2df3c8-0f91-4ebc-a02a-caed1a27ebe2.png)
![image](https://user-images.githubusercontent.com/36106057/178511651-a08ba5d5-0b79-413a-95a1-695f316ca5ff.png)

**Comment by ghost** [comment]
It's weird that they are not blue, so it means that they are not your guardians.

**Comment by MrTide** [comment]
the thing is the guards dont even show up anymore probably it requires a server restart to fully reset

**Comment by ghost** [comment]
Kill them all (alle NPCS/mobs around), `.quest remove 28237`, respawn the Warden mob, move a couple yards away and relog. Then `.quest add 28237` and see what happens.

**Comment by MrTide** [comment]
thats what i do everytime
still the same no guards around
![image](https://user-images.githubusercontent.com/36106057/178514334-736f0352-9aaf-4b2d-b88f-1c69b8c38d30.png)

**Comment by MrTide** [comment]
also after a player doing the event flesh shaper arnauld is hostiles... when you do this event for first time he is not hostile 
![image](https://user-images.githubusercontent.com/36106057/178518859-1d7a21e8-febf-4914-8fa2-51b4408772c5.png)
![image](https://user-images.githubusercontent.com/36106057/178518960-08a77dd8-b146-4257-93fd-1ea7cbaa0a73.png)
