### ISSUE TITLE
[NPC] Megs Dreadshredder, Tanaris Lost Rigger Cove

### ISSUE THREAD

**Issue by Freemind0** [SallyWhitemane/Maelstrom#337]
**Description:**
She stands on the wrong side.

**How to reproduce:**
Just go to her at lost rigger cove.

**How it should work:**
She should be standing next to the bruisers on the right side, not with the gnome on the left side.
![image](https://user-images.githubusercontent.com/56369938/175572377-0797c879-88e6-4400-922d-809c9e804ef8.png)

**Comment by Afgann** [comment]
fixed
