### ISSUE TITLE
[NPCS][Zone] Lost Rigger Cove in Tanaris

### ISSUE THREAD

**Issue by Freemind0** [SallyWhitemane/Maelstrom#338]
**Description:**
Theres multiple npcs so i figured i would title it like this.
So essentially there should be Bilgewater Battlebruisers & Covert Ops Hardsuits battling the Southsea pirates.
But as i can see on videos, no npcs should actually take dmg.
So they should all be alive, right now, they're killing all the pirates.

Looking at this video it looks very different & no pirates actually dies to the npcs.
And im not entirely sure the Covert Ops Hardsuits should be enemies & attackable by the horde or even aggroed to the horde.
Vice viersa for bilgewater to the alliance.
https://www.youtube.com/watch?v=XhBZFxoFsR4

![image](https://user-images.githubusercontent.com/56369938/175572675-79dae4e0-e3b8-411c-9822-6c95f5a61151.png)

**Comment by ghost** [comment]
Already fixed.
