### ISSUE TITLE
[Quest] Just trying to kill some bugs, Tanaris

### ISSUE THREAD

**Issue by Freemind0** [SallyWhitemane/Maelstrom#341]
**Description:**
The ability "Sense Pheromones" should spawn a orange line pointing you in the right direction.
The ability "Detonate Silithid" does not work, it gives you an error message that you're in the wrong place, but even watching a guide it still says im in the wrong place.
And it's kinda impossible to know when the ability does not work to show me where. I've tried multiple other places, but all are wrong.

![image](https://user-images.githubusercontent.com/56369938/175586662-aef42637-9d4e-4491-a13f-dee1de9e42a4.png)

Theres also missing bombs/dynamites on top of the mind-controlled swarmer. 

**How to reproduce:**
 Pick up quest & try to use the abilities.
Go to the correct spot & try to use the detonate ability.

**How it should work:**

Should be bombs/dynamites on the mind controlled swarmer, the sense pheromones should spawn orange lines leading you in the right direction. 
And using the detonate ability should blow the place up & then take you back to the quest npc immediatly, as your body should still be back there as you're just controlling this swarmer.

Video: https://www.youtube.com/watch?v=VEPggamuKT0

**Comment by Freemind0** [comment]
Also funny, if you simply leave, by using the "leave vehicle" button, it still allows you to keep the buff to make you friendly with all the swarmer mobs. And it kicks you out where the swarmer was, it does not take you back to the quest npc as it should.

Buff name: "Mind-Controlled Swarmer."

**Comment by MrTide** [comment]
Can confirm. all of it
![image](https://user-images.githubusercontent.com/36106057/177199645-f136ed15-8851-4572-a029-e1a7d6ebd8a5.png)
