### ISSUE TITLE
[NPC] Research Intern

### ISSUE THREAD

**Issue by MrTide** [SallyWhitemane/Maelstrom#347]
**Description:** These creatures can be found in azshara also related to quest  "When Science Attacks"

**How to reproduce:** They are on fire and supposed to be running around because of that but here they just walk around 
![image](https://user-images.githubusercontent.com/36106057/175610843-ad702b0b-2c85-43fc-97ad-db4ebce32c5d.png)
![image](https://user-images.githubusercontent.com/36106057/175610824-0fc9ec46-4c1c-4e6c-9dbf-e2531a8225b9.png)

**How it should work:** in this video you can see them running around
https://www.youtube.com/watch?v=twN18L7SLF0

**Comment by Afgann** [comment]
fixed
