### ISSUE TITLE
[Quest] Secrets in the oasis, Tanaris

### ISSUE THREAD

**Issue by Freemind0** [SallyWhitemane/Maelstrom#349]
**Description:**
The event of this quest is not played out properly.
Mazoga does not fight at all. He should be running up to the spot where you stand, then combine his 2 weapons in to a 2handed, then fight you until hes low hp, then say a line & be unattackable, as he then vanishes.

But right now he just stands there, with both weapons still, does not attack, the dialogue doesn't show up properly, then he just vanishes.

**How to reproduce:**
Go to quest location & click on the quest objective, then watch the small event & fight Mazoga.

**How it should work:**

Event should play out properly & Mazoga should be fighting with the weapon reformed into a 2handed. 

https://www.youtube.com/watch?v=eIWPKMRYYCg

**Comment by MrTide** [comment]
Hey, can confirm its not working properly
