### ISSUE TITLE
[Object] Power Crystal Un'Goro Crater

### ISSUE THREAD

**Issue by Freemind0** [SallyWhitemane/Maelstrom#350]
**Description:**
Power Crystals have very odd spawns, where they many times spawn on top of eachother.
There should be max 1 on a spot & way more spread out than this.

![image](https://user-images.githubusercontent.com/56369938/175613802-1f23052e-334e-4277-a177-19b5fcd2cf36.png)

**Comment by Freemind0** [comment]
![image](https://user-images.githubusercontent.com/56369938/175614113-2c67c4bc-58b1-4239-8095-4747f0e62da3.png)

**Comment by Afgann** [comment]
fixed
