### ISSUE TITLE
[Quest] Finding the source, Un'Goro Crater

### ISSUE THREAD

**Issue by Freemind0** [SallyWhitemane/Maelstrom#352]
**Description:**
Cannot complete it, as non of the spots completes the quest. Following videos, the supposed correct spot is not working.
![image](https://user-images.githubusercontent.com/56369938/175618215-55a70eaf-51d0-4a91-b992-4843284941a0.png)

**How to reproduce:**
Pickup quest & try the item on the hotspots.

**How it should work:**

It's a bit vague which is the correct spot, but going from this video
https://www.youtube.com/watch?v=wsfihvhW480

It should be on the northwest side, almost straight north.

**Comment by Afgann** [comment]
fixed
