### ISSUE TITLE
[Quest][NPC] Full of Hot Water and Scalding water lord

### ISSUE THREAD

**Issue by MrTide** [SallyWhitemane/Maelstrom#353]
**Description:** this npc and quest can be found in azshara

**How to reproduce:** NPC got wrong HP value it should be higher 
![image](https://user-images.githubusercontent.com/36106057/175619254-dd487f4b-cced-4b22-a12f-e2f9a17789d5.png)

**How it should work:** https://cata-twinhead.twinstar.cz/?npc=36130 
https://www.youtube.com/watch?v=NUUomvkBKo4

**Comment by Afgann** [comment]
fixed
