### ISSUE TITLE
[Quest][Npc] Wash Out

### ISSUE THREAD

**Issue by MrTide** [SallyWhitemane/Maelstrom#354]
**Description:**
This quest can be found in azshara

**How to reproduce:** He is going slow and hovering over water from time to time
![image](https://user-images.githubusercontent.com/36106057/175631444-f219a628-c24e-4c00-9164-9f5550cca8bf.png)

**How it should work:** it is supposed to move faster and don't hover over water
https://www.youtube.com/watch?v=KkhFkrQssUE

**Comment by Afgann** [comment]
fixed
