### ISSUE TITLE
[Quest] The mighty u'cha, Un'goro crater

### ISSUE THREAD

**Issue by Freemind0** [SallyWhitemane/Maelstrom#359]
**Description:**
U'Cha is in the wrong spot. 
![image](https://user-images.githubusercontent.com/56369938/175651947-7f69ae2b-fe15-4a16-9af1-f9feb8d8ee4b.png)

**How to reproduce:**
Enter the north east gorilla cave.

**How it should work:**
On my screenshot U'Cha should be up to the left above where he is, then a bit farther into where there is a rock around a small patch of water. 
Fairly certain they never moved U'cha to here from Classic to Cataclysm.
Unfortunately no videos for this one.
But a screenshot from Twinstars Cataclysm wiki.
![image](https://user-images.githubusercontent.com/56369938/175652650-bd211f27-ca61-4071-8553-5b42c7dac487.png)

**Comment by Afgann** [comment]
fixed
