### ISSUE TITLE
[Quest] [NPC] Trouble under foot

### ISSUE THREAD

**Issue by MrTide** [SallyWhitemane/Maelstrom#360]
**Description:**
This quest is offered to the players at azshara

**How to reproduce:** NPC don't despawn after finishing the quest also teleporter is missing from your pet
![image](https://user-images.githubusercontent.com/36106057/175655642-48def8bf-f9cb-421c-9612-74340bb70dc1.png)
![image](https://user-images.githubusercontent.com/36106057/175656001-244596b2-c00a-4c1b-aef5-4826d2e984be.png)

**How it should work:** it should despawn also give you the option to teleport back.
NPC name is : Personal arcane assistant 
![image](https://user-images.githubusercontent.com/36106057/175656104-b030beaa-3450-4b07-8d4f-2ae36fe4d980.png)

https://www.youtube.com/watch?v=pys_g12OMg4
https://www.wowhead.com/quest=14226/trouble-under-foot#comments:id=1182910

**Comment by Afgann** [comment]
fixed
