### ISSUE TITLE
[Item] Faded Wizard Hat

### ISSUE THREAD

**Issue by MrTide** [SallyWhitemane/Maelstrom#376]
**Description:** This item is offered to you after finishing quest called [Farewell, Minnow](https://cata-twinhead.twinstar.cz/?quest=14392)

**How to reproduce:** Item doesn't work it wont change your race 

**How it should work:** Like the video below 
https://www.youtube.com/watch?v=nP27pHBYxeQ
https://wowpedia.fandom.com/wiki/Faded_Wizard_Hat
The Faded Wizard Hat transforms you into one of [Archmage Xylem](https://wowpedia.fandom.com/wiki/Archmage_Xylem)'s [apprentices](https://wowpedia.fandom.com/wiki/Archmage_Xylem#Apprentices), picked at random. NPCs will react to the gender change, if it happens.

The form lasts for thirty minutes, as does the hat's cooldown. The hat's relative ease to acquire, coupled with its long transformation duration and relatively short cooldown, have made it a popular [vanity](https://wowpedia.fandom.com/wiki/Vanity) item among higher level [Horde](https://wowpedia.fandom.com/wiki/Horde) players.

**Comment by Afgann** [comment]
fixed
