### ISSUE TITLE
[Major Issue] [NPCS] Casters around the world

### ISSUE THREAD

**Issue by MrTide** [SallyWhitemane/Maelstrom#379]
**Description:** these creatures can be found all around the world

**How to reproduce:** Looks like there is a big delay between casters all over the world
they look at you for long while then start to cast and after finishing their cast there is a big gap until they cast again it should not be like that
take a look at these three examples 
https://streamable.com/f3o9g1
https://streamable.com/1us8ig
https://streamable.com/1tmqwv
some physical ranged creatures are like this as well like the ones that use bow

**How it should work:** There should be no hesitation they should be casting and keep casting until their mana is gone then run and attack you
an example of how they are supposed to work
https://www.youtube.com/watch?v=MLQl5Du-z_0

**Comment by Afgann** [comment]
Fixed those three examples. All cases need to be fixed individually, so i can't fix all of them at once.

**Comment by MrTide** [comment]
> 

can we atleast keep this open ? because by the look of it.. its the every creature in the world it must be a core function this is a major issue we can't just by pass it

**Comment by Afgann** [comment]
It's just a script written badly, if it was one core function then i would fix it that way.
