### ISSUE TITLE
[Quest] [Item]  It's Time to Oil Up / Darla's Grapple

### ISSUE THREAD

**Issue by MrTide** [SallyWhitemane/Maelstrom#382]
**Description:** This quest is offered to the players at felwood 

**How to reproduce:** Darla's Grapple can be used anywhere in area players need to use it on Oil Balloon

**How it should work:** Like the video below it should be used on oil balloons 
https://www.youtube.com/watch?v=c3eRPir1u7g

**Comment by Afgann** [comment]
fixed
