### ISSUE TITLE
[NPC] Donald Emery

### ISSUE THREAD

**Issue by MrTide** [SallyWhitemane/Maelstrom#383]
**Description:** This npc can be found at western plaguelands 

**How to reproduce:** He is supposed to sell supplies but its not possible to talk to him
![image](https://user-images.githubusercontent.com/36106057/175981404-3a6e1660-ac4d-4a59-80a2-335eb67b4ccf.png)

**How it should work:** players should be able to trade/buy/repair and sell items to it
https://cata-twinhead.twinstar.cz/?npc=47864

**Comment by Afgann** [comment]
fixed
