### ISSUE TITLE
[Quest]  Scholomancer

### ISSUE THREAD

**Issue by MrTide** [SallyWhitemane/Maelstrom#385]
**Description:** This quest is offered to the players at western plaguelands 

**How to reproduce:** Event is not scripted properly they kill you as well in the process also there are missing animations there are multiple spawns of the same creatures and so on 
![image](https://user-images.githubusercontent.com/36106057/175987632-006d494d-c7d5-4455-acec-1bb02e0869a2.png)

**How it should work:** an example ... i would assume its same for both horde and alliance side of the quest
https://www.youtube.com/watch?v=HqIm6XDdK-Q

**Comment by ghost** [comment]
Already fixed.
