### ISSUE TITLE
[NPC] Northridge Spider, Rabid Fox, Whitetail fox

### ISSUE THREAD

**Issue by MrTide** [SallyWhitemane/Maelstrom#396]
**Description:** these creatures can be found at western plaguelands

**How to reproduce:** Northridge Spider, Rabid Fox, Whitetail fox are missing movements and standing still they should have basic movements

**How it should work:** you can see them moving in the videos below
Spiders
https://www.youtube.com/watch?v=8JmAugkRhzs
Rabid fox
https://www.youtube.com/watch?v=NCBNefBQ_YA
whitetail fox
https://www.youtube.com/watch?v=D7rAeghxsHk

**Comment by Afgann** [comment]
fixed
