### ISSUE TITLE
[NPC] Redpine looter and redpine necromancer

### ISSUE THREAD

**Issue by MrTide** [SallyWhitemane/Maelstrom#398]
**Description:** These creatures can be found at western plaguelands

**How to reproduce:** They are missing basic movements 
![image](https://user-images.githubusercontent.com/36106057/176253077-e62f8aab-1947-4206-b32b-05d39c215acf.png)
![image](https://user-images.githubusercontent.com/36106057/176253157-54ae5414-364b-4e64-805a-d560c897baca.png)

**How it should work:** you can see these creatures moving in these videos
https://www.youtube.com/watch?v=IfB0y4cDezs
https://www.youtube.com/watch?v=c2MjrFg1oAc

**Comment by Afgann** [comment]
fixed
