### ISSUE TITLE
Wanted james clark

### ISSUE THREAD

**Issue by romaric-roussel** [SallyWhitemane/Maelstrom#4]
**Description: cannot drop his head

**How to reproduce: priest class, kill james clark

**How it should work: drop his head

**Comment by phonkala** [comment]
Can confirm, seems to be problem with many neutral mobs. Opened more generic issue of that:
https://github.com/SallyWhitemane/Maelstrom/issues/21

**Comment by UltraNix** [comment]
Just tested it - works okay.
