### ISSUE TITLE
[Generic] Big issues with stealth

### ISSUE THREAD

**Issue by phonkala** [SallyWhitemane/Maelstrom#40]
**Description:**
Currently a lot of stuff gets bugged when you start from stealth. This makes at least druids and rogues suffer a lot as that part of the classes is just unplayable, probably other classes with temporary stealth suffer from it too.

1) Autoattacks from stealth seem to ALWAYS make the target bugged. Already reported this with
https://github.com/SallyWhitemane/Maelstrom/issues/29
There was also another report I assume from same issue
https://github.com/SallyWhitemane/Maelstrom/issues/7

When the target mob gets bugged, you also enter combat and you can never leave it unless you have some vanish-style ability.

2) Inside dungeon, when the target gets bugged via the method described above, even shadowmeld does not seem reset the mob. Shadowmeld does work in open world. Noticed this when fighting Foe Reaper 5000 in Deadmines, if you get it bugged there is no way to pass it besides reset whole dungeon. Tested also again on the first boss, and a random elite mob too. Also, if you just log out inside the dungeon while being targeted by bugged mob, once you login you are dead/ghost.

3) Stealthing "through" mobs makes them attack you once, but they do no damage so stealth never breaks and the mob immediately resets. Basicly you can stealth through anything. I was testing this inside dungeon so dunno if this happen in open world too.

**Comment by phonkala** [comment]
Checked the 3. (stealthing through mobs) bit more. This does not always happen, but does happen in open world too. However, bit more info about it:

When the mob that sees me through stealth and hits me and the hit is missed/dodged etc, then the mob resets right away and stealth is not broken. If it hits successfully, it does break stealth and the mob keeps attacking.

**Comment by phonkala** [comment]
Also a note to 2: Tried again logging out (alt+f4) while in combat with bugged mob (deadmines first boss), this time when logging back in I was not dead and combat was reseted. However, with Foe Reaper again, logging out while it is bugged and logging back in makes u enter back in as ghost.

**Comment by ghost** [comment]
@phonkala 
`
When the mob that sees me through stealth and hits me and the hit is missed/dodged etc, then the mob resets right away and stealth is not broken. If it hits successfully, it does break stealth and the mob keeps attacking.
`
And what is the blizzlike behaviour? Stealth should be removed even on miss/dodge?

**Comment by phonkala** [comment]
I don't believe stealth should be removed when hit doesn't actually hit, but the mob that hit you should keep hitting you if I remember correctly. Currently the mob resets pretty much instantly and "forgets you were ever there" :) Couldn't find any videos quickly of the blizzlike behaviour in Cata though, probably need to find one to see how it actually was then.

This can be tested easily for example in any low level dungeon (where the level difference between you and the mobs is huge). One can basicly run through dungeon in stealth, running through mobs, as mostly they target you, _miss_, and instantly reset.

**Comment by ghost** [comment]
Okay.
