### ISSUE TITLE
[Quest][NPC]  Postponing the Inevitable

### ISSUE THREAD

**Issue by MrTide** [SallyWhitemane/Maelstrom#400]
**Description:** This quest is offered to the players in eastern plaguelands

**How to reproduce:** There are animation issues Plague disseminator are supposed to fall down and explode when you use  Overcharged Mote

**How it should work:** like the video below
https://www.youtube.com/watch?v=8zNEAh2xRmA

**Comment by Afgann** [comment]
fixed
