### ISSUE TITLE
[NPC] blighthound,  landlocked grouper

### ISSUE THREAD

**Issue by MrTide** [SallyWhitemane/Maelstrom#401]
**Description:**These creatures can be found in eastern plaguelands

**How to reproduce:** they are missing basic movements they dont move at all
![image](https://user-images.githubusercontent.com/36106057/176267767-f6aeda42-0e0f-4276-becd-56c5f3ef1950.png)
![image](https://user-images.githubusercontent.com/36106057/176272584-d1c20b8e-91ce-4ec1-90ae-300c46ab14bf.png)

**How it should work:** you can see them in this video moving
https://www.youtube.com/watch?v=nsMXoKaSG2c
and the fishes 
https://www.youtube.com/watch?v=YxomvLKVOk4

**Comment by Afgann** [comment]
fixed
