### ISSUE TITLE
[Quest] Catalysm

### ISSUE THREAD

**Issue by MrTide** [SallyWhitemane/Maelstrom#402]
**Description:** this quest can be found at eastern plaguelands

**How to reproduce:** you are supposed to use Betina's flasks on elementals only once but you can spam it on one of them to finish the quest

**How it should work:** you can find more info here
please keep in mind it should not cause issues for other players trying to do the same quest 
https://www.youtube.com/watch?v=_VxyAORDtaU

**Comment by Afgann** [comment]
fixed
