### ISSUE TITLE
[Quest] Duskwing, Oh How I Hate Thee...

### ISSUE THREAD

**Issue by MrTide** [SallyWhitemane/Maelstrom#409]
**Description:** this quest can be found at eastern plaguelands

**How to reproduce:** he is supposed to brought down with a flare while he is sitting there since begining 
![image](https://user-images.githubusercontent.com/36106057/176289155-ac9f3354-6d45-40f7-b23a-2081e045bc7b.png)

**How it should work:**
https://www.youtube.com/watch?v=KrIzKc-1YEs

**Comment by Afgann** [comment]
fixed
