### ISSUE TITLE
[NPC] Augustus the Touched

### ISSUE THREAD

**Issue by MrTide** [SallyWhitemane/Maelstrom#412]
**Description:** THIS NPC can be found at eastern plaguelands

**How to reproduce:** he is not selling anything also the bag he is selling is not working as intended you get an error that slot is empty also i believe this bag is a limited offer so players can just buy one until it refreshes again https://wowpedia.fandom.com/wiki/Augustus_the_Touched
also based on this comment you need to finish his quest to access his goods which i did... check the note on this link https://wowpedia.fandom.com/wiki/Augustus%27_Receipt_Book_(quest)
![image](https://user-images.githubusercontent.com/36106057/176305841-dad64bc0-b02b-42af-a8d5-b958d59faa85.png)
![image](https://user-images.githubusercontent.com/36106057/176305116-a0219d08-e387-484d-b864-bf4040ac3ad2.png)

**How it should work:** 
https://cata-twinhead.twinstar.cz/?item=15902
https://cata-twinhead.twinstar.cz/?npc=12384#sells

**Comment by Afgann** [comment]
fixed
