### ISSUE TITLE
Goblin rogue stealth interface problem

### ISSUE THREAD

**Issue by Noisefr3ak** [SallyWhitemane/Maelstrom#415]
**Description:**
When stealth there is not the stantar bar  / The problem is only at the starting area of goblins. When you leave Kezan interface work fine. Maybe the problem is with the Hot rod key that you have at Kezan

**How to reproduce:**

**How it should work:**
Like all other rogue races
![stealth bug](https://user-images.githubusercontent.com/108414976/176461730-9836ebaf-da9b-4938-a441-a053c99c7c67.png)

**Comment by ghost** [comment]
@Noisefr3ak Cannot reproduce it.
