### ISSUE TITLE
[Quests] Missing requirements on Neeka Bloodscar quests

### ISSUE THREAD

**Issue by MrTide** [SallyWhitemane/Maelstrom#417]
**Description:** This npc can be found at swamp of sorrows

**How to reproduce:** quests are missing requirements
![image](https://user-images.githubusercontent.com/36106057/176471459-1c1d4fc8-6d61-49c3-bbf2-0eca3e304602.png)

[The Purespring](https://cata-twinhead.twinstar.cz/?quest=27909) requires [Prayerblossom](https://cata-twinhead.twinstar.cz/?quest=27907), "Prayerblossom" Opens [With Dying Breath](https://cata-twinhead.twinstar.cz/?quest=27911) and "With Dying Breath" opens [With Dying Breath](https://cata-twinhead.twinstar.cz/?quest=27911) series 

------------

[Secrets of the Mire](https://cata-twinhead.twinstar.cz/?quest=27908) Opens up [Last Regrets](https://cata-twinhead.twinstar.cz/?quest=27910)

**How it should work:** They all should follow the requirements

**Comment by Afgann** [comment]
fixed
