### ISSUE TITLE
[NPC] Purespring Elemental, Misty Grell, Shifting Mireglob, Sorrow Screecher, Sorrow venomspitter, Sorrow spinner

### ISSUE THREAD

**Issue by MrTide** [SallyWhitemane/Maelstrom#418]
**Description:** These creatures can be found at swamp of sorrows 

**How to reproduce:** They are missing basic movements they just stand in one place and wont move at all
![image](https://user-images.githubusercontent.com/36106057/176473679-f0445471-b0f8-4279-b37b-00c1048644d8.png)
![image](https://user-images.githubusercontent.com/36106057/176474955-a69cdef8-0c08-4b43-8303-5e755af793be.png)

**How it should work:** as you can see in this video they have basic movements
https://www.youtube.com/watch?v=02T35n1OSrk
https://www.youtube.com/watch?v=jmClj7rrLVM
https://www.youtube.com/watch?v=d00UGUiHEAg
for the "Sorrow Screecher, Sorrow venomspitter, Sorrow spinner"
https://www.youtube.com/watch?v=POjxn9lsU-U

**Comment by Afgann** [comment]
fixed
