### ISSUE TITLE
[Quests][NPC] Missing quest requirements on dispatch commander Ruag

### ISSUE THREAD

**Issue by MrTide** [SallyWhitemane/Maelstrom#419]
**Description:** This npc can be found at swamp of sorrows

**How to reproduce:**
He is simply missing quest requirements and offering all at once i would assume its the same for alliance side.
![image](https://user-images.githubusercontent.com/36106057/176477384-c622aaea-11ad-4f9d-8e56-c7cca43cda88.png)
You need to do [Orcs and Humans](https://cata-twinhead.twinstar.cz/?quest=27852) for [Tides of Darkness](https://cata-twinhead.twinstar.cz/?quest=27854) , [Reinforcements Denied](https://cata-twinhead.twinstar.cz/?quest=27855) and [Marking the Fallen](https://cata-twinhead.twinstar.cz/?quest=27856)

------------
You need to do [Tides of Darkness](https://cata-twinhead.twinstar.cz/?quest=27854) for [We're Under Attack!](https://cata-twinhead.twinstar.cz/?quest=27857)
and you need to do [We're Under Attack!](https://cata-twinhead.twinstar.cz/?quest=27857) and [Tides of Darkness](https://cata-twinhead.twinstar.cz/?quest=27854) to open up [Neeka Bloodscar](https://cata-twinhead.twinstar.cz/?quest=27906)

**How it should work:** They should follow the requirements listed above.

**Comment by Afgann** [comment]
fixed
