### ISSUE TITLE
[Quest][Npc] Missing quest and requirement "Maliciously Delicious"

### ISSUE THREAD

**Issue by MrTide** [SallyWhitemane/Maelstrom#423]
**Description:** This npc and quest can be found at swamp of sorrows 

**How to reproduce:** NPC Trade baron silversnap simply is not offering the quest but the quest afterwards is open
[Maliciously Delicious](https://cata-twinhead.twinstar.cz/?quest=27587) should be available and then after doing this, [Mostly Harmless](https://cata-twinhead.twinstar.cz/?quest=27536) and [Croc-Out](https://cata-twinhead.twinstar.cz/?quest=27656) and  [Tastes Like Strider](https://cata-twinhead.twinstar.cz/?quest=27663) becomes available
![image](https://user-images.githubusercontent.com/36106057/176485188-c4d6760d-3c45-4e9e-b73a-355782172d96.png)

also  Silversnap Swim Tonic which is supposed to be offered by Maliciously Delicious quest as well is not working 

**How it should work:** more info in this video about the quest
https://www.youtube.com/watch?v=Ycf3VPWK1Bk

**Comment by Afgann** [comment]
fixed
