### ISSUE TITLE
[NPC] Swampshore Makrura, Sawtooth Crocolisk, Swampstrider

### ISSUE THREAD

**Issue by MrTide** [SallyWhitemane/Maelstrom#424]
**Description:** these creatures can be found at swamp of sorrows

**How to reproduce:** These creatures are missing basic movements they dont move at all
![image](https://user-images.githubusercontent.com/36106057/176487695-534c1862-a244-44c4-a517-2fbf4e437e89.png)
![image](https://user-images.githubusercontent.com/36106057/176487715-edd8e832-e7ab-463c-8bb7-f50e00e952b0.png)
![image](https://user-images.githubusercontent.com/36106057/176487803-5a142e83-3049-4df4-9403-3d47f979db49.png)

**How it should work:** you can see these creatures moving in the videos below
https://www.youtube.com/watch?v=Ycf3VPWK1Bk
https://www.youtube.com/watch?v=2U01rqca0Pw

**Comment by Afgann** [comment]
fixed
