### ISSUE TITLE
[NPC][Quest] NPC Crazy Larry is missing quest requirements 

### ISSUE THREAD

**Issue by MrTide** [SallyWhitemane/Maelstrom#427]
**Description:** This npc and quests can be found at Swamp of sorrows

**How to reproduce:** you need to do and turn the quest called crazy larry then they become available but here i have not done it yet nor have it in my quest log and they are available
![image](https://user-images.githubusercontent.com/36106057/176489443-0510768e-1c5f-4837-b828-c9d05f96e809.png)

**How it should work:** more info here
https://cata-twinhead.twinstar.cz/?quest=27597

**Comment by Afgann** [comment]
fixed
