### ISSUE TITLE
[NPC] Stagalbog Serpent, Marshfin murkdweller

### ISSUE THREAD

**Issue by MrTide** [SallyWhitemane/Maelstrom#428]
**Description:** These creatures can be found at swamp of sorrows 

**How to reproduce:** They are missing basic movements they don't move at all
![image](https://user-images.githubusercontent.com/36106057/176492131-2ad809c0-f4ee-4cef-b856-c3ee2e3700a6.png)
![image](https://user-images.githubusercontent.com/36106057/176492179-e03c7103-b705-47a1-af94-31f65885d670.png)

**How it should work:** you can see their right behavior here
https://www.youtube.com/watch?v=tg5wa0gOi5Q

**Comment by Afgann** [comment]
fixed
