### ISSUE TITLE
[World Event] Candy Bucket in-game when it's Midsummer fest

### ISSUE THREAD

**Issue by phonkala** [SallyWhitemane/Maelstrom#430]
**Description:**
Found a Candy Bucket in-game from Farstrider Lodge @ Loch Modan during Midsummer Fire Festival world event. Candy Buckets should be linked to Hallow's End world event starting in October.
![WoWScrnShot_063022_130249](https://user-images.githubusercontent.com/43609330/176651239-6f9cd95a-dc3f-4272-8ea3-1817b5db743b.jpg)

Interacting with the bucket did bring up empty gossip menu.
![WoWScrnShot_063022_130301](https://user-images.githubusercontent.com/43609330/176651253-90414ff7-d105-4da5-91ed-eb96ec4af56d.jpg)

**Comment by phonkala** [comment]
Another one at Swiftgear Station @ Wetlands
![WoWScrnShot_070622_175438](https://user-images.githubusercontent.com/43609330/177580254-85deac93-4351-4e91-ba03-5ba2977b2870.jpg)

**Comment by Afgann** [comment]
fixed
