### ISSUE TITLE
[Generic] Caster enemies seem to wait 3-5s before doing anything

### ISSUE THREAD

**Issue by phonkala** [SallyWhitemane/Maelstrom#437]
Many "pure" caster mobs, when attacked, just seem to wait for around 3-5 seconds before attacking at all, just idling doing nothing. With "pure" caster mobs I mean the ones that should always just cast if they have mana and only start meleeing after that.

You can try aggroing these mobs from range and as you see, they just wait there a while doing nothing. Couple examples of such mobs:
- Kobold Geomancer
- Scarlet Magician
- Mo'grosh Earthbender

This was also happening when I was leveling another character, but didn't really focus on that too much then. But now I see it happens all over the map so there is some issue there.

**Comment by phonkala** [comment]
Just found this closed issue which is same problem: https://github.com/SallyWhitemane/Maelstrom/issues/379

I think this issue should definitely be kept open as how else will people know this is a known issue and not fixed (closed)? Not everyone reads the closed issues, they just check the title.

Maybe just add some generic. sticky issue of it and post new npc's that are found and have this same problem as comments?

**Comment by MrTide** [comment]
Reported this already by the look of it we need to report every single one ... 
https://github.com/SallyWhitemane/Maelstrom/issues/379
I will ask sitdev again to see if he can fix them all at once

**Comment by ghost** [comment]
The problem here is just bad SAI scripts, so we can't do here any generic solution. @MrTide @phonkala Just report every single mob with this problem.
