### ISSUE TITLE
[NPC][Movements] Volchan

### ISSUE THREAD

**Issue by MrTide** [SallyWhitemane/Maelstrom#439]
**Description:** this creature can be found at burning steps

**How to reproduce:** He is supposed to be walking lava but he is hovering/flying over it with wrong animations
![image](https://user-images.githubusercontent.com/36106057/176681827-0f42c597-6332-4aad-b50f-b67bf8e2a1b4.png)

**How it should work:** like the video below 
https://www.youtube.com/watch?v=gx_4wii3XKU

**Comment by phonkala** [comment]
Was already "fixed" but seems incorrectly :)
https://github.com/SallyWhitemane/Maelstrom/issues/125
