### ISSUE TITLE
[NPC] Margol the rager

### ISSUE THREAD

**Issue by MrTide** [SallyWhitemane/Maelstrom#442]
**Description:** this npc can be found in searing gorge

**How to reproduce:** he is missing movements he just stands there
![image](https://user-images.githubusercontent.com/36106057/176690325-9a354693-ab2f-4aae-a8b1-9c890e661bbb.png)

**How it should work:** he is supposed to patrol the area around the mountain
https://www.youtube.com/watch?v=AbxnBXOwtkk

**Comment by Afgann** [comment]
fixed
