### ISSUE TITLE
[NPC][Quest] Missing quest requirements 

### ISSUE THREAD

**Issue by MrTide** [SallyWhitemane/Maelstrom#444]
**Description:**
These quests can be found at searing gorge

**How to reproduce:** They are not following the requirements and available for the players eitherway
Thorium Point: The Seat of the Brotherhood quest supposed to open the quests below and i have not even done it but still available
![image](https://user-images.githubusercontent.com/36106057/176691924-b8be271f-c25c-492d-9f97-cc4852a375c8.png)
![image](https://user-images.githubusercontent.com/36106057/176691671-968e27e3-f6a8-4988-a7f0-4f13d66904fb.png)
![image](https://user-images.githubusercontent.com/36106057/176692037-0b24f4d1-2ef1-4786-be40-20a36bab24e6.png)
Only quest Rasha'krak follows the requirements

**How it should work:** they should follow the requirements 
https://cata-twinhead.twinstar.cz/?quest=27965

**Comment by Afgann** [comment]
fixed
