### ISSUE TITLE
[NPC] Lunk

### ISSUE THREAD

**Issue by MrTide** [SallyWhitemane/Maelstrom#445]
**Description:** This npc can be found at searing gorge

**How to reproduce:** everytime you kill a dark iron steamsmith and  glassweb spider one of them spawn which they are supposed to when you have the quests named  "A Proper Antivenom" and  "Recon Essentials" but on every kill it would spam the area with them specially with dynamic respawns and such would be a nightmare
fortunately they despawn after a while but only one of them should be there  
![image](https://user-images.githubusercontent.com/36106057/176693350-328e6b20-860d-4921-8c9e-706febaf114e.png)
![image](https://user-images.githubusercontent.com/36106057/176696976-7c24c74d-f806-4791-9bc4-f1c690d3eab0.png)

also he is not despawning after doing his tasks either
he got two tasks for you which spawns after killing the creatures
Lunk's Adventure: Cranky Little Dwarfs and Lunk's Adventure: Spider Rider

**How it should work:** only one should be there 
and he is supposed to despawn when you finish his tasks and show up again if you decide to do his other tasks.. 
you can see them despawn after finishing the quest
https://www.youtube.com/watch?v=KAyyZ3ARO5k
https://www.youtube.com/watch?v=J9pxo_7W0Vo

**Comment by Afgann** [comment]
fixed
