### ISSUE TITLE
[NPC] Twilight Idolater and dark iron marksman

### ISSUE THREAD

**Issue by MrTide** [SallyWhitemane/Maelstrom#446]
**Description:** these creatures can be found in searing gorge 

**How to reproduce:** Long dly before casting
https://user-images.githubusercontent.com/36106057/176701083-1748df64-86d4-4898-b1b4-d04603965030.mp4
https://user-images.githubusercontent.com/36106057/176701090-02ec3032-24ac-493a-b765-1ef0a7faec07.mp4

**How it should work:** they should not wait that long to cast or hit you
related issue: https://github.com/SallyWhitemane/Maelstrom/issues/379

**Comment by Afgann** [comment]
fixed
