### ISSUE TITLE
[Quest][NPC] Lunk's Adventure: Rendan's Weakness

### ISSUE THREAD

**Issue by MrTide** [SallyWhitemane/Maelstrom#448]
**Description:**
This Quest can be found at searing gorge

**How to reproduce:** He still follows you even after finishing the quest
he should despawn
![image](https://user-images.githubusercontent.com/36106057/176704405-fa111186-d6bc-430a-9749-9e7593bbe6ba.png)

**How it should work:**
https://www.youtube.com/watch?v=9cEPOEIPFfY

**Comment by Afgann** [comment]
fixed
