### ISSUE TITLE
[NPC][Quest] Dragonmaw Grunts and Scouts have way too much HP

### ISSUE THREAD

**Issue by phonkala** [SallyWhitemane/Maelstrom#453]
**Description:**
Dragonmaw Grunts and Scouts are around lvl 20 mobs and they got over 200k health. They do correct damage, just the health is way too high. There is also the quest "Cleaning Hovel" related where you need to kill those guys, so currently can't complete with a lvl 25 toon.

![WoWScrnShot_070122_141512](https://user-images.githubusercontent.com/43609330/176885029-06d0ac5a-9319-4bf4-a7d7-33cb9251df49.jpg)

**Comment by Afgann** [comment]
fixed
