### ISSUE TITLE
[Generic][NPC] Mobs on land can't enter water, mobs in water can't come to land, both evade

### ISSUE THREAD

**Issue by phonkala** [SallyWhitemane/Maelstrom#456]
**Description:**
Was starting Wetlands quest and now seen this issue happen all the time. Already posted couple issues about mobs in water evading (https://github.com/SallyWhitemane/Maelstrom/issues/454, https://github.com/SallyWhitemane/Maelstrom/issues/455) as I though it is just an issue with those. 

But seems to happen now with Dark Iron Holdouts in Wetlands too. These guys are humanoids walking on shore and I attacked them from shallow water, and they started evading like they couldn't get to me. I watched him run around the shore a little while (after he evaded to full health, was still trying to attack me though) and then he suddenly found his way to me, and I killed him.

So I'm guessing there is some more generic issue with waterline, pathing or maybe surface of water.

**Comment by phonkala** [comment]
Also seems, that if I manage to kill one of these mobs that does evade and before resetting finds a way to attack me, it does not respawn later in full HP. Tested this too 4 times, the mob I killed always respawned with the HP it had before the killing blow. Same issue happened with the linked other two issues that were about single mobs.

**Comment by ghost** [comment]
@phonkala As I can't reproduce it, please record some video of this.

**Comment by phonkala** [comment]
@UltraNix 3 videos @ https://drive.google.com/drive/folders/12SjCxB3K_o_z8oOEU7bpcDYFLuS1KDC0

**Comment by MrTide** [comment]
the only creatures that are not supposed to come out are fishes .. basically sea creatures.
