### ISSUE TITLE
[Tracking] Tracking Townsfolk > Class trainer shows all trainers, instead of only your own class

### ISSUE THREAD

**Issue by ghost** [SallyWhitemane/Maelstrom#46]
**Description:**
When tracking class trainers on the minimap, all trainers (including other classes that are not relevant to you) show up. While there are no patch notes specifying this behavior, I do remember that on the original Blizzard Cataclysm. only your own class trainers would be displayed on the minimap when tracking. This behavior is consistent on Apollo's Cataclysm realm as well. See attached videos for the difference in behavior between Apollo 3 and Maelstrom.

**How to reproduce:**
- Track class trainers in an area with various trainers (easily tested in a spawn zone such as Valley of Trials for Orcs)
- Note that class trainers for all classes are shown, instead of only your own class.

**How it should work:**
Tracking class trainers should only show the trainer for your own class, as the other class trainers are irrelevant to you and only clutter the map.

https://user-images.githubusercontent.com/106853563/172075546-be6af7bd-cae7-4ddd-8e80-96b4ecb668d1.mp4

https://user-images.githubusercontent.com/106853563/172075588-70228300-8999-4232-9893-1361c6baafd3.mp4

**Comment by phonkala** [comment]
Can confirm, all class trainers show up on minimap when tracking them. Didn't report this myself earlier because thought they might have changed it to be so in Cata (though, it would not make any sense to show class trainers for other classes).
