### ISSUE TITLE
[Quest] Dressing the part

### ISSUE THREAD

**Issue by MrTide** [SallyWhitemane/Maelstrom#466]
**Description:**
This quest can be found at stranglethorn

**How to reproduce:** Your reputation with [Bloodsail Buccaneers](https://cata-twinhead.twinstar.cz/?faction=87) must be at least Neutral to get this quest but i am getting it anyway while doing https://cata-twinhead.twinstar.cz/?quest=26629 quest line which Bloodsail buccaneers become friendly temporarily 
![image](https://user-images.githubusercontent.com/36106057/176937296-86199345-fb70-4abf-808d-eadad3896460.png)

**How it should work:**
https://cata-twinhead.twinstar.cz/?quest=9272

**Comment by phonkala** [comment]
Can confirm, I was also able to do this while on the other quest chain. Checked Wowhead patch 4.3.0 comments and yeah, it should not be available unless repu is at least neutral: https://www.wowhead.com/quest=9272/dressing-the-part#comments:id=1609977
