### ISSUE TITLE
[Quest][NPC] Bloodsail's End, The Damsel's (Bad) Luck 

### ISSUE THREAD

**Issue by MrTide** [SallyWhitemane/Maelstrom#469]
**Description:**
this quest can be found at bootybay

**How to reproduce:** when you try to kill creatures on board of the ship in this event they fall down to bottom floor of the ship for unknown reason
![image](https://user-images.githubusercontent.com/36106057/176943602-b6c12079-5e3b-47f1-b799-12a853b82bd4.png)

**How it should work:** they should not fall down under
https://www.youtube.com/watch?v=Yq6KKvfzRXs
https://www.youtube.com/watch?v=Ipt1oRAhrN8

**Comment by phonkala** [comment]
Boats still seem to have issues stuff going through walls and floor. These both were closed long ago, but I guess they were fixed other way than focusing on the actual boats:
https://github.com/SallyWhitemane/Maelstrom/issues/112, https://github.com/SallyWhitemane/Maelstrom/issues/51

**Comment by ghost** [comment]
Not fixable - static mmaps do not count gameobjects.
