### ISSUE TITLE
[Quest] Missing Quest Requirements "Krog"

### ISSUE THREAD

**Issue by MrTide** [SallyWhitemane/Maelstrom#474]
**Description:** These quests can be found at Dustwallow marsh

**How to reproduce:** These quest missing requirements, 
Inspecting the Ruins is supposed to open up [The Black Shield](https://cata-twinhead.twinstar.cz/?quest=27254) and [Suspicious Hoofprints](https://cata-twinhead.twinstar.cz/?quest=27259) [Lieutenant Paval Reethe](https://cata-twinhead.twinstar.cz/?quest=27260) quests while [Suspicious Hoofprints](https://cata-twinhead.twinstar.cz/?quest=27259) is available from start
![image](https://user-images.githubusercontent.com/36106057/177005880-b2406cbe-ae84-4d04-affb-5aed21b2c8a9.png)

More than coincidence is available without doing Return to Krog
which also is supposed to open up [The Grimtotem Plot](https://cata-twinhead.twinstar.cz/?quest=27293) and after doing that [Seek Out Tabetha](https://cata-twinhead.twinstar.cz/?quest=27295) quest line becomes available
they are available from start
![image](https://user-images.githubusercontent.com/36106057/177006189-6794228d-afdd-4af1-a1e8-b12da4f1b5e9.png)

**How it should work:** https://cata-twinhead.twinstar.cz/?quest=27253

**Comment by Afgann** [comment]
fixed
