### ISSUE TITLE
[NPC][Movements][Scripts] Grimtotem breaker and Grimtotem Elder

### ISSUE THREAD

**Issue by MrTide** [SallyWhitemane/Maelstrom#476]
**Description:** These creatures can be found at blackhoof villiage at dustwallow marsh

**How to reproduce:** Grimtotem Elder wait 3-5 sec before casting just looking at you which is a bad scripting and requires attention and Grimtotem breakers are missing movements they just stand in one place

**How it should work:** this is how they are supposed to work
https://www.youtube.com/watch?v=oWqW2qHU6tU

**Comment by Afgann** [comment]
fixed
