### ISSUE TITLE
[Quest][NPC] Corrosion Prevention

### ISSUE THREAD

**Issue by MrTide** [SallyWhitemane/Maelstrom#478]
**Description:** This quest can be found at dustwallow marsh

**How to reproduce:** This quest is not working as intended you can get credit with just casting your spells on creatures instead of Ooze buster device .. also it is supposed to kill the creatures after getting credit with ooze buster

**How it should work:** it should work like the video below
https://www.youtube.com/watch?v=9pISOTpykWo

**Comment by Afgann** [comment]
fixed
