### ISSUE TITLE
[Quest] An Ancient Enemy

### ISSUE THREAD

**Issue by Nooblerone** [SallyWhitemane/Maelstrom#48]
**Description:**
Talking to Vol'jin is not possible. The event kind of starts when you hit the boss, but then its bugged. At the end it should freeze enemies, kill an NPC and then die. Thats not happening and it stays in a loop

**How to reproduce:**
create a Char eligible for that quest, and try to speak to vol'jin

**How it should work:**
see above.

**Comment by ghost** [comment]
Fixed.
