### ISSUE TITLE
[Quest] Death From Below

### ISSUE THREAD

**Issue by MrTide** [SallyWhitemane/Maelstrom#488]
**Description:** This quest offered to the players at arathi highlands 

**How to reproduce:** Click on cannon does nothing and they just come and stack on top of quest giver ( Shakes o'breen)
![image](https://user-images.githubusercontent.com/36106057/177015665-ba866496-f002-4210-96ea-54c56e82a14f.png)

**How it should work:** cannon should work and if they somehow by pass the cannon range quest giver should fight them
https://www.youtube.com/watch?v=SSq_EppU6Mk
https://www.youtube.com/watch?v=x92kTEYbhc4

**Comment by phonkala** [comment]
Yeah can confirm, same issue here.
