### ISSUE TITLE
[NPC] [Movements] Terrortooth Runner, Terrortooth scytheclaw, Plains Pridemane, Thunderhead

### ISSUE THREAD

**Issue by MrTide** [SallyWhitemane/Maelstrom#490]
**Description:** These creatures can be found at barrens

**How to reproduce:** They are missing basic movements they dont move at all
![image](https://user-images.githubusercontent.com/36106057/177046327-ab725894-457b-4ea0-93b7-8770432f0505.png)
Also the tigers are not moving at all (atleast the ones that are awake and not sleeping)
![image](https://user-images.githubusercontent.com/36106057/177048265-c9c176aa-022e-4ef7-b1cf-20049666698e.png)
Thunderheads are not moving neither
![image](https://user-images.githubusercontent.com/36106057/177048667-6a12fc7e-1c2f-4f15-921b-c49069a1735a.png)

**How it should work:** here you can see them moving
https://www.youtube.com/watch?v=jsf38Rt6Hfg
https://www.youtube.com/watch?v=uoTOVaG6xPc
https://www.youtube.com/watch?v=-vDiHkk2YZs

**Comment by Afgann** [comment]
fixed
