### ISSUE TITLE
[NPC][Quest] Missing quest requirements " Keeping the Dogs at bay " and more

### ISSUE THREAD

**Issue by MrTide** [SallyWhitemane/Maelstrom#492]
**Description:** this quest can be found at barrens

**How to reproduce:** NPC makaba lathoof offering the quest without considering the requirement. as you can see the image below i havent done the quest but its still available
![image](https://user-images.githubusercontent.com/36106057/177047175-9bad7d90-2536-4ff7-b877-36b13c1c56bd.png)

I haven't done "Bad to worse" quest but "A family divided" quest is available 
https://cata-twinhead.twinstar.cz/?quest=24529
![image](https://user-images.githubusercontent.com/36106057/177047239-11a685c6-ba98-4db4-ac0a-819c1d8ab74e.png)

I havent done quest called "The Nightmare Scar" but "Winnoa Pineforest"
 is available https://cata-twinhead.twinstar.cz/?quest=24807

![image](https://user-images.githubusercontent.com/36106057/177047703-5e65aa2e-a1ae-4aa1-bbb9-b416eed0d202.png)

Quest "mahka's Plea" is available without doing "Concern for mankrik " .. its missing requirement.
https://cata-twinhead.twinstar.cz/?quest=24633
![image](https://user-images.githubusercontent.com/36106057/177049784-d6dff06a-9d86-4426-9416-159efe132671.png)

**How it should work:** it should follow the requirement
https://cata-twinhead.twinstar.cz/?quest=24525
https://cata-twinhead.twinstar.cz/?quest=24529
https://cata-twinhead.twinstar.cz/?quest=24807

**Comment by Afgann** [comment]
fixed
