### ISSUE TITLE
[class problems whit hunter pet]

### ISSUE THREAD

**Issue by Deflowdk** [SallyWhitemane/Maelstrom#493]
**Description:**
The hunter pet keep go to ground under water then you set it to attack something down in the water ( under the water)

**How to reproduce:**
swim directly to the target you set it to attack

**How it should work:**
swim directly to the target you set it to attack

**Comment by MrTide** [comment]
Can you provide more info ? like screenshots ? what were you fighting with ? etc etc

**Comment by Deflowdk** [comment]
Yes i Will so that give me 2min

Hent Outlook til Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Deflowdk** [comment]
![WoWScrnShot_070322_175838](https://user-images.githubusercontent.com/108612550/177047647-ca8ebaf8-9148-4743-9ae0-7905ea64b949.jpg)
![WoWScrnShot_070322_175844](https://user-images.githubusercontent.com/108612550/177047648-9123c6b7-52b3-4bd8-a0cf-ccb1819a821f.jpg)
![WoWScrnShot_070322_175859](https://user-images.githubusercontent.com/108612550/177047649-ccb9c676-4728-4186-9ec0-dc8db049f23d.jpg)
![Skærmbillede 2022-07-03 175951](https://user-images.githubusercontent.com/108612550/177047651-e15eae8b-33c5-4f1c-b0ae-317f0367ea3d.png)
![Skærmbillede 2022-07-03 180014](https://user-images.githubusercontent.com/108612550/177047654-a1a3a361-0514-494f-88c3-e989cbfc3c20.png)
![WoWScrnShot_070322_175736](https://user-images.githubusercontent.com/108612550/177047655-d744f6cb-cba9-4942-823b-61040528c3fe.jpg)
![WoWScrnShot_070322_175832](https://user-images.githubusercontent.com/108612550/177047656-11d24f49-ac07-4a8a-9dbf-9b591e821854.jpg)

**Comment by ghost** [comment]
Cannot reproduce it.
