### ISSUE TITLE
[Quest][NPC] Bad to Worse

### ISSUE THREAD

**Issue by MrTide** [SallyWhitemane/Maelstrom#494]
**Description:** This quest can be found at barrens 

**How to reproduce:** There is nothing inside cages 
![image](https://user-images.githubusercontent.com/36106057/177047346-39f76da3-d9c7-4b91-9b47-8536ed3b0ec4.png)
![image](https://user-images.githubusercontent.com/36106057/177047392-853e1d32-556d-4e2d-83e2-2ca2e9df523d.png)

**How it should work:** Like the video below
https://www.youtube.com/watch?v=rVIxTxnFzx0

**Comment by Afgann** [comment]
fixed
