### ISSUE TITLE
[NPC] Landquaker Kodo, Landquaker bull, Thunderhawk Cloudscraper, Disturbed earth elemental

### ISSUE THREAD

**Issue by MrTide** [SallyWhitemane/Maelstrom#496]
**Description:** These creatures can be found at barrens 

**How to reproduce:** None of them have any basic movements

![image](https://user-images.githubusercontent.com/36106057/177049481-8ce1ee33-3835-4d47-924c-13862fb30625.png)
![image](https://user-images.githubusercontent.com/36106057/177050290-2897705c-739d-4c90-b585-b3f66b0bea50.png)

**How it should work:** you can see them moving here
https://www.youtube.com/watch?v=V3Gp9tEtp_I
https://www.youtube.com/watch?v=BELk7nV1Edo

**Comment by Afgann** [comment]
fixed
