### ISSUE TITLE
[NPC] Razormane pathfinder, razormane warfrenzy, razormane seer

### ISSUE THREAD

**Issue by MrTide** [SallyWhitemane/Maelstrom#498]
**Description:** these creatures can be found at barrens 

**How to reproduce:** They are missing movements  they dont move at all
![image](https://user-images.githubusercontent.com/36106057/177050126-67673fc5-7032-4836-b65e-d2a13b377261.png)

**How it should work:** you can see them having basic movements here
https://www.youtube.com/watch?v=fF3cMxQhOEU

**Comment by Afgann** [comment]
fixed
