### ISSUE TITLE
[NPC] Lien Farner - Talk options are swaped!

### ISSUE THREAD

**Issue by Hewlith** [SallyWhitemane/Maelstrom#50]
**Description:**
If you press "Tell me about gathering Professions" it shows Produktion Professions and the other way around.

**How to reproduce:**
Talk to Lien Farner and use one of the Talking Options.

**How it should work:**
The other way around :D

**Comment by phonkala** [comment]
Duplicate of https://github.com/SallyWhitemane/Maelstrom/issues/23
