### ISSUE TITLE
[mount] animation problem

### ISSUE THREAD

**Issue by Deflowdk** [SallyWhitemane/Maelstrom#501]
**Description:**
when you press w ( forward ) at the moment you mount up the hand will be up in the air
![WoWScrnShot_070422_100116](https://user-images.githubusercontent.com/108612550/177110498-032a197d-96d3-4a66-b546-5b1fdea4f1c4.jpg)

**How to reproduce:**

**How it should work:**
When you mount up the hand should come into the air and then down to grab the horse agin

**Comment by ghost** [comment]
It's clientside. But still works okay to me.
