### ISSUE TITLE
[NPC][Movements] Tidal Strider, desert Crawler, Duneclaw burrower, duneclaw Lasher, Dune claw matriarch, Sandstone Golem

### ISSUE THREAD

**Issue by MrTide** [SallyWhitemane/Maelstrom#503]
**Description:** These creatures can be found at tanaris

**How to reproduce:** They are missing basic movements they just stand in place and wont move 
![image](https://user-images.githubusercontent.com/36106057/177191564-f81ff64e-467f-4f62-86fd-4fba4b254390.png)
![image](https://user-images.githubusercontent.com/36106057/177192419-a18059f1-7d62-4543-a165-485315749374.png)
![image](https://user-images.githubusercontent.com/36106057/177192437-6122218e-95fa-4d10-8a00-9a43e4a257e6.png)
![image](https://user-images.githubusercontent.com/36106057/177193553-561f3cf8-eb59-4cdc-92ea-2f6ddb6e494f.png)
![image](https://user-images.githubusercontent.com/36106057/177200571-c8f8abdd-3a1e-4d3e-8024-b6be99a9809f.png)

**How it should work:** you can see them moving here in these videos
https://www.youtube.com/watch?v=ky4sbZWwqBk
https://www.youtube.com/watch?v=LIHa7qN-Bz4
https://www.youtube.com/watch?v=59oe3CBU2RE
https://www.youtube.com/watch?v=-u6UsadtebM

**Comment by Afgann** [comment]
fixed
