### ISSUE TITLE
[NPC] SandFury axe thrower, Sandfury firecaller, southsea musketeer

### ISSUE THREAD

**Issue by MrTide** [SallyWhitemane/Maelstrom#504]
**Description:** These creatures can be found at tanaris

**How to reproduce:** they have 3-5 sec delay before starting to cast ( most of range creatures in the world are like this)

https://user-images.githubusercontent.com/36106057/177194116-b149ea38-4a73-4526-8155-98916cd429dd.mp4

https://user-images.githubusercontent.com/36106057/177194185-5489b80a-4cdb-4aa6-bc29-34a3fb6c8933.mp4

https://user-images.githubusercontent.com/36106057/177197342-ba5074bb-2d45-49cd-bd84-cb740285b5fb.mp4

**How it should work:** they should not have a delay 
More info here : https://github.com/SallyWhitemane/Maelstrom/issues/379

**Comment by Afgann** [comment]
fixed
