### ISSUE TITLE
[NPC] Misplaced Kelsey Steelspark and Megs dreadshredder

### ISSUE THREAD

**Issue by MrTide** [SallyWhitemane/Maelstrom#506]
**Description:** these creatures can be found at tanaris

**How to reproduce:** they are simply misplaced 
![image](https://user-images.githubusercontent.com/36106057/177196270-0c02ba13-98e3-4209-bae4-c23cd0778bd4.png)
![image](https://user-images.githubusercontent.com/36106057/177196289-a2f15de4-ca59-45b4-8508-018ec9f4e710.png)

**How it should work:** we need to exchange their spots... Kelsey Steelspark should be standing next to Covert ops hardsuit and Megs dreadshredder should be next to bilgewater battlebruiser
https://www.youtube.com/watch?v=iPDB1D3IM5A

**Comment by ghost** [comment]
Fixed.
