### ISSUE TITLE
[Quest] [NPC] To The Ground! and Covert ops punder

### ISSUE THREAD

**Issue by MrTide** [SallyWhitemane/Maelstrom#507]
**Description:** This quest and npc can be found at tanaris

**How to reproduce:** Using the quest item to burn down the houses is missing fire animation on the house and Covert ops punder is not going around to shoot rockets at the houses 
![image](https://user-images.githubusercontent.com/36106057/177197564-19194457-6f82-47b6-8605-15e62a29c597.png)

**How it should work:** npc and quest should work like the video below
https://www.youtube.com/watch?v=r2abngCQkxU

**Comment by ghost** [comment]
Fixed.
