### ISSUE TITLE
[NPC] Southsea musketeer, southsea strongarm | Southbreakshore/lost rigger cove

### ISSUE THREAD

**Issue by MrTide** [SallyWhitemane/Maelstrom#508]
**Description:** This are can be found at tanaris

**How to reproduce:** they are simply missing movements some of them should be patrolling the roads some should have basic movements, a few should be patrolling the  camp .. basically nothing moves in this camp
![image](https://user-images.githubusercontent.com/36106057/177198193-91b97cb4-f3be-4a1d-964f-9b06bcf84e4a.png)
![image](https://user-images.githubusercontent.com/36106057/177198203-7a80be7c-d063-489a-89f0-753fae1aaa6e.png)
![image](https://user-images.githubusercontent.com/36106057/177198341-e98ab448-2b1e-4fca-8951-ee83e612b709.png)

**How it should work:** like the video below 
https://www.youtube.com/watch?v=8BGg_eF2IwA

**Comment by ghost** [comment]
Fixed.
