### ISSUE TITLE
[Quest]  The Scent of Lar'korwi

### ISSUE THREAD

**Issue by MrTide** [SallyWhitemane/Maelstrom#509]
**Description:** This quest can be found at Ungoro crater

**How to reproduce:** Quest is not scripted at all ... its still doable but its not working properly Lar'korwi mates are just standing around while they should be spawns 
![image](https://user-images.githubusercontent.com/36106057/177352195-522296e0-6fa5-4320-a706-7f24c3a4db2c.png)

**How it should work:** it should work like the video below
https://www.youtube.com/watch?v=kpoOQgSMY4g
also mentioned on wowhead comments
https://www.wowhead.com/quest=24732/the-scent-of-larkorwi#comments:id=1182908

**Comment by ghost** [comment]
Fixed.
