### ISSUE TITLE
[Quest][NPC] Bouquets of Death

### ISSUE THREAD

**Issue by MrTide** [SallyWhitemane/Maelstrom#510]
**Description:** This quest can be found at ungoro

**How to reproduce:** creatures that you need to kill for this quest are supposed to be running around while they have no movements
![image](https://user-images.githubusercontent.com/36106057/177355757-a31edb28-374d-4d94-b7e7-3de2a78c4941.png)

**How it should work:** like the video below
https://www.youtube.com/watch?v=PcmfndKrhkg

**Comment by Afgann** [comment]
fixed
