### ISSUE TITLE
[Quest]  The Eastern Pylon

### ISSUE THREAD

**Issue by MrTide** [SallyWhitemane/Maelstrom#511]
**Description:** This quest can be found at ungoro crater

**How to reproduce:** after taking the quest you dont get teleporter to top and neither 
click on transport does anything 
![image](https://user-images.githubusercontent.com/36106057/177357950-a2fbad21-9eb9-4227-b6b3-494fa71dbdf1.png)

**How it should work:** It should port you up top like the video below
https://www.youtube.com/watch?v=6sB5R6O3uQ4

**Comment by Afgann** [comment]
fixed
