### ISSUE TITLE
[Quest]  Damsels Were Made to be Saved

### ISSUE THREAD

**Issue by MrTide** [SallyWhitemane/Maelstrom#512]
**Description:** This quest can be found at ungoro crater

**How to reproduce:** first event worked fine but on second quest the npc that follows you just flied away xD (i don't blame him tho second one was a male blood elf xD)
![image](https://user-images.githubusercontent.com/36106057/177366138-9c8c2356-3c35-4b77-b27b-f5568f268d9a.png)

also none of the options on him work
![image](https://user-images.githubusercontent.com/36106057/177367055-f09ac252-27a9-4a7e-b70a-fa639c027042.png)

**How it should work:** Like the video below
https://www.youtube.com/watch?v=RjGwu8lJ6-s

**Comment by ghost** [comment]
Fixed.
