### ISSUE TITLE
[Quest] Rain of Destruction

### ISSUE THREAD

**Issue by MrTide** [SallyWhitemane/Maelstrom#515]
**Description:** This quest can be found at ashenvale

**How to reproduce:** after finishing the quest you can still get the imp disguise also there are two duraks which i assume its phasing issues which also includes quest "Dread Head Redemption" and more
![image](https://user-images.githubusercontent.com/36106057/177374784-f275b469-2df6-464d-aa75-d2f45ad2a878.png)

**How it should work:**  Please keep in mind Durak is supposed to start and end multiple quests so phases are important there... multiple versions of him are in there

https://cata-twinhead.twinstar.cz/?search=durak#npcs

So this is what i am suggesting NPC ID 44414 should be available when you get the quest called  "Dread Head Redemption" (which is right now) and npc ID: 33760 should phase out(which is not phasing out right now) until you finish this quest and turn it in or abandon it and after turning this quest in or finishing it npc ID: 33760 becomes available again and NPC ID 44414 phases out ( npc 44414 phases out already after finishing the quest)
So to sum it out only npc that has issues is NPC ID 33760 he should not offer the disguise after finishing Rain of Destruction quest and also phase out when you have "Dread Head Redemption" quest

Note: the npc that is phased with you while using the imp got different id which is 33977 and you use it to finish the quest "Rain of Destruction" so don't confuse him with this issue he is not related and have no issues.

**Comment by ghost** [comment]
Everything works okay.
