### ISSUE TITLE
[Quest] Crisis at Splintertree

### ISSUE THREAD

**Issue by MrTide** [SallyWhitemane/Maelstrom#517]
**Description:** This quest can be found at ashenvale 

**How to reproduce:** NPC is not saying your name 
![image](https://user-images.githubusercontent.com/36106057/177378962-845e7765-345b-484e-9667-15ea7ba7f68c.png)

and after mounting up event is not working completely some lines and encounters are not getting played 
![image](https://user-images.githubusercontent.com/36106057/177378715-c9dffd72-5ea8-4af2-8ed1-e1128413e228.png)

**How it should work:** it should work like the video below
https://www.youtube.com/watch?v=XCl692e9mRc

Related issue which didn't get fixed properly https://github.com/SallyWhitemane/Maelstrom/issues/194

![image](https://user-images.githubusercontent.com/36106057/177379667-b917c9aa-e7d7-43d5-9bbb-4e1910ece955.png)
still have issues even tho you said its fixed

**Comment by ghost** [comment]
Because it's fixed. That missing line of text - of course I can fix it. But the whole events is not gonna works better because of lack of data (waypoints/spells/actions etc).

**Comment by MrTide** [comment]
> Because it's fixed. That missing line of text - of course I can fix it. But the whole events is not gonna works better because of lack of data (waypoints/spells/actions etc).

Videos are not enough ? are you saying core limits you ?

**Comment by ghost** [comment]
Not core - lack of data. I tested that and works pretty okay to me. I won't spend hours on correcting some visuals.
