### ISSUE TITLE
[Quest] The Final Voyage of the Brashtide - the Wind Rider does not fly

### ISSUE THREAD

**Issue by phonkala** [SallyWhitemane/Maelstrom#52]
**Description:**
On the quest you are supposed to get a Wind Rider from Kebok, which you then use to fly around and bomb the buccaneers in boats. Everything else works, but the Wind Rider won't fly, jumping off the roof ends you up in water. Actually, the Wind Rider should be on a pathed flight, instead you end up manually controlling it. Video of how it should work: https://www.youtube.com/watch?v=Y-bNRA2RwVQ

However you can complete the quest just by using the bombs in the water. Also the button used to return the Wind Rider to original starting place doesn't work, but you can just exit vehicle and run back.

![WoWScrnShot_060622_145229](https://user-images.githubusercontent.com/43609330/172156646-894e3008-1ee6-4bf2-bd8d-4a7007a6ef8b.jpg)

**Comment by phonkala** [comment]
Still doesn't work, Wind Rider won't fly.

**Comment by ghost** [comment]
Because it's not Live yet.
