### ISSUE TITLE
[Quest] Might of the Stonemaul  "FeedBack"

### ISSUE THREAD

**Issue by MrTide** [SallyWhitemane/Maelstrom#525]
**Description:** Might of the Stonemaul quest is not working as intended

**How to reproduce:** there are no Ogres fighting for you and Orhan Ogreblade does no damage with his weapon and The fix that developers did is not how its supposed to be .. it sure did improve it but it didnt fix it ... there are still missing scripts and player can still agrro the boss at start since the npc that is helping does no weapon damage 

**How it should work:** please check the video below
https://www.youtube.com/watch?v=jusYkAPQsC4

**Comment by ghost** [comment]
Won't fix.
