### ISSUE TITLE
[Pathing] More pathing issues in water, mobs reset HP but not combat

### ISSUE THREAD

**Issue by phonkala** [SallyWhitemane/Maelstrom#527]
**Description:**
Was able to do some more quests after a 5 day break. Continued with Wetlands quests inside Menethil Harbor. There still seems to be issues with pathing when in water so reporting it here. These previous ones that I reported and that could be related (https://github.com/SallyWhitemane/Maelstrom/issues/454, https://github.com/SallyWhitemane/Maelstrom/issues/455, https://github.com/SallyWhitemane/Maelstrom/issues/456) are closed but not sure if they are live on server yet, they could possibly fix this issue.

However, the issue again is that when I attacked a crab in water from certain spot, it took LOOONG way to get to me. The route is drawn on the screenshot. The crab was originally at the spot drawn in green and when I attacked it from red spot, it took all the way along the blue line to get to me. If I moved couple steps away from my original spot, the crab would come directly to me.

![WoWScrnShot_070622_172142](https://user-images.githubusercontent.com/43609330/177575105-e5a95c53-0bcc-4420-a79d-57878fd9ea9c.jpg)

Also, another weird thing that happened with this one and on the other issues that I linked too: When the mobs go the long route, they kinda get far out of your range. They do reset their health if they go far enough, but they don't drop combat and still come to you. They definitely should either reset completely, or their health should remain if they keep you in combat and still come to attack you.

**Comment by phonkala** [comment]
Same problem happening with Cursed Sailors along the shore. They took crazy long route to get on shore from water, went almost out of whole drawing distance (maxed), when they should just directly swim to you.

**Comment by ghost** [comment]
The fix is still not live.

**Comment by ghost** [comment]
@phonkala Please test it.

**Comment by phonkala** [comment]
@UltraNix Tested quickly before heading outdoors. First impression was that now all the "bugged" mobs are hovering over water like the ones in https://github.com/SallyWhitemane/Maelstrom/issues/528 , is that the fix just so we know? Was there some changes in mob locations/paths, so I know what to keep an eye for?

I didn't see any bugged (bugged = evading in this case) mobs anymore when it comes to issues https://github.com/SallyWhitemane/Maelstrom/issues/454 and https://github.com/SallyWhitemane/Maelstrom/issues/455 , but mobs are now floating in air and it kinda _looks_ even "more bugged". IMO it's better this way though than previous, they are all easily killable now!

Tested also https://github.com/SallyWhitemane/Maelstrom/issues/527 quickly, they no longer take the loooong route to get to me, they swim straight. But now they started evading a lot @ first attack. Sadly no time to get video, but if yolu just stand where I am at the screenshot, they start evading now.

Also tested the Cursed Sailors (second comment of this issue), they did now swim straight to shore based on just couple quick tests. It feels like there is no more "barrier" for mobs to swim/run to shore.

All in all, seems the way the mobs find their way to me is lots better, but I guess the fixes have caused some more issues, which are not that bad but might look bit bad :) I will test this more during the weekend and report here, can take some videos too if needed. At the least, very good start, nice job :)

**Comment by ghost** [comment]
The problem with weird, long paths should be fixed. If there are any new problems, then it must be fixed again.

**Comment by ghost** [comment]
@phonkala This floating is just visual - lack of swimming flag. Not related to this one. I'm closing this.
