### ISSUE TITLE
[Dungeon] [Ragefire Chasm] Searing Blade Warlock, Ragefire shaman

### ISSUE THREAD

**Issue by MrTide** [SallyWhitemane/Maelstrom#529]
**Description:** this dungeon can be found in orgrimmar

**How to reproduce:** warlocks and shamans take long time to cast 3-5 sec which is a known issue

https://user-images.githubusercontent.com/36106057/177786560-deb38115-f904-4039-b050-e5dbaae1eae0.mp4

https://user-images.githubusercontent.com/36106057/177783695-6b43722b-8cfc-43dc-9c77-8a1d77de64ad.mp4

https://user-images.githubusercontent.com/36106057/177783380-1ead0a4a-c394-4f09-a2e1-a4f7a99807da.mp4

**How it should work:**
 please understand i have seen developers applying fixes to other creatures scripts with similar issues  which causes them to go on melee first then start casting thats wrong they need to start casting where they stand then if they run out of mana or forced in melee combat start hitting with their weapons. also their pet wont attack for some reason until you are in aggro range or being attacked

**Comment by Afgann** [comment]
fixed
