### ISSUE TITLE
[Dungeon] [Deadmines] defias cannon, Mining monkeys, Lumberingoaf and more

### ISSUE THREAD

**Issue by MrTide** [SallyWhitemane/Maelstrom#530]
**Description:** This dungeon can be found at westfall

**How to reproduce:** defias cannon does not deal any damage when you try to control them
Mining monkeys are not mining they just stand there and after getting freed they are supposed to throw stuffat enemy troops  (which they are)  and have basic movements.. rest of their scripting seems working decently enough tho
![image](https://user-images.githubusercontent.com/36106057/177793720-c5f4f90d-634f-4d31-a382-d7a8c8d04c90.png)
Helix Gearbreaker when is on top of Oaf he is just supposed to throw bombs not also hit the players here it does hit players...  if you wipe you can't kill this boss anymore event is supposed to restart so  you can try again. also he hits way too fast. and wont jump on players 
![image](https://user-images.githubusercontent.com/36106057/177797622-b2c7b109-a7e4-495b-8857-ef4718c330b6.png)
![image](https://user-images.githubusercontent.com/36106057/177797660-4c6e899f-087b-4daf-8d6e-d40d9b798a1c.png)
Mining powders are not exploding after hitting them or getting close to them
![image](https://user-images.githubusercontent.com/36106057/177802196-e48227c1-68d9-4240-b344-7ae3862fd072.png)
a few of Goblin Craftsmans and engineers are supposed to be friendly and some dead on the ground and have lines here they dont hit you but you can still hit them they are supposed to run away...
![image](https://user-images.githubusercontent.com/36106057/177803435-88da2c3b-b80a-4b98-b012-6a57695c4eec.png)

Foe reaper 5000 overdrive spell he is  supposed to move when its casting overdrive here he just wont move

Admiral Ripsnarl stacking his Thirst for blood waaaaay too fast he should not stack it that fast 
admiral ripsnarl is dropping green winter hat without the event ( i recommend the checking the whole event)
![image](https://user-images.githubusercontent.com/36106057/177810248-e6799591-25cb-4afa-a7d3-8c7ac4284dce.png)
On captain cookie encounter rotten food are supposed to have different animations (an aura around them) which they are missing also if you wipe he aggros you again from far away which i don't think is correct he basically keeps you in combat...
![image](https://user-images.githubusercontent.com/36106057/177811916-5bd99aab-ee52-452e-bd3d-2da82557589e.png)

Fefias squallshapers have the delay casting of 3-5 sec before they start casting

**How it should work:** 
https://youtu.be/UWSOU2yPPS8?t=341 monkeys
https://youtu.be/sWTAGVRJ0oY players using cannons
https://www.youtube.com/watch?v=CSRwjFLjmcc Helix fight
https://youtu.be/sWTAGVRJ0oY?t=123 mines exploding and Goblin running away
https://www.youtube.com/watch?v=VaTQzS4G5JQ foe reaper 5000
https://youtu.be/sWTAGVRJ0oY?t=809 admiral ripsnarl
captain cookie : https://youtu.be/sWTAGVRJ0oY?t=882

**Comment by Afgann** [comment]
fixed
