### ISSUE TITLE
[Dungeon][WC][NPC] Druid of the fang, Muyoh 

### ISSUE THREAD

**Issue by MrTide** [SallyWhitemane/Maelstrom#531]
**Description:** This dungeon can be found at barrens

**How to reproduce:** Druid of the fang casters have 3-5 sec delay its a know issue with the creatures around the world.
after failing to protect Muyoh he just simply runs to the entrance with insane speed while its better to let him die and respawn a few seconds later
deviate moccasins hit way too hard ... players barely have 500hp here
![image](https://user-images.githubusercontent.com/36106057/177816178-ef25af23-a993-4daa-8820-92d1f13025ba.png)
![image](https://user-images.githubusercontent.com/36106057/177816346-e6a1fdc6-b298-4e14-b04f-bd93488d8e93.png)

Muyoh event should not be available to do without killing four leaders of the fang while here its available, also he should cast mark of the wild on you and your group after talking to him
![image](https://user-images.githubusercontent.com/36106057/177821332-d64eaaf4-1dda-44be-b122-463f3a41998b.png)

**How it should work:** a full run from 11 years ago
https://www.youtube.com/watch?v=dS_szT-tMvE
more info about Muyoh here
https://wowpedia.fandom.com/wiki/Muyoh

**Comment by Afgann** [comment]
fixed
