### ISSUE TITLE
[Dungeon] Shadowfang keep

### ISSUE THREAD

**Issue by MrTide** [SallyWhitemane/Maelstrom#532]
**Description:**
This dungeon can be found at silverpine forest

**How to reproduce:** after killing Baron ashbury, alive forsaken friendly guards should spawn (Veteran forsaken Trooper, Forsaken blightspreader) here they spawn but they are dead (please keep in mind players should not be able to use these to kill creatures....  (Veteran forsaken Trooper and  Forsaken blightspreader should not be dead you can see that in this video: https://youtu.be/i2OBzSOipAY?t=347 first boss)
![image](https://user-images.githubusercontent.com/36106057/177828053-a580bd83-852a-4931-88d8-25afa1c7dcc8.png)

![image](https://user-images.githubusercontent.com/36106057/177827721-264ca563-ab78-481a-829e-a29fbe855431.png)

Lupine Spectre's are summon creatures during  baron silverlaine fight there are three of them and they are hitting for more than 300 which is wrong they wipe the party in seconds they are not supposed to hit that hard 
![image](https://user-images.githubusercontent.com/36106057/177830649-6b42f77a-b33a-4e3b-8165-308d638677e0.png)
friendly guards are dead on the ground after killing the baron ( they should not be dead you can see that in this video https://youtu.be/k7_1cOoHeFM?t=288 )
![image](https://user-images.githubusercontent.com/36106057/177831037-af41fe8f-5c18-47c2-b4f4-484c8146ce20.png)
also by the look of it baron only summons Wolf Master Nandos
he should summon multiple bosses at random more info here : https://wowpedia.fandom.com/wiki/Baron_Silverlaine
Commander Springvale desecration stalker hits players for some reason i believe its a world trigger... it hits for 1500+ (2000+with crit) its impossible to kill this boss
![image](https://user-images.githubusercontent.com/36106057/177832023-9041545f-a30d-4b97-abb0-76346f38b182.png)
Frantic Geist are not patrolling also you dont get the message that says " a nearby gargoyle comes to life "  ( shown in the videohttps://youtu.be/S4bh_WiGmd4?t=214)
![image](https://user-images.githubusercontent.com/36106057/177833350-a3903767-759a-4a21-a637-bdc3e51a1920.png)
 Lord walden animation issues : he won't raise his hand like he is casting the ice shards  (like this video https://www.youtube.com/watch?v=aJzjtKOBkf0 ) 
![image](https://user-images.githubusercontent.com/36106057/177834707-9c794ab7-1e9b-4ebb-abc7-9a20a2ca2d25.png) 

Dread Scryers have long delays 3-5 sec before casting 

Lord godfrey Pistol barrage has no animations there is no way to tell where is he shooting at. bloodthirsty Ghouls come out of the ground way too fast, summon bloodthirsty ghouls ability animations are not correct it drops two of them while 3-4 creatures spawn  it should be like this video : https://youtu.be/4TizbbS5cbA?t=277
also he is keep saying "This is the quality of assassins sent to kill me" laughable" after killing his own ghouls with pistol barrage he should not spam that... he should say that after killing the players only.
![image](https://user-images.githubusercontent.com/36106057/177836554-76259516-84b1-4fea-bfba-fdc6ebd9a37b.png)
also he is dropping the green winter hat without the event
![image](https://user-images.githubusercontent.com/36106057/177836658-dc032702-da94-4a73-af9b-66f22ef31cdf.png)

**### Important: about the dead friendly guards on the ground.**
Please keep mind that dead guards are supposed to be dead at god frey room i assume whom ever developed this didn't pay attention to having two sets of guards with same name/display ID and different entry ID so it wont interfere with earlier versions of them in the dungeon thats why by mistake he set state all of them dead
also by the look of it they are also reason players stay in combat bug in this dungeon
![image](https://user-images.githubusercontent.com/36106057/177842973-ea8a2188-8026-407d-aa35-9fa328fda8cc.png)

**Comment by MrTide** [comment]
I counldn't find any source on pistol barrage DPS which is 300 right now but i believe it should be 150 please if you found any information about this share it with us
![image](https://user-images.githubusercontent.com/36106057/177841129-7ed27ef3-0090-4eb0-883f-ee9d471133b0.png)

**Comment by Afgann** [comment]
fixed
