### ISSUE TITLE
[Dungeon] Stormwind stockade

### ISSUE THREAD

**Issue by MrTide** [SallyWhitemane/Maelstrom#534]
**Description:** This dungeon can be found at stormwind

**How to reproduce:** Rifle Commander Coe and stockade guards are missing lines when players enter the dungeon you can see it at start of this video https://www.youtube.com/watch?v=NQmxrFlgz6E

Riverpaw shamans have a long delay before start casting. (known issue)
![image](https://user-images.githubusercontent.com/36106057/178037783-586e407c-cf65-47a3-a265-b6788d2923b0.png)

**How it should work:** They should have their missing lines and Riverpaw shamans start casting without the delay

**Comment by Afgann** [comment]
fixed
