### ISSUE TITLE
[Dungeon] Blackfathom deeps 

### ISSUE THREAD

**Issue by MrTide** [SallyWhitemane/Maelstrom#536]
**Description:** this dungeon can be found at ashenvale

**How to reproduce:** blackfathom sea witch, Fallenroot hellcaller, Blindlight oracle and twilight aquamancer just stand in their place and wont engage in combat and takes a long time to start casting
![image](https://user-images.githubusercontent.com/36106057/178052388-5036a3ca-b3d8-41fb-ae5f-fee9a0373232.png)

Altar of the deep at the end of the dungeon dont work and wont give you buffs
![image](https://user-images.githubusercontent.com/36106057/178056745-644abc2e-c4a3-4647-84a2-3d6b0873e36f.png)
![image](https://user-images.githubusercontent.com/36106057/178056785-439995b8-d715-4a8b-9ff4-c8d0dd45d677.png)

NPC morridune is not supposed to spawn after killing Aku'mai boss he used to spawn for alliance players only and create a portal for them but he got removed at patch 4.0.3
![image](https://user-images.githubusercontent.com/36106057/178057103-7d80bcee-277a-4b25-8d8e-f55eb1d9d914.png)
https://wowpedia.fandom.com/wiki/Morridune

**Comment by Afgann** [comment]
fixed
