### ISSUE TITLE
[Dungeon] Scarlet monastery "Grave yard"

### ISSUE THREAD

**Issue by MrTide** [SallyWhitemane/Maelstrom#537]
**Description:** this dungeon can be found at tirisfal glades 

**How to reproduce:** Dark Ranger Velonara is missing instead alliance version Joseph the awakened is available which is wrong ... alliance version should be available for alliance side and horde version should be available for horde side (unless you wanna do it cross faction which you need to figure that out) so i can't turn in my quests or start quests. you can see her in this video (https://www.youtube.com/watch?v=1BafsEjWKdk)
![image](https://user-images.githubusercontent.com/36106057/178119410-33a85a27-9945-456a-8a98-547782a2db96.png)
also i don't think forsaken guards should be with joseph on alliance side there should be scarlet renegades instead
![image](https://user-images.githubusercontent.com/36106057/178119493-5ce09d41-2f6b-492f-b0c6-4f5b63c37a7d.png)

Scarlet Scryer takes a long time to start casting ( known issue)
![image](https://user-images.githubusercontent.com/36106057/178119583-2f4a4870-6d67-446a-be83-20896b5213d7.png)

Fallen champion is a rare NPC can be found at SMGY but looks like he is phased out and still can hit you i don't think its scripted properly
you can see its hitting me but i can't see it
![image](https://user-images.githubusercontent.com/36106057/178119799-21b14dd9-e33a-43b0-a022-9e3941608061.png)

once i turn the GM mode on i can see him
![image](https://user-images.githubusercontent.com/36106057/178119810-1bbac68d-4461-4d28-b1a7-179851e8576c.png)

**How it should work:** more info about the fallen champion here
https://wowpedia.fandom.com/wiki/Fallen_Champion
a run from 2011 horde side
https://www.youtube.com/watch?v=1BafsEjWKdk
alliance side 2010
https://www.youtube.com/watch?v=DGfgAlf09ZE

**Comment by Afgann** [comment]
fixed
