### ISSUE TITLE
[Dungeon] Scarlet monastery "Library"

### ISSUE THREAD

**Issue by MrTide** [SallyWhitemane/Maelstrom#538]
**Description:** This dungeon can be found at tirisfal glades 

**How to reproduce:** this dungeon also have Dark Ranger Velonara missing and instead alliance version Joseph the awakened is available which is wrong (similar issue https://github.com/SallyWhitemane/Maelstrom/issues/537 )
![image](https://user-images.githubusercontent.com/36106057/178119972-cfd18c4f-8611-4742-b2af-e3ea363b7d8c.png)
and on alliance side guards are missing as you can see in the image scarlet renegades are missing ( you can see them in this video https://www.youtube.com/watch?v=M0amOL_8ytI)
![image](https://user-images.githubusercontent.com/36106057/178120009-e788d181-1a0c-4486-a6e8-bcaa603075a1.png)

Scarlet adept take long time to start casting (known issue)
![image](https://user-images.githubusercontent.com/36106057/178120143-6d838e49-4d34-4f07-ad94-c1efd9a20d39.png)
Scarlet beastmaster takes long time to start shooting you with their gun (known issue)
![image](https://user-images.githubusercontent.com/36106057/178120162-b54a16b7-0446-47e5-9b34-69edc56a60a7.png)
Scarlet diviner takes long time to start casting
![image](https://user-images.githubusercontent.com/36106057/178120609-2e976672-8a0d-40c1-ac36-0658a7f52f59.png)

Scarlet beastmaster pets which is called scarlet tracking hound is not following the master movements at start of the dungeon and also goes through walls 
![image](https://user-images.githubusercontent.com/36106057/178120129-5123b821-750c-4934-aac1-9c740be20fb0.png)

Houndmaster Loksey is summoning an extra dog which is called "scarlet Hound" with a classic era model i don't think such thing should be happening according to this evidence " https://youtu.be/M0amOL_8ytI?t=125 there are no extra hounds in this video as you can see 

This particular NPC is missing lines as you can see in this video https://youtu.be/M0amOL_8ytI?t=201
![image](https://user-images.githubusercontent.com/36106057/178120558-840edd2a-9030-44c4-8fa7-516b844a1bf9.png)

**How it should work:**
full dungeon run : https://www.youtube.com/watch?v=M0amOL_8ytI
Dark Ranger Velonara : https://cata-twinhead.twinstar.cz/?search=Dark+Ranger+Velonara

**Comment by Afgann** [comment]
fixed
