### ISSUE TITLE
[Dungeon] Scarlet monastery "Cathedral" 

### ISSUE THREAD

**Issue by MrTide** [SallyWhitemane/Maelstrom#539]
**Description:** This dungeon can be found at Tirisfal Glades 

**How to reproduce:** Forsaken Royal Dreadguards are not lined up and Dark Ranger Velonara is at wrong location it should be like this video below for horde side : https://youtu.be/cXIUTVgLcWQ?t=3
![image](https://user-images.githubusercontent.com/36106057/178121198-cba3eb29-4c77-4220-afb9-65d81c8a0957.png)
some alliance scarlet renegades are missing (left side) check this video https://youtu.be/vtaXub7Wj4w?t=39

![image](https://user-images.githubusercontent.com/36106057/178122237-e6b2dcbb-c074-4be6-9da8-d025712e2a9f.png)
Joseph the insane should not be in available in horde run  https://youtu.be/cXIUTVgLcWQ?t=46
![image](https://user-images.githubusercontent.com/36106057/178122259-e9dd7695-1b67-4032-92d6-57aef42f7d41.png)

There is one Forsaken Flesh rippers missing and also misplaced you can see their location in this video https://youtu.be/cXIUTVgLcWQ?t=40
![image](https://user-images.githubusercontent.com/36106057/178121840-5cc61973-6b58-460c-9752-94a66f0e8aa6.png)

Scarlet members/mobs have missing lines its shown in this video: https://youtu.be/cXIUTVgLcWQ?t=168
![image](https://user-images.githubusercontent.com/36106057/178121335-5d1dfc14-e577-41e8-9fb8-1d108eeace8e.png)
High inquisitor fairbanks is on dead standstate which is wrong according to this video https://youtu.be/cXIUTVgLcWQ?t=225 the door also should be accessed through a torch but its not a big issue
![image](https://user-images.githubusercontent.com/36106057/178121398-78d55771-c504-403e-bec2-0531f36db88b.png)
If you have dot high inquisitor whitemane she will die and wont be able to finish her script so she can't revive mograine and just dies https://github.com/SallyWhitemane/Maelstrom/issues/165
![image](https://user-images.githubusercontent.com/36106057/178121715-f9e70036-58ad-4c65-bd56-55e1d3500a23.png)
also after getting revived none of them hit you with auto attack only spells and mograine wont move 
![image](https://user-images.githubusercontent.com/36106057/178121776-01b6fef7-bcde-459b-88c5-bb613cb3762c.png)

also door behind you wont close up after you start the fight

![image](https://user-images.githubusercontent.com/36106057/178121799-b80ad4aa-08af-4093-875a-40302a959664.png)

also i didnt see him casting divine shield when he is low like the video below
https://youtu.be/cXIUTVgLcWQ?t=335

**Comment by Afgann** [comment]
fixed

**Comment by MrTide** [comment]
i think you added everything twice for horde side by mistake @Afgann 
they are stacked up inside each other ... some even more than twice 

![image](https://user-images.githubusercontent.com/36106057/179047258-60ea41e7-0283-4bf9-85cb-8dc0bd4a3c7d.png)
![image](https://user-images.githubusercontent.com/36106057/179052417-6c28bc00-59e9-4356-a16d-b9f3bec98aac.png)
![image](https://user-images.githubusercontent.com/36106057/179052436-a6393934-e130-4647-8125-cc19093cb856.png)

**Comment by Afgann** [comment]
Issue should be fixed after update @MrTide
