### ISSUE TITLE
[Dungeon] Scarlet monastery "Armory" 

### ISSUE THREAD

**Issue by MrTide** [SallyWhitemane/Maelstrom#540]
**Description:** This dungeon can be found at tirisfal glades 

**How to reproduce:** Joseph the crazed is missing two of his guards (scarlet renegades) and there should not be any scarlet mob at this entrance in front of her like this video https://youtu.be/27LurkOO5HY?t=11
![image](https://user-images.githubusercontent.com/36106057/178122704-a774299d-7f11-40f4-bfdf-13b8a1e1d62c.png)

Joseph the crazed should not be in horde runs and scarlet soldiers should not be standing in the entrance in front of her in horde side as well also some guards are missing on the other side please check this video : https://youtu.be/2RdL0c1i1_o?t=36
![image](https://user-images.githubusercontent.com/36106057/178122773-96f19990-b375-4a11-a263-4679afc0661a.png)

Scarlet conjuror takes a long time to start casting (known issue)
![image](https://user-images.githubusercontent.com/36106057/178122804-fb9a27a0-ab38-4874-b653-9ac18780e5a5.png)

Scarlet evoker takes a long time to start casting

![image](https://user-images.githubusercontent.com/36106057/178122865-49794bb6-0917-442a-b64d-2e580e45017e.png)

after killing herod all the scarlet trainee run to you inside each other they should come in lines https://youtu.be/2RdL0c1i1_o?t=174
![image](https://user-images.githubusercontent.com/36106057/178123000-b1d56468-c5dc-418a-9a98-90f18ca46645.png)
![image](https://user-images.githubusercontent.com/36106057/178123230-c4bc6317-a2f5-4f0e-8fb5-ca355ae26c10.png)

**Comment by Afgann** [comment]
fixed
