### ISSUE TITLE
[NPC] Mobs in front of scarlet monastery entrance 

### ISSUE THREAD

**Issue by MrTide** [SallyWhitemane/Maelstrom#541]
**Description:** These creatures can be found at tirisfal glades 

**How to reproduce:** Scarlet sentry, scarlet disciple, scarlet augur they all got 50 sec respawn timer (you can see they are respawning too fast after killing them) even tho its listed as full 10min i would assume it would cause issues with dynamic respawns and such in long term its better to correct their respawn timers 
![image](https://user-images.githubusercontent.com/36106057/178123442-36315fe9-d1a6-4836-affa-2a8a298096b5.png)
![image](https://user-images.githubusercontent.com/36106057/178123449-d40227bc-2dff-40cd-b749-8abb0d167503.png)
![image](https://user-images.githubusercontent.com/36106057/178123465-e69ca799-593b-4718-986c-df6c4b213b2d.png)

**How it should work:** they should have 10min respawn timer

**Comment by ghost** [comment]
Everything works okay.

**Comment by MrTide** [comment]
afgann fixed it idk why unassigned it probably miss click
