### ISSUE TITLE
[NPC] Syndicate Magus only attacks if in line of sight, won't run to you

### ISSUE THREAD

**Issue by phonkala** [SallyWhitemane/Maelstrom#543]
**Description:**
As the title says. Tested this many times, they do cast when you are in line of sight, but when you step behind a wall, they just stop attacking and stand still in combat.  They should run to a place where they can see you and cast.

Doing nothing here, just standing still for 10sec+:
![WoWScrnShot_071022_114745](https://user-images.githubusercontent.com/43609330/178138056-d8e4f4b9-db80-4654-aa04-931ea7a797a9.jpg)

Stepped to line of sight, started casting:
![WoWScrnShot_071022_114748](https://user-images.githubusercontent.com/43609330/178138063-cddbdfc7-9d43-4499-87e1-e5f7f22f380b.jpg)

**Comment by Afgann** [comment]
fixed
