### ISSUE TITLE
[Dungeon] Maraudon

### ISSUE THREAD

**Issue by MrTide** [SallyWhitemane/Maelstrom#544]
**Description:** this dungeon can be found at Desolace

**How to reproduce:** Poison Sprite takes a long time to start casting (known issue)
![image](https://user-images.githubusercontent.com/36106057/178151624-dd4e066a-0f90-4a51-b0fb-9e8f7f01504b.png)
Celebrian Dryad take a long time before start hitting you (known issue)
![image](https://user-images.githubusercontent.com/36106057/178152073-843ba1ad-d983-4360-8eb0-dbd192eaf436.png)
Primordial behemoth takes a long time to start attacking (known issue)
![image](https://user-images.githubusercontent.com/36106057/178152521-5238a8ab-7849-4199-9d73-8d717573189a.png)
Theradrim Guardian: they are mostly missing way points or have broken ones and their Theradrim shardlings are not following them you can see them in these videos moving around like in a pack 
https://youtu.be/foGlLZofce4?t=354
https://youtu.be/foGlLZofce4?t=114
![image](https://user-images.githubusercontent.com/36106057/178152789-51301350-b5c5-4ccc-aae1-d08b31fbf4a4.png)
![image](https://user-images.githubusercontent.com/36106057/178152798-d37c2475-ea6a-474e-b2e2-6e465ffb7199.png)

Thessala Hydra pathing issues inside water at different lvls of water

https://user-images.githubusercontent.com/36106057/178153263-d5637514-81cf-4262-8e77-657c564d9dfc.mp4

https://user-images.githubusercontent.com/36106057/178153267-1e775fb4-632b-4405-b043-dde95b28680b.mp4

**How it should work:** creatures should start hitting/casting and they should have not a long delay before doing so and shardlings should follow the pack and they should not go through the walls, and Thessala Hydra should attack the player no matter what and should not have weird pathing issues

**Comment by Afgann** [comment]
fixed
