### ISSUE TITLE
[Dungeon][BRD] New list of bugs from Blackrock Depths

### ISSUE THREAD

**Issue by phonkala** [SallyWhitemane/Maelstrom#546]
**Description:**
Some of these were "fixed" earlier (https://github.com/SallyWhitemane/Maelstrom/issues/152), but a bit wrong:

- Grim Guzzler area: In the linked issue, I had this: "Patrons don't turn hostile after killing Plugger Spazzring, they should.". Now they were hostile right away when we entered the area. They should become hostile ONLY AFTER Plugger Spazzring is killed.
- Grim Guzzler area: Ribbly Screwspigot was nowhere in the room this time. He is one NPC that you talk to, and then he and his fellows turn hostile. He is also part of a quest so he needs to be there. This time he just wasn't there at all.
- Grim Guzzler area: This time destroying the kegs did start the boss event like it should. However, the summoned Blackbreath Crony was unattackable and also didn't attack us, and kept following us as hostile.
- Summoner's Tomb: You should kill all the 7 bosses before the door to next room opens. Some of the 7 bosses (the furthest ones) never aggroed us, and the door opened without killing them. They should aggro us no matter where we are in the room, and the door should not open before all are killed.

**Comment by MrTide** [comment]
Detailed info can be found here
https://github.com/SallyWhitemane/Maelstrom/issues/572
