### ISSUE TITLE
[Dungeon] Dire maul  "Capital Gardens"

### ISSUE THREAD

**Issue by MrTide** [SallyWhitemane/Maelstrom#550]
**Description:** this dungeon can be found at feralas

**How to reproduce:** ancient equine spirit is supposed to spawn after killing the boss tendris warpwood while he is here from the start it should be like this video: https://youtu.be/fm64c4LqQUY?t=350 
![image](https://user-images.githubusercontent.com/36106057/178318434-08467fa8-dd96-4f22-a4c6-e60fe1522b03.png)

Eldreth apparition takes a long time before start casting
![image](https://user-images.githubusercontent.com/36106057/178318807-d8b48161-7ab2-4d7a-bf7b-fd6f46ef60fb.png)

Magister kalendris takes a long time before engaging in combat
![image](https://user-images.githubusercontent.com/36106057/178319038-f93933b6-4c5a-42c0-ac19-375f6fbaf2d5.png)

Diremaul crystals should have 4 Guardians instead of two like these videos : https://youtu.be/fm64c4LqQUY?t=709
![image](https://user-images.githubusercontent.com/36106057/178319918-cd87970f-7d38-48bc-abb0-ae5f5bc6e322.png)

Illyanna ravenoak should patrol with her pet ferra .. here they dont go together .. you can see them going together in the background here https://youtu.be/fm64c4LqQUY?t=894
also their attack speed i believe are way too fast and they hit hard as well.. you can see the video of their fight here : https://youtu.be/An_Z-RXbGN0?t=512
![image](https://user-images.githubusercontent.com/36106057/178320881-0d97ce0a-098a-4e7c-beb2-d79688041364.png)
![image](https://user-images.githubusercontent.com/36106057/178320186-4ad14ea0-16b1-4220-87e3-be1622f4de14.png)

arcane torrent and arcane feedback patrols and some patroling Residual Monstrosity  are missing at Prison of immol'thar area you can see players fighting with them in this video: https://youtu.be/fm64c4LqQUY?t=1072
https://cata-twinhead.twinstar.cz/?npc=14399
https://cata-twinhead.twinstar.cz/?npc=14400
https://cata-twinhead.twinstar.cz/?npc=11484
![image](https://user-images.githubusercontent.com/36106057/178321919-a7c681ae-a7a5-45c5-87a7-e3c84f6dc88f.png)

The door after killing immol'thar  is missing https://youtu.be/fm64c4LqQUY?t=1420
![image](https://user-images.githubusercontent.com/36106057/178323153-b1b096dd-c8f6-41c4-a7a3-32f5ec8c6349.png)

Shen'dralar zealot : Should not get dagger icon which means killing these creatures here
you can see this in this video: https://youtu.be/fm64c4LqQUY?t=1428
![image](https://user-images.githubusercontent.com/36106057/178323464-5d3c22bb-e537-4017-9e8d-dc36b9612160.png)
![image](https://user-images.githubusercontent.com/36106057/178323718-940248ff-1da8-465e-8622-905ec6ef11e8.png)

**Comment by Afgann** [comment]
fixed
