### ISSUE TITLE
[Raid][Generic] HP scaling of low level raid bosses seems bugged

### ISSUE THREAD

**Issue by phonkala** [SallyWhitemane/Maelstrom#552]
Was going to do some testing in Molten Core, but health of "low level" (60) raid bosses seems way over the top. I assume this is because raid bosses are always "skull level", be it lower level raid or not. Bosses should still not scale their stats besides the intended level in (low level) raids, for example in Molten Core the bosses should not exceed their intended level (63) stats. Their level "scales" yes (as raid bosses are always 3 levels higher than player, thus the skull icon and not some static level), but not the stats.

From MC:
Magmadar has 1189M hp, it should have 413k hp: https://cata-twinhead.twinstar.cz/pqykaszaz.html?npc=11982
Lucifron has 1859M hp, it should have 176k hp: https://cata-twinhead.twinstar.cz/?npc=12118
etc.

Some video of rogue soloing MC in 2011: https://www.youtube.com/watch?v=hts_Cx1qu8w

Hopefully this gets fixed quick to do some actual testing of the raids, with current state can't even kill the bosses.

**Comment by phonkala** [comment]
Also had some chat in Discord with Xecc, he had a screenshot from maybe half a year back when the boss hp was still working correctly on the PTR: https://user-images.githubusercontent.com/66841484/158037729-300004fd-5536-4d6a-8741-e20825d65008.jpg

**Comment by phonkala** [comment]
Oh forgot to mention, I was level 85 when testing. This should not scale lower level raid boss stats past their intended level, even if the "visually seen level" is still "skull".

**Comment by ghost** [comment]
E.g. http://web.archive.org/web/20110625094651/https://www.wowhead.com/npc=11982
Wowhead from 2011 says 826k.

**Comment by phonkala** [comment]
Ye seems that is correct value for Magmadar, here is the last snapshot before MoP release: https://web.archive.org/web/20120908071235/https://www.wowhead.com/npc=11982

But that was not the main point of this issue. It was that the current values are just absurdly off. 400k or 800k would still be easily killable, but 1189M is like 1500 times that.

I think there is also some screenshot in Discord that some boss in MC is hitting over 76k damage, that too is absurdly high, so was guessing it's all the stats that are scaling wrongly based on level.

**Comment by ghost** [comment]
Fix is on the way.
