### ISSUE TITLE
[Raid][MC][NPC] Core Hounds respawn even if whole pack is dead

### ISSUE THREAD

**Issue by phonkala** [SallyWhitemane/Maelstrom#553]
Was starting some Molten Core testing, but first issue I ran was that the Core Hounds kept resurrecting even if I killed the whole pack. They should only resurrect after 10 sec, if they have some other hounds alive in their pack.

Killed a full pack of Core Hounds:
![WoWScrnShot_071222_174809](https://user-images.githubusercontent.com/43609330/178526471-44c4ad7e-d125-4706-a1ec-81adb4c04126.jpg)

They still keep resurrecting:
![WoWScrnShot_071222_174814](https://user-images.githubusercontent.com/43609330/178526555-a9b729bd-1653-44be-9c65-eee828d8b2d3.jpg)

Tested this multiple times, they kept ressing every time even when I changed the pack I was killing.

Some rogue soloing full MC in 2011: https://www.youtube.com/watch?v=hts_Cx1qu8w
Here the packs work as they should.

**Comment by Afgann** [comment]
fixed
