### ISSUE TITLE
[Dungeon][UBRS] Warchief Rend Blackhand missing whole boss event rp

### ISSUE THREAD

**Issue by phonkala** [SallyWhitemane/Maelstrom#555]
In upper Blackrock Spire, I jumped down to the "arena" where the Rend Blackhand event should be done. Jumping in should start the rp event, where there are multiple waves of whelps coming from the gate that opens and closes, and after all the waves Gyth (the dragon) should come first and then Rend appears.

Currently, there is no event, Rend just ran to me through gate and I was able to kill him before any waves of whelps. Also Gyth never appeared. Rend should also be unattackable before he actually appears, but I was able to tag him when I jumped down into the room.

From youtube, working event: 
Start of event: https://www.youtube.com/watch?v=A0hntkg4Vz8
Gyth and Rend: https://www.youtube.com/watch?v=WOCoCYLdBRM

**Comment by ghost** [comment]
![obraz_2022-09-12_115937104](https://user-images.githubusercontent.com/80540499/189626597-f955f411-36db-4fc6-a6ae-88436ce4c3ab.png)
Everything works okay.
