### ISSUE TITLE
[Dungeon] Scholomance

### ISSUE THREAD

**Issue by MrTide** [SallyWhitemane/Maelstrom#556]
**Description:** This dungeon can be found at western plaguelands 

**How to reproduce:** Scholomance Neophyte takes a long delay before start casting
![image](https://user-images.githubusercontent.com/36106057/178514969-ff756109-7e28-4030-a306-1fe8c19076f8.png)

Scholomance Necrolyte takes a long time before start casting.
![image](https://user-images.githubusercontent.com/36106057/178520279-d1876c46-792b-4b35-a79d-185bfa02ff8a.png)

Kirtonos the herald flys in the air in his humanoid form
![image](https://user-images.githubusercontent.com/36106057/178520857-c08fbbe6-8677-411b-941c-73ba4be7a4a0.png)

Scholomance adept takes a long delay before start casting
![image](https://user-images.githubusercontent.com/36106057/178521442-d8bb8adc-2209-40c3-b051-1d53ae5e562d.png)

Rattlegore still drops viewing room key it was removed at patch 4.0.3
https://wowpedia.fandom.com/wiki/Viewing_Room_Key
![image](https://user-images.githubusercontent.com/36106057/178524159-9a9be43c-d2d5-4c7b-bbf4-6f24dc0a6a6c.png)

Vectus event is not scripted properly he is also missing lines you can't use Alexi's Gambit in this room (its for the quest  [Alexi's Gambit] ) to turn the npcs around to skeletons etc etc it should work like this video 
https://youtu.be/j7d31aHvEkA?t=600
you are not supposed to be able to kill these guys without the quest https://youtu.be/VAWFsYprkhk?t=707 check this video player is just running around and unable to fight them
also marduk blackpool is casting an aura on you called defiling aura and keeps you incombat forever if you decide to not fight them ... he should only do that if you decide to fight him
![image](https://user-images.githubusercontent.com/36106057/178526892-534cb02d-4731-45b2-8052-be24d3656790.png)

Quest  "Doctor Theolen Krastinov, the butcher" by the look of it quest is not fully scripted here you dont need to burn the corpses while you should.. two objectives are missing https://wowpedia.fandom.com/wiki/Doctor_Theolen_Krastinov,_the_Butcher
please check this video: https://youtu.be/j7d31aHvEkA?t=1065

Lord Alexei barov casting two immolates instead of one with different damages one deals over 400 and other one 12 there should be only one immolate... also i dont think he is casting Unholy Aura
https://wowpedia.fandom.com/wiki/Lord_Alexei_Barov
![image](https://user-images.githubusercontent.com/36106057/178536202-dadebb08-8116-4b17-a9a6-403302ed3269.png)

Lady illucia barov is not casting her spells instead she casts something called arcane devastation and arcane resonance 
you can see her spells here : https://wowpedia.fandom.com/wiki/Lady_Illucia_Barov
full fight https://youtu.be/j7d31aHvEkA?t=1369
![image](https://user-images.githubusercontent.com/36106057/178538952-14bae2b0-8250-4553-9c0d-05c71f916b5b.png)
![image](https://user-images.githubusercontent.com/36106057/178539418-8f431af6-e4a5-4d98-93d0-ad4d777e9cb1.png)

after finishing the quests two darkmaster grandling spawns and also hits super hard 
there should be only one full fight here : https://youtu.be/j7d31aHvEkA?t=1562
![image](https://user-images.githubusercontent.com/36106057/178541370-bfaea15c-3221-40c5-b59f-79f52ba60794.png)
![image](https://user-images.githubusercontent.com/36106057/178541533-a906a22f-6da7-4e8e-a3fd-3ce04737fc14.png)

**Comment by Afgann** [comment]
fixed
