### ISSUE TITLE
[Dungeon][UBRS] General Drakkisath: Shadowmeld reseted boss, but still kept me in combat

### ISSUE THREAD

**Issue by phonkala** [SallyWhitemane/Maelstrom#557]
So I went to fight General Drakkisath, the last boss in upper Blackrock Spire. I accidentally pulled some trash packs in the room, continued to pull the boss and then decided to instead reset the boss so I don't have adds on me, just to keep things bit more clear. I used Shadowmeld, the boss disappeared (don't know if he should _disappear_ or just run to his original location), it's 2 adds ran to their original locations (they did not disappear) and basicly I managed to reset it all.

However, I was then stuck in combat for some reason. After a while General Drakkisath appeared again and I was able to kill him, but the issue here was the combat part. I was not able to stealth etc. Could maybe have something to do with the fact that the boss disappeared instead of just running back to his original spot.

**Comment by ghost** [comment]
Cannot reproduce it. No combat after Shadowmeld use on boss.
