### ISSUE TITLE
[Dungeon][URBS] The Beast "skull level", other bosses just "normal" level (58-63 etc)

### ISSUE THREAD

**Issue by phonkala** [SallyWhitemane/Maelstrom#558]
I did my first run through upper Blackrock Spire, mostly wanted to see if it's completeable. It was, but buggy and one thing I thought I'll report here separately: For some reason, all other bosses in the dungeon had "normal level" (the level was actually visible in their portrait), but The Beast was "skull level". He did have correct HP etc though. So I was just left thinking, either all the bosses there should have "normal level", or all be "skull level".

**Comment by phonkala** [comment]
Actually, based on this video from 2011, The Beast should be level 60 (and not "skull lvl"): https://youtu.be/WOCoCYLdBRM?list=PL2D1B8C6C35F01AE7&t=219

**Comment by MrTide** [comment]
yes its true i don't think it will cause issues tho.. up to developers its still a lvl 60 creature
![image](https://user-images.githubusercontent.com/36106057/179037229-360254b9-af24-493c-8168-31360586a767.png)

**Comment by Afgann** [comment]
fixed
