### ISSUE TITLE
[Dungeon] Zul'Farrak

### ISSUE THREAD

**Issue by MrTide** [SallyWhitemane/Maelstrom#559]
**Description:** This dungeon can be found at tanaris

**How to reproduce:** Sandfury shadowcaster takes a long delay before start casting
![image](https://user-images.githubusercontent.com/36106057/178544290-d8240204-8f5f-4508-93a0-6d54bca2d604.png)

Sandfury shadowhunter takes a long delay before start shooting
![image](https://user-images.githubusercontent.com/36106057/178544770-064a1c6a-3401-450e-abf7-03607495f3b7.png)

Theka the martyr is missing waypoints he should be patrolling in this area while he is just standing in place
more info here: https://youtu.be/g-kIg-wowlw?t=440
![image](https://user-images.githubusercontent.com/36106057/178545193-28b0c5a0-4f37-48ae-8fdb-7903633f7e79.png)

the altar event friendly creatures hit some creatures that are not visible to the players  
i am guessing they are under ground
![image](https://user-images.githubusercontent.com/36106057/178546747-6f5b34b0-d30c-438c-8b44-25fb1c653a5d.png)
also by the look of it they are missing some lines .. they kept saying placeholder 1
![image](https://user-images.githubusercontent.com/36106057/178547235-81c2a592-bbd6-4b42-a1d3-6d46b34eb85c.png)

Gahz'rilla boss casts an spell which causes you to get kicked in the air but the problem is once you are in the air boss sometimes start to heal to the max he is not supposed to regen .... also if you bang its gong whole room will come at you i couldn't find any cataclysm video which says thats correct as you can see in none of these videos they do that
https://youtu.be/YbLVxgI2w2M?t=237
https://youtu.be/g-kIg-wowlw?t=1144
![image](https://user-images.githubusercontent.com/36106057/178549900-e5150e1e-1f60-4836-a918-831afa6cc05a.png)

**Comment by Afgann** [comment]
fixed
