### ISSUE TITLE
[Dungeon] Stratholme "Main Gate"

### ISSUE THREAD

**Issue by MrTide** [SallyWhitemane/Maelstrom#560]
**Description:** this dungeon can be found at eastern plaguelands 

**How to reproduce:**  there are no friendly npcs available for the players to turn in quests or take quests (looks like they are phased out for both horde and alliance)
horde: https://www.youtube.com/watch?v=6aeJMiwyDiI
alliance: https://youtu.be/9OIcBvC7orw?t=22
Note: argent crusaders guards are supposed to be appearing after killing the end boss that part works as intended but the quest givers should be there at start to give you quests they are simply not here. 
Note: the quest givers from start of the dungeon also appear after finishing the dungeon at start and end of the dungeon (please try to test after applying your changes and kill the end boss balnazzar to make sure everything working as intended)
![image](https://user-images.githubusercontent.com/36106057/178554289-882cdc2b-4888-4d88-92b0-863dce1232a1.png)
![image](https://user-images.githubusercontent.com/36106057/178554379-f446c7f1-ed06-493d-a7d5-0136c6fe7ea6.png)

Skeletal Guardians, Risen Sorcerer, Risen conjuror and Risen priest have a long delay before start casting

plagued rats are not running at you so you get stuck its a small mini event happening in this dungeon : https://youtu.be/9OIcBvC7orw?t=554
![image](https://user-images.githubusercontent.com/36106057/178555878-4498ec56-ac10-40e5-b4f8-5b7353b199b2.png)
![image](https://user-images.githubusercontent.com/36106057/178555902-a291dec4-acf6-4937-b72e-c4740168db59.png)

Timmy the cruel is missing in this dungeon (by the look of it he spawns after killing the balnazzar which is wrong argent crusaders kill him before you can get to him most of the time) you can see him in this video : https://youtu.be/9OIcBvC7orw?t=828
https://youtu.be/6aeJMiwyDiI?t=576
there is nothing special anymore he just exists there.
![image](https://user-images.githubusercontent.com/36106057/178557136-4486fb89-bceb-46e0-85d1-e8c10ab5cc87.png)
![image](https://user-images.githubusercontent.com/36106057/178557241-904e8ed8-3399-431b-9b38-0c5c586e2f0c.png)

after killing the end boss friendly npcs should be appearing .. they do but they are missing some waypoints and lines more info in this video https://youtu.be/6aeJMiwyDiI?t=2000 
here they just spawn outside of the room
![image](https://user-images.githubusercontent.com/36106057/178562356-b12e572b-afc2-49f7-8b2d-d183f2c4a96a.png)

**Comment by Afgann** [comment]
fixed
