### ISSUE TITLE
[Dungeon] Stratholme " service entrance"

### ISSUE THREAD

**Issue by MrTide** [SallyWhitemane/Maelstrom#561]
**Description:** This dungeon can be found at eastern plaguelands

**How to reproduce:** Friendly npcs at start of the dungeon most of them are missing both horde and alliance side
Note: they spawn after finishing the dungeon instead. please don't confuse these quest givers with argent crusaders 
horde: https://youtu.be/RqomyGyA-sE?t=176
alliance: https://youtu.be/TKqksw8Po7g?t=139
![image](https://user-images.githubusercontent.com/36106057/178575528-83ba2e8c-e48b-403c-8254-a3c42ec7079f.png)
![image](https://user-images.githubusercontent.com/36106057/178575992-f6f62113-0756-4681-87d2-ca63935538f5.png)

Shrieking banshee, Thuzadin shadowcaster takes a long time to start casting

Baroness Anastari is completely missing her spells 
more info here : https://wowpedia.fandom.com/wiki/Baroness_Anastari
her fight : https://youtu.be/TKqksw8Po7g?t=623

Magistrate barthilas is misplace he should be far back after finishing his script https://youtu.be/TKqksw8Po7g?t=1641 .. the problem is that having to kill more elite mobs next to him makes it hard to kill him
![image](https://user-images.githubusercontent.com/36106057/178578697-3d6aafd9-bdec-465f-8f37-3ac03606d573.png)

every large solid chest i have found in this dungeon have been empty
![image](https://user-images.githubusercontent.com/36106057/178579537-5a9ab77e-cd01-4645-920c-9fb41983db7d.png)
![image](https://user-images.githubusercontent.com/36106057/178579549-4e1f99c5-5c66-4708-96ff-76b91f2f1e1c.png)

Lord aurius Rivendare aura hits you even tho you haven't engaged in combat with him .. it should not happen
![image](https://user-images.githubusercontent.com/36106057/178580915-8fbfe0db-19db-4d42-89cd-3ca13558c0ff.png)

if you wipe on Ramstein the gorger you can't finish the dungeon anymore because he goes back inside and you can't pull him through the locked door anymore.
Full fight: https://youtu.be/TKqksw8Po7g?t=1980

**Comment by Afgann** [comment]
fixed
