### ISSUE TITLE
[Raid][MC][NPC] Baron Geddon already dead, follows you around as corpse

### ISSUE THREAD

**Issue by phonkala** [SallyWhitemane/Maelstrom#563]
Title pretty much describes it all. In Molten Core, Baron Geddon was already dead when I entered, but it keeps moving as corpse and after pulling it, it also keeps attacking as corpse. It is targetable, but I can't attack it (as it's dead already).

![WoWScrnShot_071322_090558](https://user-images.githubusercontent.com/43609330/178662709-5d869191-3ec3-49c4-aacf-355cd2ee0f80.jpg)
![WoWScrnShot_071322_090849](https://user-images.githubusercontent.com/43609330/178662717-bf5daf6a-8c21-4b99-9687-b4c4f80dbf41.jpg)

Also, interestingly it's Inferno ability is able to damage me through Divine Shield (I'm using the permanent "dev version" of it), which should be immunity to all damage. Pallys might not like this :)

**Comment by Afgann** [comment]
fixed
