### ISSUE TITLE
[Raid][MC][NPC] Sulfuron Harbinger already dead, follows you around as corpse

### ISSUE THREAD

**Issue by phonkala** [SallyWhitemane/Maelstrom#564]
Same issue than https://github.com/SallyWhitemane/Maelstrom/issues/563 but this time with Sulfuron Harbinger.

![WoWScrnShot_071322_091306](https://user-images.githubusercontent.com/43609330/178663262-c5557798-3ecb-41d2-b771-806e8ee1b462.jpg)

**Comment by Afgann** [comment]
fixed
