### ISSUE TITLE
[Dungeon][URBS] First room mobs reset after pull

### ISSUE THREAD

**Issue by phonkala** [SallyWhitemane/Maelstrom#566]
In upper Blackrock Spire, you need to kill all the mobs inside the whole first room to open door to next part. As it is a dungeon, mobs pulled should not reset themselves. However, in this room some mobs do run back a while after pulling, if you run too far or just don't attack. This should not happen inside any dungeon.

**Comment by MrTide** [comment]
I Couldnt reproduce this .. what lvl were you ?

**Comment by ghost** [comment]
Cannot reproduce it as well.
