### ISSUE TITLE
[Dungeon][URBS] The Beast keeps reseting if knockback throws me to wall

### ISSUE THREAD

**Issue by phonkala** [SallyWhitemane/Maelstrom#567]
Was fighting The Beast and noticed that if you position yourself to about middle of the room, back facing towards wall, Beasts knockback throws you high against the wall and the boss resets. This doesn't happen if you are close to wall, or if you are just in open area so that you land back on the ground without touching any wall in flight.

Position yourself around the middle, back facing wall:
![WoWScrnShot_071322_094827](https://user-images.githubusercontent.com/43609330/178669695-8cd5684f-00da-4f09-8cf5-159d41fea5c0.jpg)

Knockback sends you to hit wall high up, and boss resets while you are still in air:
![WoWScrnShot_071322_094831](https://user-images.githubusercontent.com/43609330/178669813-92e8cdfc-14c2-4ee4-8776-64a2582c3b86.jpg)

**Comment by Afgann** [comment]
fixed
