### ISSUE TITLE
[Dungeon] "Lower" Blackrock spire 

### ISSUE THREAD

**Issue by MrTide** [SallyWhitemane/Maelstrom#574]
**Description:** this dungeon can be found at burning steps

**How to reproduce:** 
Acride <Scarshield Legion> Doesn't exist at all you can even see the quest marker on mini map but he doesn't exist in this dungeon ... instead of him two scarshield inflitrator exist which is wrong (it used to be like that in classic this is cataclysm)
even quest says find acride
https://www.wowhead.com/npc=10299/acride#comments:id=1621260
https://cata-twinhead.twinstar.cz/?npc=10299
you can see him this video : https://youtu.be/uLeZJFwdqfY?t=39
![image](https://user-images.githubusercontent.com/36106057/179023494-74a56a74-318e-46bb-bd28-1cc6f33f6170.png)
![image](https://user-images.githubusercontent.com/36106057/179022337-ec75bf86-f672-4a80-af92-bf43d0073f98.png)
![image](https://user-images.githubusercontent.com/36106057/179022590-868cd0c5-97eb-4c04-814e-1170d7ab99f8.png)

Firebrand invoker, firebrand darkweaver, smolderthorn seer, smolderthorn mystic, smolderthorn headhunter, smolderthorn axe thrower, Scarshield warlock, Spirestone ogre magus, bloodaxe evoker, bloodaxe summoner, Chromatic whelp  takes a long delay before start casting/attacking, 

Scarshield warlock opens a portal which allows multiple creatures come through but the problem is that portal wont close up after killing the warlock.. and there is a rare spawn which comes through that portal and it happens every time you try to kill a warlock it should be a rare spawn not on every portal it should happen occasionally ( honestly every rare creature i have found in any dungeon so far all of them were there .. there was nothing rare about them i don't think the system related to these rare spawns is working properly)
Video of the warlock and portal despawning after killing him : https://youtu.be/H7h9WL3IOM8?t=325
https://wowpedia.fandom.com/wiki/Burning_Felguard
Burning fel guard is a random spawn from a warlock portal he should not exist in a random location by himself
![image](https://user-images.githubusercontent.com/36106057/179018467-449d79cb-cdea-4d32-91f8-f760c182f8f8.png)

Bannok Grimaxe is not casting his whirl wind ability (might be related that i was trying to kill him solo but still worth to check) 
https://cata-twinhead.twinstar.cz/?npc=9596#abilities

Urok doomhowl event is not scripted at all there are no bones no heads nothing .. also no pikes on the wall
https://wowpedia.fandom.com/wiki/Omokk%27s_Head
Pikes https://youtu.be/LtcUepHZWYU?t=63
full event: https://youtu.be/LtcUepHZWYU?t=442
Video from cataclysm : https://youtu.be/0Vw4Hm41aC0?t=26 players wont do the event but you can see boss is not there and pile of bones are also there 
Comment from 4.3.4 patch https://www.wowhead.com/npc=10584/urok-doomhowl#comments:id=1668036
![image](https://user-images.githubusercontent.com/36106057/179017115-269f24f8-2171-4e7a-a532-4f58cb21f168.png)
![image](https://user-images.githubusercontent.com/36106057/179016057-60e5157c-94cd-4697-a1bc-db6cbdd2e3ce.png)
![image](https://user-images.githubusercontent.com/36106057/179015886-40b4d9e7-bf1c-4ccb-b9ea-fefef88c2a75.png)

Gizrul the Slavener is missing all of his spells ...
https://wowpedia.fandom.com/wiki/Gizrul_the_Slavener

**Comment by ghost** [comment]
Fixed.
