### ISSUE TITLE
Lumbering Oaf does not reset properly on wipe

### ISSUE THREAD

**Issue by Enider890** [SallyWhitemane/Maelstrom#577]
**Description:** Lumbering Oaf/Helix Gearbreaker bugs out if you wipe on him, or at least did for me. Becomes untargetable but is still a hostile entity. Helix also seems to be attacking twice as fast/doesn't do reduced damage with offhand.

**How to reproduce:** I was solo'ing Deadmines on a warlock (for some reason I spawned in there when I logged on and decided, why not?) and when Lumbering Oaf grabbed me for the mechanic, my minion zoomed off into the wall at a million miles an hour. Took a good 6 seconds or so to come back and I had gotten threat and died before my minion pulled threat off me. When I came back in the room, this is how he was. Oaf was gone, and an untargetable Helix in his place. The wipe wasn't after Helix had hopped off Lumbering Oaf, the boss was still probably at 98% because this happened pretty much immediately, so I'm not sure why Lumbering Oaf didn't show back up.

Edit: Even in a normal attempt, when he grabs a warlock the summoned demon despawns, like if you get on a flight path or something. Worth mentioning because if it happens to a dps in a normal dungeon group, that's lost damage for a lock, potentially with resummon time too

Note: Image shows that I have health bars on and am close enough for Helix's to be there, but he still won't show one and cannot be targeted. Soul shards are at 0 because I kept dying and needing to resummon minion while running back.

![image](https://user-images.githubusercontent.com/45482752/181298036-82fa166f-9d3b-4e35-9ebb-145827ca5988.png)

**How it should work:** Lumbering Oaf should be respawned as normal after a wipe, resetting for another attempt to kill the boss. Or Helix at least should be targetable so that he can be killed as per normal.

**Comment by MrTide** [comment]
Dungeon issues are already reported https://github.com/SallyWhitemane/Maelstrom/issues/530 hopefully they will fix it as soon as possible

**Comment by Afgann** [comment]
fixed
