### ISSUE TITLE
[Raid][MC] List of issues, still lots to do

### ISSUE THREAD

**Issue by phonkala** [SallyWhitemane/Maelstrom#578]
So went into Molten Core after couple weeks, finally got some gear to do it. There was quite a lot issues still but the boss HP is now fixed nicely! Also the killed dog packs before Magmadar didn't respawn anymore endlessly, which is nice :)

I don't think there is any point going into further detail before these are fixed, there was so much very basic issues that I couldn't finish the raid without GM spells, which I really should not need as a lvl85 HC cata raid geared. Not even as a lvl 80. 

Issues that I managed to take notes of:

- This one I'm not sure if it was changed on Cata, but at least in WotLK Baron Geddon's path ends way much closer to the tunnel where you enter the room, very close to where I'm waiting. Currently he barely came to the bottom of the slope he is patrolling. In the screenshot below he just turned back, screenshot might be 1-2sec late but he should come way further down, as you devs probably know from WotLK. As said, unless it was changed in Cata.

![WoWScrnShot_072822_231902](https://user-images.githubusercontent.com/43609330/181641667-93797d78-bad8-4517-b0ef-1826ee58c244.jpg)

- Dogs do not show any mark that they can see you from stealth. They do still attack you when you are stealthed, even if you go past them from far far away, and they are only lvl 59 or so, and I'm 85 - doesn't seem correct. On latest wotlk servers I've played on I can pass them in stealth even as a lvl 60. Once again, not sure if and how they were changed in Cata. Anyone that knows better please do comment.

- Baron Geddon reseted to full HP every time when he used the knockback. Wasn't able to kill him "normally" without getting his knockback and then he always started first evading, then resets hp to full (and stays full after) and keeps attacking. So probably just the same thing that happened on so many other dungeon bosses with knockback ability that I have previously reported.  Also, when I used Shadowmeld he just disappeared every time (unless I was right next to him).

- Sulfuron Harbinger was hitting way too hard with his melee, he did 50k+ crits with basic melee attacks, when talents like Flame Spear did only bit below 1k dmg. He could probably 2-3 shot me in 85 HC tier gear (I had 100k+ hp in cat form). Also, running away and Shadowmelding did reset his adds but not him. Adds should not reset.

- Golemagg adds are not linked to the boss, happened also on ALL the other bosses with adds. They got never pulled when I attacked Golemadd. So basicly boss adds that should be linked to bosses can be taken out of the fight easily with just pulling boss away and Shadowmelding, adds go back to their original spots and do not re-engage.

- Majordomo adds were also not linked to boss, but this one I had to mention separately. The adds were standing at their original spots, but they were still healing the boss etc. They were getting the magic shield. They had **no animations** (no casting etc) except just standing there. When I attacked and killed those, all went "normally", but I think I could have killed Majordomo even with never attacking the adds.

- Ragnaros was attackable right away after he was summoned, during his rp. During every knockback he did and flew me into air, he reseted his to full hp, also reseted combat. Had to kill with GM spells as these is lots of knockback in that fight.

- I did die couple times as I really didn't want to use GM spells unless forced to. The boss corpses and the loot never despawned and I was in MC for more than 2h I think, at least easily more than 1h 30min. Should they not despawn?

**Comment by Afgann** [comment]
fixed
