### ISSUE TITLE
Can't equip gear

### ISSUE THREAD

**Issue by Zano74** [SallyWhitemane/Maelstrom#584]
**Description:**
I cannot equip any gear. I am a goblin hunter and I cannot equip leather or cloth items. I can equip weapons but not gear. 

**How to reproduce:**
Try to equip a new item and get the error text " you do not have the required proficiency for that item"

**How it should work:**
I should be able to equip any leather or cloth item.

**Comment by ghost** [comment]
@Zano74 Give me an example of such items

**Comment by Zano74** [comment]
@UltraNix such as Thrall's Gift, Banner Cloak, or Whirling Axe.

**Comment by ghost** [comment]
@Zano74 Should be okay now.
