### ISSUE TITLE
Got Wood?

### ISSUE THREAD

**Issue by Zano74** [SallyWhitemane/Maelstrom#585]
**Description:**
The quest Got Wood? does not provide Kadrak's reins. This means the player cannot ride Brutusk and therefore cannot complete the quest. 

**How to reproduce:**
Accept the quest Got Wood? after completing the previous quests in the chain. Go to mount Brutusk and get the error text " missing reagent Kadrak's reins"

**How it should work:**
The player should get the reins from the quest giver Truun.

**Comment by ghost** [comment]
Just talk to Kadrak.
`Speak with Kadrak to get [Kadrak's Reins](https://www.wowhead.com/item=45051/kadraks-reins) to ride Brutus.`
No bug here.
