### ISSUE TITLE
Unholy Death knight transformed pet stun range

### ISSUE THREAD

**Issue by Kenniflopper** [SallyWhitemane/Maelstrom#616]
**Description:**
Currently unholy death knight transformed pet stun has a long range, i believe its due to using petmoveto and then casting the stun (not sure tho) 

**How to reproduce:**
https://clips.twitch.tv/AmericanToughBeanTheTarFu--Btyd4NuJ_7Pmb7k (can turn the vid down to 0.25 to see the range properly)

**How it should work:**
Transformed unholy dk pet stun should be melee ability, not have any range.

**Comment by Afgann** [comment]
fixed
