### ISSUE TITLE
[NPC] Roloch (#14488) does not aggro or take damage

### ISSUE THREAD

**Issue by ghost** [SallyWhitemane/Maelstrom#73]
**Description:**
Roloch (#14488) does not engage in combat, regenerates, and locks player in combat. Similar to #15  

**How to reproduce:**
- Engage Roloch in combat
- He will continue walking

**How it should work:**
Roloch should engage in combat as any mob would

https://user-images.githubusercontent.com/106853563/172694386-621e525b-a4ed-4683-b1e0-ae9cbf3a1fc0.mp4

**Comment by Afgann** [comment]
works fine
