### ISSUE TITLE
[Quest] High Priest Venoxis (Horde side) missing various features

### ISSUE THREAD

**Issue by ghost** [SallyWhitemane/Maelstrom#76]
**Description:**
Wowhead link: https://www.wowhead.com/quest=26555/high-priest-venoxis
This quest is missing various elements; there are no adds, no particle effects on High Priest Venoxis, or the scripted event with Shade of the Hexxer after killing the High Priest. I was unaware of how this quest should look until I watched a video, as it felt like something was missing.

It is worth noting that I was still able to complete the quest after hitting High Priest Venoxis' body until it's health reached zero, which completed the quest criteria successfully. Therefore, while it is missing scripted elements, it is not game breaking in the sense of preventing progress through the quest. I linked a video below in the "how it should work" section.

**How to reproduce:**
- Progress through the quest chain to High Priest Venoxis in Cape of Stranglethorn
- Begin attacking Zanzil and High Priest Venoxis
- Note that the elements listed in the above and below sections are missing from the fight

**How it should work:**
- Venoxis should have a green particle effect around his body
- Adds should spawn to heal Venoxis
- After killing Venoxis, there should be a scripted event where the player is stunned and Shade of the Hexxer attempts to kill the player if they don't click on a ladder from an escape balloon

See this video for how the fight should look: https://youtu.be/Z5snxP4qs7Q?t=71

**Comment by MrTide** [comment]
Can confirm still got issues
