### ISSUE TITLE
[Northshire Valley] Target Dummys

### ISSUE THREAD

**Issue by bovanova1** [SallyWhitemane/Maelstrom#78]
**Description:**
Target Dummys do not regain HP / Do not die and respawn after putting on damage

**How to reproduce:**
Human Starting zone has multiple Target Dummys to practice spells. They do not regain HP / dont respawn cannot be killed

**How it should work:**
I think they are supposed to die then respawn (after a short duration)
![image](https://user-images.githubusercontent.com/106834485/173053061-72cfe70b-bb7a-4322-b4a6-41e14253f79d.png)

**Comment by ghost** [comment]
Nope. They cannot be killed. It's blizzlike.
