### ISSUE TITLE
[NPC] Duplicate Auctioneer Graves in Booty Bay

### ISSUE THREAD

**Issue by ghost** [SallyWhitemane/Maelstrom#85]
**Description:**
Auctioneer Graves in Booty Bay (NPC ID #15677) appears to have cloned himself.

**How to reproduce:**
Go to Auctioneer Graves in Booty Bay

**How it should work:**
There should only be one of him on the crate
![Auctioneer Graves](https://user-images.githubusercontent.com/106853563/173143371-41ee31c3-f589-499a-bbd9-b1d2404f4ef5.png)

**Comment by Afgann** [comment]
fixed
