### ISSUE TITLE
[Dungeon] Sunken Temple - Maelstorm PTR Server - Avatar of Hakkar - bugged

### ISSUE THREAD

**Issue by Arkasus11** [SallyWhitemane/Maelstrom#96]
Testing all Dungeons von Maelstrom PTR Server

Sunken Temple is okay - only 1 Boss cant resporn " Avatar of Hakkar"
so the Quest ind the Dungeon "The Blood God Hakkar" is not makeable

**Comment by ghost** [comment]
Everything works okay. Boss is summoned after 80 sec.
